### PR TITLE
MONIT - lightweight ATSIGN HACTRN replacement.

### LINKED ISSUE #996: MONIT - DM HACTRN alternative
SYS; TS MONIT  
SYSENG; MONIT 114  
DMCG; MONIT 200

### PR DESCRIPTION
**Pull request by atsampson**
A shell for ITS machines with limited memory.

This is MONIT 200 circa 1972, which works without modification (unlike the 1971-vintage MONIT 114).

Fixes #996.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
A suggestion: How about committing MONIT 114 before this, and do a rename+update in the second commit?  That way there's be a historical record of the arcane version.

You mentioned possible runtime errors.  Have you been able to provode them?

**Comment by larsbrinkhoff** [comment]
The change is to add a link. From SYS; TS DDT to SYS; ATSIGN DDT.  Just like in PI and the AI dump.

**Comment by eswenson1** [comment]
Ah, ok. That’s great. Can’t tell that from Github issue from phone interface.

**Comment by larsbrinkhoff** [comment]
There's no documentation, is there?  Adam, you probably tested this so what was it like?  Is it a subset of DDT commands?

**Comment by larsbrinkhoff** [comment]
It it like MONIT mode?

**Comment by atsampson** [comment]
Yes, it's much like :MONMODE. Type "help" for a list of commands, most of which have shorter aliases:

```
;help
Commands
ASSIGN  ASN
CONTIN  CON
DELETE  DEL
DESIGN  DES
DISOWN  DIS
FLAP
FLUSH
HELP    HOW
KILL    K
LISTF   LF
LOAD    GET
LOGIN   LOG
LOGOUT  BYE
OWN     JOB
PRINT   TYP
PROCED  P
RUN     R
START   GO
STOP
SYSTAT  WHO
TIME    TI
TRANS
UINIT
UNTRAN
USER
```

I was pretty impressed at how much it does given how short the source is!

**Comment by atsampson** [comment]
(You don't have to do anything special to try it for yourself under DDT - just do `:monit` to start it, and `logout` then `:kill` when you're done.)

**Pull request merged**
