### PR TITLE
Add Chaosnet hosts to table

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
All of these:

| Number | Name |
| --- | --- |
| 440, 3040, 7001 | MX-11.Update.UU.SE |
| 3041 | MX12.Victor.SE |
| 3127 | CC.Cosmic.COM |
| 3141 | MD.Update.UU.SE |
| 3144 | BV.Victor.SE |
| 3160 | ES-ITS.Swenson.ORG |
| 3401 | MX12.Victor.SE |
| 3402 | JJ.Victor.SE |
| 3403 | CDR.Victor.SE |
| 3404 | SRV.Victor.SE |
| 3405 | BV.Victor.SE |
| 3412 | Amnesia.aosnet.CH |
| 3430 | Lambda-X.Victor.SE |
| 401 | Greek.UPDATE.UU.SE |
| 442 | Lambda-D.UPDATE.UU.SE |

### CODE REVIEW

**Comment by bictorv** [comment]
> @SMJ, @bictorv I suggest adding 3130 for LC. Or should be reserve the historical ITS hosts?

Should what be what? 

What domain is LC in? Does it have IP (v4/v6) connectivity?

**Comment by bictorv** [comment]
> @SMJ, @bictorv I suggest adding 3130 for LC. Or should be reserve the historical ITS hosts?

Should what be what? 

What domain is LC in? Does it have IP (v4/v6) connectivity?

**Comment by larsbrinkhoff** [comment]
LC isn't reachable yet, and it only has a CH11 card, no working Ethernet.  But I hope it can be hooked up some day.

**Comment by larsbrinkhoff** [comment]
@bictorv, what is the machine and system types for MX-11, MX12, JJ, CDR, SRV, Amnesia, Lambda-D, Lambda-X, and Greek?

Greek is the Update 3600, right?

**Comment by larsbrinkhoff** [comment]
This shows some MIT Chaos subnets.

**Comment by larsbrinkhoff** [comment]
I was thinking that "LISPM" isn't a very nice name for the Lispm operating system.  But then I saw the older host tables did use that name, so I'm not about to suggest anything else.

RFC810 doesn't suggest anything:

```
Current operating system acronyms are:

   ASP          KRONOS       RSX11M      VMS
   AUGUST       MCP          RT11        WAITS
   BKY          MOS          SCOPE
   CCP          MPX-RT       SIGNAL
   DOS/360      MULTICS      SINTRAN
   ELF          MVT          TENEX
   EPOS         NOS          TOPS10
   EXEC-8       NOS/BE       TOPS20
   GCOS         OS/MVS       TSS
   GPOS         OS/MVT       UNIX
   ITS          RIG          VM/370
   INTERCOM     RSX11        VM/CMS

**Comment by bictorv** [comment]
> This shows some MIT Chaos subnets.

You can also find a list in SYSHST;HSTNET > on a PI-based system (such as UP).
(There are quite a lot of historically interesting files there, I don't know if/where they are in the Github system?)

**Comment by larsbrinkhoff** [comment]
> There are quite a lot of historically interesting files there, I don't know if/where they are in the Github system?

Some.  They are added on a case-by-case basis.  As you can imagine, it takes a bit of time.

**Pull request merged**
