### PR TITLE
Mini Prolog

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Nils M Holm pointed me to this file: https://www.saildart.org/AI.V1[BB,DOC]

It contains a "tiny Prolog" by @ToonTalk, and another "FOOLOG" by Martin Nilsson.  They are both written in Maclisp, arguably the premier Lisp dialect.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Not sure if we need to do anything with these other than have the files around as examples of Maclisp code.

**Comment by larsbrinkhoff** [comment]
Not sure if we need to do anything with these other than have the files around as examples of Maclisp code.

**Comment by eswenson1** [comment]
Why aren’t these compiled as part of the build? Do they compile?

**Comment by larsbrinkhoff** [comment]
I haven't tested them in any way.  They are snippets of code found on
the net, claiming to be written for Maclisp.

**Pull request merged**
