### PR TITLE
ATSIGN CHAOS - Chaosnet support.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
We didn't have DEVICE; ATSIGN CHAOS built, even thought the source is there.  I'm about to try using Chaosnet, so I'm adding it now.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@bictorv Should we add BV to MLDEV/SLV in this repository, or should it be private?

**Comment by bictorv** [comment]
You can leave BV out, I haven't run it for ages.

**Comment by larsbrinkhoff** [comment]
Sorry, I meant to write UP!

**Comment by bictorv** [comment]
Oh, please add UP! It would be fun to have a large(r) Chaosnet!

**Comment by eswenson1** [comment]
And ES!

**Pull request merged**
