### PR TITLE
IMEDIT - Text editor for Imlac

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
We have these binary files:

IMSRC; IMEDIT BIN, backed up 1972-12-15  
SYS; TS IMEDIT, backed up 1973-06-14  
SYS1; TS IMEDIT, timestamp 1975-02-13 - version 168  

Documentation:  
.INFO.; IMEDIT ORDER  
.INFO.; IMEDIT RECENT

### CODE REVIEW

**Comment by jh95468** [comment]
Well, 50 years is getting to be a long time, I'm going to need a Hubble soon....

So, IIRC:

Imedit and Emacs were developed at about the same time.  I remember both, but don't remember which was first.

In the early 70s, TECO was the primary editor in use within the ITS world, typically on a hardcopy (TTY33/35) or VT52 CRT terminal.  You'd type your edit command and include "0ltt" at the end, which would cause the line after editting to be printed out so you could see if you got it right.  TECO was effectively a programming language, and the "edit buffer" was a Turing Machine.  We all wrote lots of programs for that Turing Machine, conceptually moving the cursor back and forth on the "tape" to create text files.   Every command to TECO was a program, and some people could write impressively long programs, with the final <ESC><ESC> to see if they got it right.  Hey, it was better than submitting card decks to the computer center and seeing the results tomorrow when you picked up the listing!

The Imlacs came with a basic terminal emulator program, which included the ability to use the keys on the Imlac to manipulate text on the screen.   The physical keyboard also included a "Page Xmit" key, which would send the entire contents of the screen/memory out the TTY line.  So that kind of editting capability came from Imlac with the hardware.  What PDL and I did was interface it to the PDP-10 in a "client-server" type of setup (although I don't think the term "client/server" existed yet - perhaps we were the first!?).

TECO influence IMEDIT a lot, e.g., the cursor motion and many other commands were the same keys you would use for similar actions in TECO.   That made it much easier for diehard TECO users to learn how to use IMEDIT.

My memory of ^R mode is vague.  It may be that "^R Mode" was what EMacs became after it became a built-in part of TECO.  At first, the WYSIWIG TECO capability was provided by RMS' macro package.  To use it you would cajole RMS to give you a copy of the file, put it on your ITS machine, fire up TECO, and load the macro file into a Q-register.  (by typing 0EREMACS$YHXE$$, or something like that...)  

There were several macro packages in common use at the time, but it became standard practice to load RMS' macros into the "E" Q-register.  (E for Edit) To use them in TECO, you'd type ME$$ which would fire up the E register macros.  So naturally they were called the "E Macros", or EMacs....   I suspect that ^R Mode was just a subsequent shortcut installed in TECO to make it easy to start Emacs by a single keystroke.

But I don't recall which came first - the IMEDIT editor or RMS' macros.

BTW, if anyone's curious about such early WYSIWIG editting, I recently found another artifact in my basement - the project report from a "Digital Systems Project Laboratory" course I took at MIT as an undergraduate in 1969.  We built a very, very rudimentary WYSIWIG text processor - all in hardware.  So my 1969 hardware "text editor" experience undoubtedly was also an influence on IMEDIT.   If anyone's curious I can upload the report (lots of logic diagrams), One page is attached here FYI.

DigSysLab1969

/Jack Haverty

**Comment by jh95468** [comment]
Well, 50 years is getting to be a long time, I'm going to need a Hubble soon....

So, IIRC:

Imedit and Emacs were developed at about the same time.  I remember both, but don't remember which was first.

In the early 70s, TECO was the primary editor in use within the ITS world, typically on a hardcopy (TTY33/35) or VT52 CRT terminal.  You'd type your edit command and include "0ltt" at the end, which would cause the line after editting to be printed out so you could see if you got it right.  TECO was effectively a programming language, and the "edit buffer" was a Turing Machine.  We all wrote lots of programs for that Turing Machine, conceptually moving the cursor back and forth on the "tape" to create text files.   Every command to TECO was a program, and some people could write impressively long programs, with the final <ESC><ESC> to see if they got it right.  Hey, it was better than submitting card decks to the computer center and seeing the results tomorrow when you picked up the listing!

The Imlacs came with a basic terminal emulator program, which included the ability to use the keys on the Imlac to manipulate text on the screen.   The physical keyboard also included a "Page Xmit" key, which would send the entire contents of the screen/memory out the TTY line.  So that kind of editting capability came from Imlac with the hardware.  What PDL and I did was interface it to the PDP-10 in a "client-server" type of setup (although I don't think the term "client/server" existed yet - perhaps we were the first!?).

TECO influence IMEDIT a lot, e.g., the cursor motion and many other commands were the same keys you would use for similar actions in TECO.   That made it much easier for diehard TECO users to learn how to use IMEDIT.

My memory of ^R mode is vague.  It may be that "^R Mode" was what EMacs became after it became a built-in part of TECO.  At first, the WYSIWIG TECO capability was provided by RMS' macro package.  To use it you would cajole RMS to give you a copy of the file, put it on your ITS machine, fire up TECO, and load the macro file into a Q-register.  (by typing 0EREMACS$YHXE$$, or something like that...)  

There were several macro packages in common use at the time, but it became standard practice to load RMS' macros into the "E" Q-register.  (E for Edit) To use them in TECO, you'd type ME$$ which would fire up the E register macros.  So naturally they were called the "E Macros", or EMacs....   I suspect that ^R Mode was just a subsequent shortcut installed in TECO to make it easy to start Emacs by a single keystroke.

But I don't recall which came first - the IMEDIT editor or RMS' macros.

BTW, if anyone's curious about such early WYSIWIG editting, I recently found another artifact in my basement - the project report from a "Digital Systems Project Laboratory" course I took at MIT as an undergraduate in 1969.  We built a very, very rudimentary WYSIWIG text processor - all in hardware.  So my 1969 hardware "text editor" experience undoubtedly was also an influence on IMEDIT.   If anyone's curious I can upload the report (lots of logic diagrams).  
DigSysLab1969
 One page is attached here FYI.

/Jack Haverty

**Comment by jh95468** [comment]
Well, 50 years is getting to be a long time, I'm going to need a Hubble soon....

So, IIRC:

Imedit and Emacs were developed at about the same time.  I remember both, but don't remember which was first.

In the early 70s, TECO was the primary editor in use within the ITS world, typically on a hardcopy (TTY33/35) or VT52 CRT terminal.  You'd type your edit command and include "0ltt" at the end, which would cause the line after editting to be printed out so you could see if you got it right.  TECO was effectively a programming language, and the "edit buffer" was a Turing Machine.  We all wrote lots of programs for that Turing Machine, conceptually moving the cursor back and forth on the "tape" to create text files.   Every command to TECO was a program, and some people could write impressively long programs, with the final <ESC><ESC> to see if they got it right.  Hey, it was better than submitting card decks to the computer center and seeing the results tomorrow when you picked up the listing!

The Imlacs came with a basic terminal emulator program, which included the ability to use the keys on the Imlac to manipulate text on the screen.   The physical keyboard also included a "Page Xmit" key, which would send the entire contents of the screen/memory out the TTY line.  So that kind of editting capability came from Imlac with the hardware.  What PDL and I did was interface it to the PDP-10 in a "client-server" type of setup (although I don't think the term "client/server" existed yet - perhaps we were the first!?).

TECO influence IMEDIT a lot, e.g., the cursor motion and many other commands were the same keys you would use for similar actions in TECO.   That made it much easier for diehard TECO users to learn how to use IMEDIT.

My memory of ^R mode is vague.  It may be that "^R Mode" was what EMacs became after it became a built-in part of TECO.  At first, the WYSIWIG TECO capability was provided by RMS' macro package.  To use it you would cajole RMS to give you a copy of the file, put it on your ITS machine, fire up TECO, and load the macro file into a Q-register.  (by typing 0EREMACS$YHXE$$, or something like that...)  

There were several macro packages in common use at the time, but it became standard practice to load RMS' macros into the "E" Q-register.  (E for Edit) To use them in TECO, you'd type ME$$ which would fire up the E register macros.  So naturally they were called the "E Macros", or EMacs....   I suspect that ^R Mode was just a subsequent shortcut installed in TECO to make it easy to start Emacs by a single keystroke.

But I don't recall which came first - the IMEDIT editor or RMS' macros.

BTW, if anyone's curious about such early WYSIWIG editting, I recently found another artifact in my basement - the project report from a "Digital Systems Project Laboratory" course I took at MIT as an undergraduate in 1969.  We built a very, very rudimentary WYSIWIG text processor - all in hardware.  So my 1969 hardware "text editor" experience undoubtedly was also an influence on IMEDIT.   If anyone's curious I can upload the report (lots of logic diagrams).  
DigSysLab1969
 One page is attached here FYI.

/Jack Haverty

**Comment by jh95468** [comment]
Sorry for the duplicate comment.  When I hit the "Comment" button, github said "You can't comment at this time".  Never saw that before, but I waited a few minutes and tried again.  Same result.  But apparently the comment was accepted, both times, even though the system said otherwise.   Maybe a github bug...?

**Comment by larsbrinkhoff** [comment]
Thank you.  Sorry for asking about events long back in time.

I think I'm on quite firm ground with this timeline:

- 1967 - ITS up and running on AI lab PDP-6.
- TECO presumably ported to ITS soon after.
- 1971 - IMEDIT memos SYS.08.01.  (Copies linked above.)
- 1972 - ^R mode started by @foxkit.  (As per comments in TECO 355.)
- 1976 - EMACS started by @GuySteele, RMS, @david-moon, et al.

As you can see, IMEDIT predates EMACS by a good margin.

**Comment by jh95468** [comment]
Thanks for the timeline.   I'm curious about the EMACS milestone.  I left MIT in 1977, and am pretty sure I used EMACS for quite a few years before I left.  By 1976, much of the group's work was being done in Muddle, and the Muddle editting/debugging tools (now you'd say IDE) were more commonly used than EMACS.

Is the 1976 EMACS historical trail about the origin of the TECO macro package?  Or was it about the implementation of EMACS as a separate program rather than a bunch of TECO macros?  I suspect it is the latter, since my memory is that we were using Emacs (the macros) well before 1976.

FYI, TECO, DDT, et al originated at TMRC - Tech Model Railroad Club, which was experimenting with using computers to control their railroad setup.  Necessity was the mother of invention, to make the hardware useful.   At least that's what I was told when I joined the ITS world in 1970.   Some of the MIT-AI hackers came from the TMRC world, and brought their tools with them to ITS.

**Comment by larsbrinkhoff** [comment]
I do believe your document would be of interest to @ericfischer, who maintains a great collection of documents about early text editors: https://archive.org/search.php?query=subject%3A%22enf-editors%22

**Comment by larsbrinkhoff** [comment]
@jh95468, we have backed up files and email correspondence from late 1976 when the editor changed name from ? or ?MACS, to E or EMACS.  I believe it's fairly well established elsewhere that development began earlier that year, in the summer.  This summary is consistent with other evidence I have found: http://www.codeartnow.com/hacker-art-1/macsimizing-teco

You may remember earlier TECO macro packages such as TMACS, TECMAC, and RMODE, most of which fed into EMACS in one way or another.

**Comment by jh95468** [comment]
Yes, that makes sense.  The name "EMACS" might have stabilized in 1976.   Before that we used RMS' macros, which were commonly loaded into the E Q-register.   I'm pretty sure RMS wrote the first macros, but of course there were lots of ideas floating around so other people wrote useful macros too.   I think of all of those collectively as "Emacs", with the earliest being the package that RMS wrote.   I remember occasionally trying to convince RMS to make some addition or change to his macros, which he kept tightly controlled.

So "Emacs" per se might have congealed around 1976, but TECO WYWSIWIG editting was in heavy use well before that, often with macro packages loaded into the E Q-register.

Were the 1976 EMACS implementations written as TECO macros?   Or something else - PDP-10 assembler, LISP, ...?

/Jack Haverty

**Comment by larsbrinkhoff** [comment]
EMACS from 1976 and on was written as TECO macros, but heavily supported by extensions to TECO written in MIDAS assembly language.

New implementations: EINE, SINE, Multics Emacs, were written in Lisp in 1977-1978.

**Comment by jh95468** [comment]
That's consistent with my memory; I don't recall EMACS being other than TECO macros while I was at MIT.  I *still* use Emacs, now on Linux.   Amazing longevity for software...

There were lots of interesting things written in TECO.   I remember someone once even wrote an ITS emulator -- implemented in TECO macros!   Just to see if it could be done...  The TECO program would open up all free TTY ports as devices and display the ITS login herald, just like real ITS.  You could login and even run programs, which I think were just run as ITS jobs inferior to TECO.   The "extensions to TECO written in MIDAS" made all sorts of such gyrations possible as TECO hacks.   Some of them, like Emacs, were even useful.

**Comment by GuySteele** [comment]
Thanks for the cc's.  As far as I am able to to verify, you have all the facts straight in this thread (I am not surprised).

—Guy

**Comment by eswenson1** [comment]
I get a kick out of the fact that I regularly use Emacs on Multics, ITS, Linux, and my Mac. And I do mean “these days”!

**Review by eswenson1 — APPROVED** [review]
No source for IMEDIT? Really?

**Comment by larsbrinkhoff** [comment]
Not a scrap of source, I'm afraid.  I think we're unlucky that IMEDIT development probably slowed by the time the tapes we have were made.  These are from DM .TAPE files:

```
 SYSENG  IMEDIT  172    1975-10-18 15:33:29
 SYSENG  IMEDIT  173    1975-12-05 10:54:53
 SYSENG  IMEDIT  173    1976-01-23 17:32:43
 SYSENG  IMEDIT  174    1976-11-11 11:11:44
 SYSENG  IMEDIT  175    1977-03-10 18:12:05
 SYSENG  IMEDIT  176    1977-09-06 15:15:21
 SYSENG  IMEDIT  177    1977-09-13 12:44:49
```

**Comment by eswenson1** [comment]
Bummer.  I guess it's time for you to reverse-engineer and create source then, huh?  :-)

**Comment by larsbrinkhoff** [comment]
Oh, I wouldn't dream of taking that joy away from you!

**Comment by jh95468** [comment]
I was the author of the PDP10 side of IMEDIT, at least through mid-1977 when I left MIT.   So if there were new versions of Imedit, 172-175, in that timeframe, the sources were changed to create them, and the sources were probably in DSK:JFH;  on DM.  As I was leaving, they were probably moved into some SYSxxx directory, or possibly into PDL; (Dave Lebling was the Imlac-side implementer).

Everything was in PDP10 assembler, a necessity to tighten the code enough to fit into one block of memory, at least until we got disks/virtual memory on DM.   It therefore wasn't a large source file, just a handful of pages which mostly did the disk and TTY I/O, and processed the CTRL commands. I.e., there wasn't any editting functionality on the PDP10 side.

IIRC, there were some commands which weren't possible in one block of core, and were added later when IMEDIT grew to occupy 2 blocks.  

If/when I get my personal files from MIT's archive and they contain the IMEDIT sources, I'll submit them here.

/Jack Haverty (JFH@MIT-DM, 1970-1977)

**Comment by eswenson1** [comment]
@larsbrinkhoff Are you sure that all the source files in the various copies of the IMSRC directories don't get combined in some way to create TS IMEDIT?  -- that the source file might not have a FN1 of "IMEDIT"?

**Comment by eswenson1** [comment]
There is an interest source called IMSRC;NIMED RUSSIA on tape 7005620.  It has the title "NIMED" and inserts IMDEFS >.  I wonder if this is a New IMEDIT?

**Comment by jh95468** [comment]
It's been a long time, but IIRC IMSRC was primarily where source code for the Imlacs was kept.   I didn't write any Imlac code, which would explain why I don't remember using IMSRC.    Again IIRC - IMEDIT was probably one main source file, possibly with a few .INSRTs of other files containing things like commonly used Midas macro definitions and config parameters.   I'm pretty sure, at least in the early period, it didn't use anything like libraries of subroutines, because that would have used too much memory.

The core of IMEDIT was just a loop that waited for TTY input from the Imlac, and used very small buffers (just big enough to hold one line IIRC) to pass data between disk files (in and out) and TTY (out and in).   Any control character received was checked to see if it was a command, and if so the command was executed; if not it went to the output file.   It was simplex communication, reading from the Imlac and writing to the output, or for control commands possibly outputting to the Imlac and when that completed returning to reading from the Imlac.  No interrupts or multi-threading etc.

**Comment by jh95468** [comment]
Actually, IIRC the first version of IMEDIT was written in less than a day.  We had these Imlacs, and they had this built-in standalone editor capability including a "Page Xmit" key.   So PDL and I created a way to link the Imlacs to the PDP10 disk; I wrote the PDP10 side and he tweaked the Imlac side.

Maybe Lars and Eric can have a code-off to see who can get it working faster...
/Jack

**Comment by larsbrinkhoff** [comment]
@eswenson1, I'm pretty sure the source isn't there.  From DM we have mostly incremental backups from 1977 so the coverage is spotty.  I even grepped all files for the string IMLAC which should be there, but no good hits.

NIMED sounds interesting but I have previously seen a connection so SIC; see #1794.  (SIC is something that was running on the Imlacs before SSV.)  IMEDIT shouldn't insrt IMDEFS because it's PDP-10 code.  The Imlac side by PDL is SSV.

**Comment by eswenson1** [comment]
Ok.  Bummer then.  I'll let Lars do the honors.  He likes playing with OLD STUFF.  I like new stuff (like Macsyma and ZORK)!  :-)

**Comment by jh95468** [comment]
PDL was into Russian; NIMED RUSSIA may have been a version that could he did to display the Russian character set.  /Jack

**Pull request merged**
