### PR TITLE
ITS version number history

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Extracted from MC: MAPS;

- 1971 - v672-674 (PDP-6?)
- 1972 - v720-724 (AI)
- 1973 - v785-850 (AI)
- 1974 - v915 (AI)
- 1975 - v994-998 (AI)
- 1976 - v1025-1044 (AI)
- 1976 - v997-998 (MC)
- 1977 - v1092-1097 (MC)
- 1980 - v1192-1196 (MC)
- 1982 - v1256-1278 (MC)

From AI: SYSTEM;

- 1988 - v1622-1632
- 1989 - v1633-1634
- 1990 - v1640-1644

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
*ITS 1.5 Reference Manual* from 1969 has a transcript from a session with ITS 530.

**Comment by larsbrinkhoff** [comment]
*ITS 1.4 Reference Manual* from 1968 mentions ITS 350.

**Comment by larsbrinkhoff** [comment]
_AIM-147A_ has a sample session from 1971-09-19.

- ITS 698
- DDT 317
- TECO 206
- MIDAS 75

**Comment by larsbrinkhoff** [comment]
_AIM-169_ has a sample session from 1969-12-08.

- DDT 159
- ITS 444
- PEEK 124
- LOCK 39

**Comment by larsbrinkhoff** [comment]
The best information I can find is that PDP-6 ITS was first operational in July 1967.  See AIM-138 (mentions TS and non-TS LISP), and Project MAC Progress Report IV.

ITS version 350 was clearly running on the PDP-6.  See AIM-161 from June 1968.

AIM-161A dated July 1969 mentions PDP-10, though it seems the PDP-6 was the primary timesharing host.

**Comment by larsbrinkhoff** [comment]
Open questions:

- When did ITS switch over to the PDP-10 as the primary host?
- When was virtual memory in operation?

**Comment by larsbrinkhoff** [comment]
http://bitsavers.org/pdf/mit/ai/aim/AIM-200.pdf mentions the 6 and 10 on equal terms.  Says pager to be completed early 1970, which is consistent with HW memo 2.

**Comment by larsbrinkhoff** [comment]
AIM-215 from April 1971 mentions ITS 671.

**Comment by atsampson** [comment]
[RFC 525](https://tools.ietf.org/html/rfc525), 1973-06-01, has a transcript of a session on ML with ITS 796, DDT 514, MACSYMA 212.

[RFC 578](https://tools.ietf.org/html/rfc578), 1973-10, has a transcript showing MUDDLE 42 on DM, and ITS 1 (?), DDT 516, MACSYMA 226 on ML.

**Comment by larsbrinkhoff** [comment]
ITS 1 may be a typo.  8x1 maybe?

**Comment by larsbrinkhoff** [comment]
Some digging in Saildart:
- https://www.saildart.org/FOO[CAR,HPM]2 - ITS 852, DDT 527
- https://www.saildart.org/AIDIR[1,DEK] - ITS 914, MACSYMA 251
- https://www.saildart.org/ALL.6[P,SYS]1 - ITS 1268

**Comment by larsbrinkhoff** [comment]
Login session from DM ITS, October 1971!

[RFC 254](https://tools.ietf.org/html/rfc254) - ITS 795 (747?), DDT 1334 (!), STINK T60, MIDAS 39, TECO 175

**Comment by atsampson** [comment]
A large collection of early 70s ITS hints, tips and software announcements (TECO, TJ6, SUPDUP, AGB chess, etc.): https://www.saildart.org/INFO.ITS[UP,DOC]

**Comment by larsbrinkhoff** [comment]
[AI memo 170](http://bitsavers.org/pdf/mit/ai/aim/AIM-170.pdf) by Jack Holloway describes a wirelist program.

The date of the memo is January 1969.  The transcript has the date 1929-01-09 (!) and ITS 454, I believe.

**Comment by larsbrinkhoff** [comment]
[Working paper/Vision flash 44](https://dspace.mit.edu/bitstream/handle/1721.1/41078/AI_WP_044.pdf), June 1972:

- LISP 229

**Comment by larsbrinkhoff** [comment]
- SYSEN2; DIRED 187 has a comment it was changed in 8/2/76 for ITS 1021.
- SYSNET; TELSER 149 mentions ITS 1004, but there's no date.
- .INFO.; LISP NEWS has a section from May 16, 1977 that mentions ITS 1051.

**Comment by atsampson** [comment]
Christopher Stacy in news:x8ln1bgk8do.fsf@world.std.com says:

> ITS implementation of TCP-IP was begun on November 10, 1982, nearly single-handedly by Ken Harrenstien, and MIT-MC was doing TCP on December 19th.  The other machines began running the TCP version of ITS on flag day: **MIT-AI started running ITS 1312 on December 31 at 21:03-EST** and it all worked. That included SMTP, FTP, TELNET, MLDEV, etc., etc.

**Comment by larsbrinkhoff** [comment]
That's rather precise!  I'm guessing there was some kind of log saved.

**Comment by larsbrinkhoff** [comment]
I had 1312 pegged at 1983 due to a message to ITS-BUGS from January 3, 1983.  I'll fix that and see what other 1983 verison is lowest.

**Comment by larsbrinkhoff** [comment]
[AI memo 215A](http://bitsavers.org/pdf/mit/ai/aim/AIM-215a.pdf), September 1971.

- TJ6 120

**Comment by larsbrinkhoff** [comment]
[AI memo 277](http://bitsavers.org/pdf/mit/ai/aim/AIM-277.pdf), February 1973.

- LISP 229CX

**Comment by atsampson** [comment]
Mary Ann Horton on 1983-08-30, in news:256@cbosgd.UUCP, has an FTP transcript:

> 220- MIT-MC ITS 1348,  FTP server 278

And Michael Fetzer in news:880302130156.2080021c@NMFECC.ARPA has a transcript of an FTP session between a UCSD Cray and MC on 1988-03-02:

> 220- MC.LCS.MIT.EDU ITS 1615,  FTP server 331 on  2 MAR 1988 1524 EST

**Comment by larsbrinkhoff** [comment]
There are two accounts of MC and AI ITS 1615 running in February-March 1988.  Yet there's a file listing with ITS 1616 dated December 1987.  I suppose it's not unlikely that an old version would have been running for a while.

**Comment by atsampson** [comment]
SYSDOC; ITS BUGS has a note from John Wroclawski on 1987-11-29 saying:

> I added a bunch of stuff to TCP to "optimize" (guess) the best packet size based on the path to the foreign entity, and to send and understand TCP max seg size options. [...] If you could talk to AI well last week and you can't now, please send a note before assuming you are being screwed by the arpanet.

... followed by six months of discussions about TCP state machine problems, eventually tracked down in May 1988 (not related to JW's change). So perhaps they reverted to the previous version at some point!

**Comment by larsbrinkhoff** [comment]
(It's JTW.  I added the T.)

**Comment by atsampson** [comment]
JGA on 1985-05-31 quoted in news:6ad9ar$o3d$1@nntp.ucs.ubc.ca:

> MIT Maximum Confusion PDP-10
> MC ITS.1488. PWORD.2632.
> TTY 57
> 16. Lusers, Fair Share = 86%

Keith F. Lynch had a transcript of a TAC session from March 1980 in news:8cbru6$s7n$1@saltmine.radix.net:

>  @O 134
>  Trying...
>   Open
>  MIT A.I. Lab PDP-10
>      SYSTEM IS HEAVILY LOADED DAYS AND EVENINGS
>  ***TOURISTS: DO NOT LOG IN BETWEEN 9 AM-MIDNIGHT ***
>
>  AI ITS.1168. PWORD 1733.
>  TTY 44
>  11. LUSERS, FAIR SHARE = 35%
>
>  The capacity of this system is about 15 users.  When there are 24 users
>  logged in, as has been true during the day recently, no one gets any work
>  done. Please act accordingly.

And, of course, there's this from 1980-04-01, quoted by Tim Shoppa in news:37037A38.4977B622@trailing-edge.com:

> XX ITS.1168. PWORD.1733.
> TTY 116
> 3. Lusers, Fair Share = 23%
> Due to popular demand, TWENEX has been flushed in favor of
> ITS.  Please update your programs.
>
> *kmp
> *login
> You must type a ":" before commands
> *:login kmp
> Password:
> April Fool!
>  Job 24 on TTY116 1-Apr-80 13:12
>  Previous login: 1-Apr-80 12:19 from host MIT-MC
>  End of LOGIN.CMD.4
> @

**Comment by larsbrinkhoff** [comment]
A new method.  Some binaries include information about which machine and ITS version where used to dump them.

For example, SYS2; TS MSEND has SYSNAM set to MC, and SYSVER set to 1359.  Assembly info says it was assembled 1980-07-28.

**Comment by larsbrinkhoff** [comment]
But it's not the date of the assembly, but the binary file timestamp that's interesting.  For the MC MSEND, it's 1984-01-14.

**Comment by atsampson** [comment]
- AI: SYS2; TS MSEND has timestamp 1984-01-15 and SYSVER 1359.
- MC: SYS2; TS XXFILE has timestamp 1990-09-19 and SYSVER 1604.
- AI: SYS2; TS XXFILE has timestamp 1989-06-23 and SYSVER 1533.

DEMST and GUNNER also have this mechanism, but no binaries.

**Comment by larsbrinkhoff** [comment]
PEEK does something similar.

- AI: SYS; TS PEEK - 1990-09-24, 1643.
- AI: SYSNEW; TS PEEK - 1990-09-18 1633.  Maybe SYSNEW has copies?
- MC: SYS; TS PEEK - 1990-04-29, 1650.

**Comment by larsbrinkhoff** [comment]
Note that MC: DUPSYS; ITS 1650 has timestamp 1989-02-01, a year earlier than AI; SYSTEM; ITS 1644.

**Comment by larsbrinkhoff** [comment]
One new from https://www.media.mit.edu/videos/144-lisp-logo-demonstration-henry-liberman/

- ITS 949 - 1975-09-29.

**Comment by larsbrinkhoff** [comment]
Saildart transcripts:

- ITS 775 - 1973-01-19
- AI ITS 1323 - 1983-01-20
- ML ITS 1317 - 1983-01-20
- DM ITS 1268 - 1983-01-20
- ITS 1102 - 1978-03-03
- ITS 1066 - 1977-11-26
- ITS 816 - 1973-07-25
- MC ITS 1268 - 1982-06-27
- MC ITS 1207 - 1981-04-13
- MC ITS 1192 - 1980-07-19
- AI ITS 914 - 1974-11-24
- AI ITS 905 - 1974-09-12
- AI ITS 1136 - 1979-02-01
-

**Comment by larsbrinkhoff** [comment]
From .TAPE*n* databases:

- ITS 699 - 1971-09-21
- TECO 209 - 1971-09-22
- TECO 210 - 1971-09-22
- DDT 317 - 1971-09-21
- DDT 344 - 1972-03-02
- DDT 385 - 1972-05-01
- PEEK 208 - 1971-09-021
- PEEK 234 - 1972-10-17
- DUMP 1 - 1972-06-26
- DUMP 2 - 1972-08-11

Interesting to see the first version of DUMP.  There was something called DMP before this.

**Comment by larsbrinkhoff** [comment]
[AI memo 215](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AIM-215.pdf), April 1971:

- ITS 671
- DDT 274
- TECO 100, inconsistent with TECO 175 above

**Comment by larsbrinkhoff** [comment]
Winston and Horn, "LISP" 1st ed:

**Comment by larsbrinkhoff** [comment]
[Project MAC Progress Report X](https://ban.ai/multics/doc/AD771428.pdf)

- MUDDLE 42 (page 48)

**Comment by larsbrinkhoff** [comment]
https://archive.org/details/bitsavers_dectecoMob_3120242/page/n17

- TECO 709 - 1978-11-02

**Comment by larsbrinkhoff** [comment]
[EMACS; EMACS NEWS](https://github.com/PDP-10/its-vault/blob/master/files/emacs/emacs.news)

- 123 - 1978-06-28
- 124 - 1978-07-03
- 125 - 1978-07-15
- 127 - 1978-11-06
- 129 - 1978-11-19
- 133 - 1979-04-12
- 139 - 1979-11-02
- 140 - 1979-11-10
- 141 - 1979-11-23
- 145 - 1980-04-03
- 150 - 1980-08-10
- 154 - 1981-03-02
- 155 - 1981-03-30
- 161 - 1981-08-06
- 162 - 1981-09-20

**Comment by larsbrinkhoff** [comment]
EMACS; [PURE] * timestamps:

- 24 - 1976-11-27
- 25 - 1976-11-29
- 106 - 1977-11-01
- 108 - 1977-11-14
- 109 - 1977-12-06
- 113 - 1977-12-24
- 114 - 1978-01-11
- 116 - 1978-03-17
- 123 - 1978-06-20
- 124 - 1978-07-03
- 125 - 1978-07-15
- 126 - 1978-08-24
- 128 - 1978-11-08
- 129 - 1978-11-19
- 131 - 1978-12-19
- 132 - 1979-09-22
- 135 - 1979-05-12
- 139 - 1979-11-01
- 141 - 1979-11-23
- 142 - 1979-12-02
- 146 - 1980-04-04
- 147 - 1980-05-19
- 149 - 1980-07-26
- 150 - 1980-08-08
- 152 - 1981-01-15
- 154 - 1981-02-28
- 157 - 1981-04-03
- 158 - 1981-04-08
- 159 - 1981-04-10
- 160 - 1981-04-27
- 162 - 1981-09-20

**Comment by larsbrinkhoff** [comment]
[AI memo 170](http://www.bitsavers.org/pdf/mit/ai/aim/AIM-170.pdf):

ITS 454, "JAN 09 1929" huh?

**Comment by ams** [comment]
ITS — Bits Back From The Future.

**Comment by larsbrinkhoff** [comment]
I'm hoping to get the ML tape 1054 file SYSBIN; ITS CPY dated 1974-05-01.  It may be the only preserved 1974 version of ITS.

**Comment by larsbrinkhoff** [comment]
ITS has a symbol called ASMDAT with this definition: `ASMDAT==.OP <.OPER@> 0,.RDATE`

TODO: Check all old binaries to see when they were assembled.

There are also ITSVRS, MAGVRS, and IMPVRS which have the file versions for ITS, MTAPE, and IMP.

**Comment by eswenson1** [comment]
Where do you see this symbol, ASMDAT?  I don't see it in the current ITS sources, nor as a symbol in the ITS symbol table.

**Comment by larsbrinkhoff** [comment]
I see it in ITS versions 724-864.  But not in 1041, so apparently it was removed.

**Comment by larsbrinkhoff** [comment]
| File | Version | ASMDAT
| --- | --- | ---
| BACKUP; @ ITS | 724 | 720414
| .; @ OOITS | 768 | 721007
| .; @ OOITS | 771 | 721103
| .; @ OITS | 773 | 721127
| .; @ ITS | 776 | 721222
| BACKUP; ITS COPY | 781 | No symbol table
| .; @ OITS | 794 | 730403
| .; @ ITS | 796 | 730430
| (DECtape D95A) @ ITS | 848 | 731111
| SYSBIN; ITS CPY |  864 | 740406

**Comment by larsbrinkhoff** [comment]
I'm working my way backwards from 785 sources.  I have edited them to get exactly matching binaries for 781, 776, 776, and 771 so far.  I'll do 768 and ultimately 724 too.  At some point I'll go the other direction and make sources for 848 and 864, but I'll wait until I have more files from SYSTEM.

There is one problem: CONSTANTS leave one extra zero at the end.  I don't know why.  I have hacked around it by inserting essentially LOC .-1 after.  This happens with all MIDAS versions 135, 324, and 458 so it's consistent.

I don't think it's appropriate to store the files in this repository, so I created this which also makes a chronological git history: https://github.com/larsbrinkhoff/its-history

**Comment by larsbrinkhoff** [comment]
SYS.00.00 "A Novice's Introduction to the Dynamic Modeling System" says:

```
         DM ITS 1021.1Peek 374   05/02/77  13:53:42  Up time = 2:19:15:35
```

**Comment by larsbrinkhoff** [comment]
This https://github.com/PDP-10/its/issues/672#issuecomment-575146036 hints ITS versions 331-346 are from 1968.

**Comment by larsbrinkhoff** [comment]
ToTS tape 3100151.

| File | Version | ASMDAT or timestamp
| --- | --- | ---
| .; @ OOOITS | 715 | 720204
| .; @ OOITS | 717 | 720302
| .; @ OITS | 719 | 720322
| SYSENG; ITS 720 | 720 | 1972-03-30
| SYSENG; ITS 722 | 722 | 1972-04-13
| SYSENG; ITS 723 | 723 | 1972-04-14
| SYSENG; ITS 724 | 724 | 1972-04-15
| .; @ ITS | 724 | 720414

**Comment by larsbrinkhoff** [comment]
@atsampson found 698 in H; MIDAS H76A: `;ITS SYSTEM CALLS AS OF ITS 698,  10:19:45 AM,  SUNDAY, SEP 12,1971   --SSYML.9`

**Comment by larsbrinkhoff** [comment]
ToTS tape 3100150 has no timestamps readable by itstar, but should be from 1971.  Has ITS source or binaries for ITS 671, 672, 673, and 674.

**Comment by larsbrinkhoff** [comment]
@jdersch found the 1969 Computer and Automation article ["The Personality of the Interactive Programmed Computer"](https://raw.githubusercontent.com/larsbrinkhoff/its-archives/master/articles/Personality.pdf).  It has these version numbers:

- LISP 107B
- ITS 549 (from PEEK run 11/01/69)
- PEEK 147

The article states the examples are from the Project MAC PDP-6.

**Comment by larsbrinkhoff** [comment]
@gjs found his hardcopy listings for ITS 138, Maclisp 97, and a Maclisp compiler.  According to the book The Tomorrow Makers, the ITS listing is from 1967 which seems consistent with other information.  AI memo 161 from June 1968 has next earliest recorded version: 350.

There was a Maclisp 107B in December 1969, so maybe 97 could be from 1968-69?

**Comment by larsbrinkhoff** [comment]
ABC What About Tomorrow? - On The Side Of Man" from January 22, 1973.
https://web.archive.org/web/20210228230728/wayback-fakeurl.archive.org/yt/NXQvrVQw1Uw

ITS 773 and DDT 464.

**Pull request merged**
