### PR TITLE
TEACH EMACS

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
EMACS; TSTCH 40 (dumped output)  
EMACS; TEACH EMACS
EMACS; TEACH > (found in Alderson's Twenex EMACS 170)

Uses: DOCOND and TRMTYP.

### CODE REVIEW

**Comment by eswenson1** [comment]
Geez!  I thought you wanted RWK to do it! :-)

**Comment by larsbrinkhoff** [comment]
No, this is TEACH EMACS.  This is written in TECO, not LISP.

**Comment by eswenson1** [comment]
Oh, I didn't know there were two.  Thanks.

**Comment by larsbrinkhoff** [comment]
There are some unknowns here:
- What was the name of the TEACH EMACS program, and where was it stored?  
  I'm assuming the name was TEACHE, and made it a link from SYS2; to EMACS; TSTCH >.
- How was it dumped?  
  I chose to make a link from TEACH; TEACH EMACS, which makes it easy to run EMACS with that init file.

**Comment by larsbrinkhoff** [comment]
Whoops, forgot the README line.

**Comment by larsbrinkhoff** [comment]
Oh, of course it should be TEACH; TS EMACS!

**Pull request merged**
