### PR TITLE
Various EMACS additions.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Add documentation for EMACS modes.  Add Fortran mode.  Add Scribe source for EMACS manual.  Fix some version numbers.

### CODE REVIEW

**Review by eswenson1 — COMMENTED** [review]
Are you really able to build with the new files in emacs and emacs1?  These directories are both full on ES-ITS and I have to keep moving files to archives and other directories when we add more to these....

**Comment by larsbrinkhoff** [comment]
It seems to build ok.  There's only one new EMACS1 file.  Most of the files are INFO documentation.

We noted the overflowing EMACS directories already back in issue 2: https://github.com/PDP-10/its/issues/2#issuecomment-268054975  Maybe it's time to implement that soon.

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Even with all the COMPRS files lying around in EMACS1, I was able to create 39 more files there.

**Comment by larsbrinkhoff** [comment]
Eric, you mentioned archives.  Maybe another option besides splitting off EMACS0 from EMACS would be to add code to search archives in EMACS.

**Comment by eswenson1** [comment]
It is probably because I have a lot more files in EMACS and EMACS1 on ES than we have in DB then.

**Comment by larsbrinkhoff** [comment]
Added autoloads for the programming language modes.

**Pull request merged**
