### PR TITLE
Muddle intro, hello world

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
@36bit and @atsampson, is it possible to make a small hello world application with our current set of Muddle tools?

Can we make a save file, and run it with something like the TOPS-20 bootstrap?  
https://github.com/PDP-10/its-vault/blob/master/twenex/sys/unsupported/mudsub.mid.2

### CODE REVIEW

**Review by atsampson — APPROVED** [review]
Looks fine for now. Real applications would have been compiled before dumping but we don't currently have the compiler...

It'd be nice to have a link to the Primer (and other manuals) from the muddle repo in here, since that's a good introduction to the language...

**Comment by larsbrinkhoff** [comment]
Good idea.  I added links to the four major manuals.  I'm not sure how they all differ from each other, all except "Environment" seem to cover roughly the same subjects.

**Review by eswenson1 — APPROVED** [review]
I'm not really sure this is the right perspective, however.  You don't need to create a SAVE file in order to write and use MDL programs.  You can just load muddle source into the interpreter and run it.  The purpose of the SAVE files is really to save out a largish program (consisting of lots of sources) complete with initialization and startup logic.  It is essentially used to save the state of the interpreter after it has been loaded with a bunch of code.  Normally, SAVE files are created with compiled code, too -- not source code.  Normally, you compile muddle source to NBIN files and load them into an interpreter and dump to a SAVE file.  You can also convert the NBIN files to FBIN files, which are shareable.  Then you load the FBIN files into the interpreter and SAVE the whole thing out.  

But if you want to run a simple program your like your HELLO program, you'd normally just either run it interpretered (call <HELLO> after you've loaded it).  Or you'd compile it to an NBIN and load that into a new interpreter and call it.  

One of the values of creating a SAVE file is that you can then write a shell program that opens the SAVE file, determines the MDL version, invokes the correct MDL runtime, loads the SAVE file in, and resumes it.  So your example would be a lot better if you included that part.

**Comment by larsbrinkhoff** [comment]
Thanks @eswenson1.  You make some good points, but I don't want to overhaul the text now.  I'll merge this in, but we can certainly update it later.  Especially if there's a working compiler.

**Pull request merged**
