### PR TITLE
Updates for "dump diff" script.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
- Some cleanup/refactoring.
- Output an xfile to delete files that were removed between the two tapes.
- Make it posixier.

### CODE REVIEW

**Review by eswenson1 — COMMENTED** [review]
I'm not having much luck on macOS with this version of dump-diff.sh.  I'm getting:

```
/Users/eswenson/ITS/ws/its/build/dump-diff.sh: line 98: !: command not found
/Users/eswenson/ITS/ws/its/build/dump-diff.sh: line 98: !: command not found
/Users/eswenson/ITS/ws/its/build/dump-diff.sh: line 98: !: command not found
/Users/eswenson/ITS/ws/its/build/dump-diff.sh: line 98: !: command not found
/Users/eswenson/ITS/ws/its/build/dump-diff.sh: line 98: !: command not found
head: illegal line count -- -1
?Open failure: No such file or directory
?Open failure: No such file or directory
```

This is after having shown me a bunch of NEW FILEs.

**Comment by atsampson** [comment]
That `\!` on line 98 should just be `!`.

**Comment by eswenson1** [comment]
Yes, I found that, removed the \ and got this:
```
REMOVED FILE: jtw.mail
REMOVED FILE: map.mail
REMOVED FILE: first.999999
REMOVED FILE: sigsub.999999
REMOVED FILE: switch.999999
head: illegal line count -- -1
xargs: unterminated quote
?Open failure: No such file or directory
```
What does a line count of -1 mean?  Should that be 1?  Did someone try to convert -1 to -n 1?

**Comment by eswenson1** [comment]
I changed the head lines to:
```
head -n 1 "$diffs" | xargs itstar cvf "$tap"
tail -n 2 "$diffs" | xargs itstar rvf "$tap"
```

And now the script runs to completion.

**Review by eswenson1 — CHANGES_REQUESTED** [review]
Please remove the \ before the ! in line 98.  Please fix the "head" command to not specify a negative line offset. No need for the +2 in the tail request -- just 2 is sufficient.

**Comment by larsbrinkhoff** [comment]
Thanks for checking on mac.  I fixed `if `!` and `head -n -1`.  Negative on the `tail -n +2`: +2 means something else than just 2.

**Review by eswenson1 — APPROVED** [review]

**Pull request merged**
