### PR TITLE
Add a HOSTS3 entry for the gateway IP.

### PR DESCRIPTION
**Pull request by bictorv**
This is needed to make COMSAT parse the IP address properly (see #2338): the GW address must have a host entry to be parseable by `NETRTS"HANLYZ`.

Without the HOSTS3 entry, parsing e.g. "192.168.0.45" fails. With the generated entry, it succeeds.

I'd say the underlying bug is in `NETRTS` or `RESOLV` (which is called by NETRTS), but that's for another day.

### CODE REVIEW

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by eswenson1** [comment]
This is needed even if you use the @192.168.0.45 syntax? It seemed to work for me without that. I did add host table entries for my gateway, but I thought I did that only for aesthetics and only after I verified that it was working. I could be wrong.  In any case, is is a good idea to add the host table entries and use symbolic names.

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Squashed.

**Comment by bictorv** [comment]
> This is needed even if you use the @192.168.0.45 syntax? It seemed to work for me without that.

Yes. It didn't seem to work for me. Running with DEBUG non-zero shows debug printouts in STATS, and stepping it shows that HANLYZ (in NETRTS) returns failure.

**Comment by larsbrinkhoff** [comment]
Merged.

**Pull request merged**
