### PR TITLE
FILE - Chaosnet file server

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYSBIN; FILE BIN (from syseng)  
DEVICE; CHAOS FILE (purified)  
DEVICE; CHAOS FILEI (from eak)  
DEVICE; CHAOS FILEO link to FILEI  
SYSENG; FILE 591  
EAK; FILE 2  
SYSDOC; CHAOS FILE

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@eak This FILEI/FILEO is also a Chaosnet file server services, right?  What's the difference between them, and FILE?

**Comment by larsbrinkhoff** [comment]
Thanks @ams, using the Chaosnet FILE protocol may be the quickest route to accessing a Unix file system from ITS.

I read @lisper's chaos-cadr README (@joshuaeckroth's copy), and it's my understanding chaosd listens to connections to a unix socket.  @bictorv's KLH10 extension tunnels Chaosnet packets in UDP.

**Comment by bictorv** [comment]
Yes, see my comment on #17 .

**Comment by larsbrinkhoff** [comment]
Right, thanks!

**Comment by larsbrinkhoff** [comment]
@earl-ducaine, this should be the ITS Chaosnet FILE server.

**Pull request merged**
