### PR TITLE
Fix Muddle 56's CLOSE not flushing the output buffer

### LINKED ISSUE #1957: Muddle 56 doesn't flush buffer on <CLOSE>
@ZoBoRf found that Muddle 56's `<CLOSE>` doesn't flush its output buffer when closing a file - there's a detailed description and a test program in [ZILCH-How-to](https://github.com/ZoBoRf/ZILCH-How-to).

I had a look at this, and it's because some of the IO code was updated for TOPS-20 but not for ITS. In particular, the `ODSK` and `OTTY` functions should set the `C.DISK`/`C.TTY` flags in `-2(B)` - the `CLOSE` code checks for those flags in the channel being closed and assumes it's a network channel if neither is set.

I've tried changing `ODSK`/`OTTY` to IOR in the appropriate flags after calling `OPEN0`/`OPEN2`. This gets into the right bit of code in `BFCLOS` but the `.CALL SIOT` it uses doesn't work - this either needs fixing, or replacing with a call to the usual code for writing bytes to a file (which is how Muddle 54 does it).

### PR DESCRIPTION
**Pull request by atsampson**
This is the output flushing problem @ZoBoRf found. To summarise, it's because some of the code in FOPEN that was new in Muddle 56 hadn't been tested on ITS. I've tested it with output lengths from 5 to 10 (i.e. all the possible amounts of leftover chars) and it seems OK now.

It looks like quite a lot of the code in FOPEN was modified to make better use of flags in Muddle 56 - they've tried to update the ITS code as well but I wouldn't be surprised if there are other problems like this.

Fixes #1957.

### CODE REVIEW

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
@ZoBoRf, could you please check that this solves your problem?

**Comment by larsbrinkhoff** [comment]
I think we can merge this?

**Comment by larsbrinkhoff** [comment]
@atsampson, I have tried to contact @ZoBoRf but I have not heard back from him.

**Comment by ZoBoRf** [comment]
I hope to find the time to check it around the turn of the year.

**Comment by larsbrinkhoff** [comment]
Great. thanks!  Glad to see you are still around.

**Comment by ZoBoRf** [comment]
I could remove my buffer flushing workarounds in this muddle version to compile zork2. The resulting zap files are unchanged compared to the previous muddle 56. It looks good!

**Review by ZoBoRf — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Thanks, merged!

**Comment by larsbrinkhoff** [comment]
According to @Rick-Shiffman, there may still be a problem with CLOSE:

> I think that I've found an error in muddle 56's closing of user defined disk channels.  Below is an example of the problem. I was trying to define a function to PPRINT to a disk file, you could easily save bits and pieces of code you were working on. Screen
Copying the code segment and coping it to TECO is kind of a kluge.

```
;"MUDDLE 56 error??"

<SET FOUT <OPEN "PRINT" "DSK:RRS;FOOBAR >">>$
#CHANNEL [3 "PRINT" "FOOBAR" ">" "DSK" "RRS" "FOOBAR" "3" "DSK" "RRS" 227
23748404134 80 0 0 0 0 10
""
]
"THIS IS A TEST OF FILE OUTPUT"OUTPUT" .FOUT>$

<PRINC "THIS IS A TEST OF FILE OUTPUT" .FOUT>$
"THIS IS A TEST OF FILE OUTPUT"

.FOUT$
#CHANNEL [3 "PRINT" "FOOBAR" ">" "DSK" "RRS" "FOOBAR" "3" "DSK" "RRS" 227
23748404134 80 61 0 0 63 10
""
]
<CLOSE .FOUT>$
#CHANNEL [0 "PRINT" "FOOBAR" ">" "DSK" "RRS"
MPV; 727106>>ILDB 1,(13)   1/   -50737   7520/   TSCA 17,424163(17)


$g restarts muddle at
MUDDLE 56 IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1

Everything you FLOADed or DEFINEd is still memory.

$p repeats the same crash
MPV; 727106>>ILDB 1,(13)   1/   -50737   7520/   TSCA 17,424163(17)

2   FOOBAR 3      0 ! 2/27/2021 05:08:10
Is empty

**Comment by larsbrinkhoff** [comment]
Or maybe I haven't rebuilt my copy of Muddle!

**Comment by ZoBoRf** [comment]
I get:
```
*^F
DB   ROB   
FREE BLOCKS #0=11612 
  0   FILTST MUD    1 ! 12/13/2020 15:51:02
  0   FOO    BAR    1 ! 12/13/2020 15:51:08
  0   ROB    LOGIN  1   12/13/2020 07:52:04
*:muddle
MUDDLE 56 IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1
<SET FOUT <OPEN "PRINT" "DSK:ROB;FOOBAR >">>$
#CHANNEL [4 "PRINT" "FOOBAR" ">" "DSK" "ROB" "FOOBAR" "1" "DSK" "ROB" 227 
23748404138 80 0 0 0 0 10 
""
]
<PRINC "THIS IS A TEST OF FILE OUTPUT" .FOUT>$
"THIS IS A TEST OF FILE OUTPUT"
.FOUT$
#CHANNEL [4 "PRINT" "FOOBAR" ">" "DSK" "ROB" "FOOBAR" "1" "DSK" "ROB" 227 
23748404138 80 29 0 0 29 10 
""
]
<CLOSE .FOUT>$
#CHANNEL [0 "PRINT" "FOOBAR" ">" "DSK" "ROB" "FOOBAR" "1" "DSK" "ROB" 227 
23085704398 80 29 0 0 29 10 ""]
<QUIT>$

:KILL 
*:print foobar >

THIS IS A TEST OF FILE OUTPUT
*^F
DB   ROB   
FREE BLOCKS #0=11611 
  0   FILTST MUD    1 ! 12/13/2020 15:51:02
  0   FOO    BAR    1 ! 12/13/2020 15:51:08
  0   FOOBAR 1      1 ! 3/1/2021 10:02:04
  0   ROB    LOGIN  1   12/13/2020 07:52:04
```

**Pull request merged**
