### PR TITLE
TWDEMO - scripted demonstration of SHRDLU.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This is a program that just replays the dialogue in SHRDLU; DEMO FLICK.

CC @SMJ

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Not that I have found yet.  Searching for DEMO or FLICK in the SHRDLU files doesn't reveal anything useful.

**Comment by eswenson1** [comment]
I assume all it is doing is firing up lisp, opening the demo file, and feeding lisp all the commands in the file (sort of like xxfile), right?

**Comment by larsbrinkhoff** [comment]
Something like that, but not a bare Lisp.  It probably has some SHRDLU files loaded.  Note e.g. `(GRASP (QUOTE :B1))` to have the robot pick up a block.  GRASP is defined in TWUTIL.

**Comment by larsbrinkhoff** [comment]
And text between @ characters is the dialogue.

**Comment by larsbrinkhoff** [comment]
Hmm, the GRASP in TWUTIL isn't very useful!

**Comment by larsbrinkhoff** [comment]
Ah, GRASP is in RBRN; GRAPH 26.

**Pull request merged**
