### PR TITLE
Add LMODEM, Maclisp XMODEM implementation.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
As decscribed in #969.  The source file SIGNAL needed a fix as per the updated LOOP macro.

Most files courtesy of Eric Swenson, who had them in an archive file.  The HELP file is from PI.

I contacted Ed Barton and he gave his permission.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
The matter of how to actually use LMODEM is still unresolved.  It wants to reconfigure the incoming serial or TIP line, but it doesn't recognize the input.

**Comment by larsbrinkhoff** [comment]
Another unresolved problem here is how to access the HELP file which is supposed to be `mc:cpm;help lmodem`.  Probably we should just remove the reference to the MC: device.

**Comment by eswenson1** [comment]
Yes, I agree. I removed a few references to MC to get Macsyma to build and run.

**Comment by larsbrinkhoff** [comment]
I have this to load and dump LMODEM:

```
respond "*" {(load "eb;lmodem")}
expect -re {[\r\n][0-7][17]}
type "(dump-lmodem-program)"
```

But it seems `expect -re` doesn't match.  I can't see what I'm doing wrong.

```
;Loading DSK8 33
;CAUTION!  QUIT, A SYSTEM LSUBR AT 17721, IS BEING REDEFINED
;    AS A LSUBR BY FASL FILE ((DSK EB) LMODEM FASL)

;(OPEN ((DSK DB) DB LMDLOG) (DSK OUT SINGLE)) NON-EXISTENT DIRECTORY

Can't open log file.
Connected to LISP through the following path:
      NIL.
Unable to understand how to communicate over this path.
Cannot initalize properly for transfers.

152253 

The last command timed out.
```

**Comment by larsbrinkhoff** [comment]
Oh no, I see it now.

**Comment by eswenson1** [comment]
In my case, the output from the (load …) is:

“T”

 

Which doesn’t match your expect expression.

 

When I manually call:

 

(dump-lmodem-program)

 

I get prompted for a filename (ejs;ts lmodem)

 

And it dumps it.  I can then run :ejs;lmodem and get:

 

*:ejs;lmodem

 

(TTYTYP 200000)

(JOB-SPEC 15)

(JOB-SPEC 400015)

(UNAME6 12TLNT)

(JNAME6 TELSER)

(XJNAME6 TELSER)

(*CONNECTION-PATH ((TELSER LOCATION-DESCRIPTION || HOST-NUMBER 6235000616 TIP-P!

ORT-NUMBER NIL TELSER-TYPE TELSER HOST-TYPE ARPANET TTY-HAS-%TPTEL T TTY-HAS-%T!

PMTA NIL TTY-HAS-%TOFCI NIL HAS-BINARY-NEGOTIATION-VARIABLES NIL JOB-SPEC 40001!

5)))

(*CONNECTION-PATH-TYPE (TELSER))

Opened log file #FILE-OUT-|DSK:EJS;EJS LMDLOG|-72752.

Setting up for 8-bit protocol.

You are not coming from a TIP.  Your TELNET will be asked to enter

binary mode, but LMODEM cannot insure binary mode over your entire

connection path.

 

T

 

From: Lars Brinkhoff ***@***.***>
Reply-To: PDP-10/its ***@***.***>
Date: Tuesday, November 9, 2021 at 9:14 AM
To: PDP-10/its ***@***.***>
Cc: Eric Swenson ***@***.***>, Review requested ***@***.***>
Subject: Re: [PDP-10/its] Add LMODEM, Maclisp XMODEM implementation. (PR #2090)

 

I have this to load and dump LMODEM:
respond "*" {(load "eb;lmodem")}
expect -re {[\r\n][0-7][17]}
type "(dump-lmodem-program)"
But it seems expect -re doesn't match. I can't see what I'm doing wrong.
;Loading DSK8 33
;CAUTION!  QUIT, A SYSTEM LSUBR AT 17721, IS BEING REDEFINED
;    AS A LSUBR BY FASL FILE ((DSK EB) LMODEM FASL)
 
;(OPEN ((DSK DB) DB LMDLOG) (DSK OUT SINGLE)) NON-EXISTENT DIRECTORY
 
Can't open log file.
Connected to LISP through the following path:
      NIL.
Unable to understand how to communicate over this path.
Cannot initalize properly for transfers.
 
152253 
 
The last command timed out.

**Comment by eswenson1** [comment]
But in your case, I see it is returning a memory offset. Not sure why that doesn’t match.  What does the [17] do?  Is that a length?  If so, is that the issue, since 152253 is shorter?  (I don’t know expect matching).

 

From: Lars Brinkhoff ***@***.***>
Reply-To: PDP-10/its ***@***.***>
Date: Tuesday, November 9, 2021 at 9:14 AM
To: PDP-10/its ***@***.***>
Cc: Eric Swenson ***@***.***>, Review requested ***@***.***>
Subject: Re: [PDP-10/its] Add LMODEM, Maclisp XMODEM implementation. (PR #2090)

 

I have this to load and dump LMODEM:
respond "*" {(load "eb;lmodem")}
expect -re {[\r\n][0-7][17]}
type "(dump-lmodem-program)"
But it seems expect -re doesn't match. I can't see what I'm doing wrong.
;Loading DSK8 33
;CAUTION!  QUIT, A SYSTEM LSUBR AT 17721, IS BEING REDEFINED
;    AS A LSUBR BY FASL FILE ((DSK EB) LMODEM FASL)
 
;(OPEN ((DSK DB) DB LMDLOG) (DSK OUT SINGLE)) NON-EXISTENT DIRECTORY
 
Can't open log file.
Connected to LISP through the following path:
      NIL.
Unable to understand how to communicate over this path.
Cannot initalize properly for transfers.
 
152253 
 
The last command timed out.

**Comment by larsbrinkhoff** [comment]
`T` should be from a source file, whereas a number is when a FASL is loaded.

**Comment by eswenson1** [comment]
Yes.  I was being stupid.  The “T” was not from the (load…) in my case, but from running (run t), which returns T.

 

I get the same behavior as you.  I get:

 

(load 'lmodem)

;Loading LMODEM 256

; Loading FORMAT ([ML]DSK:FORMAT;FORMAT 827)

;Loading YESNOP 44

;Loading QUERIO 51

;Loading DEFMAX 98

;Loading MACAID 120

;Loading DSK8 33

;CAUTION!  QUIT, A SYSTEM LSUBR AT 17721, IS BEING REDEFINED

;    AS A LSUBR BY FASL FILE ((DSK EJS) LMODEM FASL)

 

(TTYTYP 200000)

(JOB-SPEC 15)

(JOB-SPEC 400015)

(UNAME6 12TLNT)

(JNAME6 TELSER)

(XJNAME6 TELSER)

(*CONNECTION-PATH ((TELSER LOCATION-DESCRIPTION || HOST-NUMBER 6235000616 TIP-P!

ORT-NUMBER NIL TELSER-TYPE TELSER HOST-TYPE ARPANET TTY-HAS-%TPTEL T TTY-HAS-%T!

PMTA NIL TTY-HAS-%TOFCI NIL HAS-BINARY-NEGOTIATION-VARIABLES NIL JOB-SPEC 40001!

5)))

(*CONNECTION-PATH-TYPE (TELSER))

Opened log file #FILE-OUT-|DSK:EJS;EJS LMDLOG|-72770.

Setting up for 8-bit protocol.

You are not coming from a TIP.  Your TELNET will be asked to enter

binary mode, but LMODEM cannot insure binary mode over your entire

connection path.

 

152322

(dump-lmodem-program)

Closed log file #FILE-OUT-|DSK:EJS;EJS LMDLOG|-72770.

Filename in which to dump: ejs;ts lmodem

(TTYTYP 200000)

(JOB-SPEC 15)

(JOB-SPEC 400015)

(UNAME6 12TLNT)

(JNAME6 TELSER)

(XJNAME6 TELSER)

(*CONNECTION-PATH ((TELSER LOCATION-DESCRIPTION || HOST-NUMBER 6235000616 TIP-P!

ORT-NUMBER NIL TELSER-TYPE TELSER HOST-TYPE ARPANET TTY-HAS-%TPTEL T TTY-HAS-%T!

PMTA NIL TTY-HAS-%TOFCI NIL HAS-BINARY-NEGOTIATION-VARIABLES NIL JOB-SPEC 40001!

5)))

(*CONNECTION-PATH-TYPE (TELSER))

Opened log file #FILE-OUT-|DSK:EJS;EJS LMDLOG|-72752.

Setting up for 8-bit protocol.

You are not coming from a TIP.  Your TELNET will be asked to enter

binary mode, but LMODEM cannot insure binary mode over your entire

connection path.

 

T

 

And if I check, I now have a ejs;ts lmodem:

 

50107)   XCT 11   :find ejs;ts lmodem

DB:EJS;

  1   TS     LMODEM  44   +8  ! 11/9/2021 17:23:45 (11/9/2021)

 

:KILL  L$J

*:ejs;lmodem

 

(TTYTYP 200000)

(JOB-SPEC 15)

(JOB-SPEC 400015)

(UNAME6 12TLNT)

(JNAME6 TELSER)

(XJNAME6 TELSER)

(*CONNECTION-PATH ((TELSER LOCATION-DESCRIPTION || HOST-NUMBER 6235000616 TIP-P!

ORT-NUMBER NIL TELSER-TYPE TELSER HOST-TYPE ARPANET TTY-HAS-%TPTEL T TTY-HAS-%T!

PMTA NIL TTY-HAS-%TOFCI NIL HAS-BINARY-NEGOTIATION-VARIABLES NIL JOB-SPEC 40001!

5)))

(*CONNECTION-PATH-TYPE (TELSER))

Opened log file #FILE-OUT-|DSK:EJS;EJS LMDLOG|-72752.

Setting up for 8-bit protocol.

You are not coming from a TIP.  Your TELNET will be asked to enter

binary mode, but LMODEM cannot insure binary mode over your entire

connection path.

 

T

 

From: Lars Brinkhoff ***@***.***>
Reply-To: PDP-10/its ***@***.***>
Date: Tuesday, November 9, 2021 at 9:26 AM
To: PDP-10/its ***@***.***>
Cc: Eric Swenson ***@***.***>, Review requested ***@***.***>
Subject: Re: [PDP-10/its] Add LMODEM, Maclisp XMODEM implementation. (PR #2090)

 

T should be from a source file, whereas a number is when a FASL is loaded.

**Comment by larsbrinkhoff** [comment]
I meant to use the regexp `[\r\n][1-7][0-7]` to match a newline and two octal digits (the first one can't be 0).

**Comment by eswenson1** [comment]
That makes much more sense!

**Review by eswenson1 — APPROVED** [review]

**Comment by eswenson1** [comment]
I thought I had commented on your issue with accessing the help file, but I don't see it here. I said that I had removed a lot of "MC:" from filenames to get Macyma to compile/work -- I think it is fine to remove the MC: for LMODEM help file access too.

**Comment by larsbrinkhoff** [comment]
Thanks.  Your comment is in Adam's original issue.

**Comment by larsbrinkhoff** [comment]
A tricky detail I got wrong on the first (and second, and third...) try is that the lines output by LISP don't always have plain CR LF endings.  For example, when `dump-lmodem-program` has finished it returns `T` which is output as "CR LF LF T space".  So the expect match has to accommodate that.

**Pull request merged**
