### PR TITLE
FAIL - Stanford assembler

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SAIL; FAIL BIN  

Probably no source code.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
The original FAIL BIN identifies itself as version 143 and has a timestamp from 1979.  The source file was last edited in 1985.  I arbitrarily named it FAIL 200 to bump the version.

**Comment by eswenson1** [comment]
Are you saying you got it to work now?  If so, I approve.

**Comment by larsbrinkhoff** [comment]
Yes, there was one mistake in my new STKTRN 39, a missing comma.  Fixing that made the new FAIL work.

**Comment by larsbrinkhoff** [comment]
Original source code was in:  
SAIL; FAIL 143

**Comment by larsbrinkhoff** [comment]
And SAIL; STKTRN 39

**Pull request merged**
