### PR TITLE
Add test for one-proceed.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
The test program creates an inferior job and automatically one-proceeds it.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I expect this may fail on KL10 for now.

**Comment by larsbrinkhoff** [comment]
Thanks!  It was fun to code.

**Comment by eswenson1** [comment]
Yes. It's a great example of a superior/inferior, loading code, and managing it.

**Comment by larsbrinkhoff** [comment]
@eswenson1 and @rcornwell, the latest update on the kl10 branch passes this test.  Anything else you want to add to the list of tested instructions?  (Below the START label.)

This this fails now, I'd like to wait until the KL10 simulator can do a full build again.  And then update the subrepo in this pull request.

**Comment by eswenson1** [comment]
What about IBP and IDBP? Do they work now?

I also noticed that when single-stepping in SIMH, you have to do a "step 2" or "step 3" for some MUUOS. Is that "right"? I know this is a separate issue from ^N in TS DDT, but I wonder if there are other related/similar cases that could make ^N not work in TS DDT?

**Comment by larsbrinkhoff** [comment]
I added those two instructions.

**Comment by larsbrinkhoff** [comment]
I'm not sure about SIMH stepping.  I think it doesn't work perfectly in the PDP-11 simulator either.  Since I much prefer to use the on-target debuggers when possible, I haven't made any effort to look into it.

**Comment by rcornwell** [comment]
You should not need to do step 2 over a ILDB/IDPB instruction. The problem is SimH wants to step via sim_interval rather then instructions, so there is some logic to count instructions. However a few instructions are executed as a pair of instructions rather then one instruction, byte instructions, some DMOVEx happen this way.

**Comment by larsbrinkhoff** [comment]
Hello @eswenson1,

When @rcornwell's latest commit on his kl10 works, I intend to update the sims submodule in this pull request.

**Comment by larsbrinkhoff** [comment]
@rcornwell says ITS is working again, so I'll try to update this pull request later today.

**Comment by eswenson1** [comment]
I tried with the latest rcornwell/kl10 branch and still get:

```
INFO Dumped

:KILL
*:tctyp la36:KILL
*

The last command timed out.
Makefile:100: recipe for target 'out/pdp10-kl/rp04.1' failed
make: *** [out/pdp10-kl/rp04.1] Error 1
eswenson@localhost:~/kl-its/ws/its$
```

**Comment by larsbrinkhoff** [comment]
Thanks for checking.  When I tested a few minutes ago, it passed the sticking point.  So I started another run.  But from your input it seems it still isn't stable.

**Comment by larsbrinkhoff** [comment]
I'm thinking I'll enabled (or add) some debugging for front end I/O.  So we can see if ITS actually does write the CR or not.

**Comment by larsbrinkhoff** [comment]
Output from `set cty debug`.  The first line is the `6` from `:tctyp la36`.  `CTY char 15` is the CR character.  The `queue` lines at the end are `:KILL<cr lf>*`.

```
DBG(57884911618)> CTY DETAIL: CTY outch 66 '6'
DBG(57884911618)> CTY DETAIL: CTY ITS DTEODN = 777777777777 1
DBG(57884911618)> CTY DETAIL: CTY ITS DTEODN = 000000000100
DBG(57884911912)> CTY CONI: CTY 202 CONI 001017
DBG(57884911925)> same as above (3 times)
DBG(57884911928)> CTY CONO: CTY 203 CONO 001040 071217
DBG(57886262023)> CTY DETAIL: CTY ITS DTEODN = 777777777777 0
DBG(57887613114)> same as above (1 time)
DBG(57887613114)> CTY DETAIL: CTY char 15 '.'
DBG(57888964204)> CTY DETAIL: CTY ITS DTEODN = 777777777777 0
DBG(57888964204)> CTY DETAIL: CTY ITS DTETYI = 000000000015
DBG(57888964264)> CTY CONI: CTY 202 CONI 001017
DBG(57888964277)> same as above (3 times)
DBG(57888964280)> CTY CONO: CTY 203 CONO 001040 071217
DBG(57888964291)> CTY CONO: CTY Ring 11 DB
DBG(57888964291)> CTY CONO: CTY 203 CONO 020000 071223
DBG(57888964493)> CTY DETAIL: CTY ITS DTEODN = 777777777777 0
DBG(57888964729)> CTY CONI: CTY 202 CONI 000017
DBG(57888964736)> same as above (2 times)
DBG(57888964739)> CTY CONO: CTY 203 CONO 001040 071217
DBG(57889808384)> CTY CONO: CTY Ring 11 DB
DBG(57889808384)> CTY CONO: CTY 203 CONO 020000 076433
DBG(57889808588)> CTY DETAIL: CTY ITS DTEODN = 777777777777 0
DBG(57889808588)> CTY DETAIL: CTY ITS DTEOST = 000000000000
DBG(57890317778)> CTY DETAIL: CTY ITS DTEODN = 777777777777 1
DBG(57890317778)> CTY DETAIL: CTY ITS DTEODN = 000000000100
DBG(57890317837)> CTY CONI: CTY 202 CONI 001017
DBG(57890317850)> same as above (3 times)
DBG(57890317853)> CTY CONO: CTY 203 CONO 001040 071217
DBG(57891190957)> CTY CONO: CTY Ring 11 DB
DBG(57891190957)> CTY CONO: CTY 203 CONO 020000 076433
DBG(57891191159)> CTY DETAIL: CTY ITS DTEODN = 777777777777 0
DBG(57891191159)> CTY DETAIL: CTY ITS DTEOST = 000000000000
DBG(57891668871)> CTY DETAIL: CTY ITS DTEODN = 777777777777 1
DBG(57891668871)> CTY DETAIL: CTY ITS DTEODN = 000000000100
DBG(57891668931)> CTY CONI: CTY 202 CONI 001017
DBG(57891668944)> same as above (3 times)
DBG(57891668947)> CTY CONO: CTY 203 CONO 001040 071217
DBG(57891670076)> CTY CONO: CTY Ring 11 DB
DBG(57891670076)> CTY CONO: CTY 203 CONO 020000 073370
DBG(57891670278)> CTY DETAIL: CTY ITS DTEOUT = 001000000010
DBG(57891670278)> CTY DETAIL: CTY queue 3a
DBG(57891670278)> CTY DETAIL: CTY queue 4b
DBG(57891670278)> CTY DETAIL: CTY queue 49
DBG(57891670278)> CTY DETAIL: CTY queue 4c
DBG(57891670278)> same as above (1 time)
DBG(57891670278)> CTY DETAIL: CTY queue d
DBG(57891670278)> CTY DETAIL: CTY queue a
DBG(57891670278)> CTY DETAIL: CTY queue 2a

**Comment by rcornwell** [comment]
You can see here the sending of the 6 followed by a <cr>. ITS then outputs a ":KILL<cr><lf>*", it seems to not put out the <cr><lf> before printing this. Somehow this data appears to be being eaten.

**Comment by larsbrinkhoff** [comment]
@rcornwell wrote "\<cr>." which GitHub rendered as " ."

**Comment by eswenson1** [comment]
Ah, thanks.

-- Eric

**Comment by larsbrinkhoff** [comment]
Progress on this is slow.  I confirmed that the ITS interupt routine gets to the last line here, and that A is 15.

```
;HANDLE INTERRUPTS FROM THE CONSOLE PDP11 VIA THE DTE20
;CODE FOR HANDLING MULTIPLE CONSOLES, BLOCK TTY OUTPUT, ETC.
;IN THE FUTURE ETHERNET STUFF WILL GET ADDED HERE.

TTDTE1: CONI DTE,DTECNI         ;SAVE FOR DEBUGGING
        CONSZ DTE,460           ;TO11 ERROR OR TO10 DONE OR TO10 ERROR
         BUG PAUSE,[DTE20 ERROR, CONI=],OCT,DTECNI
        CONSZ DTE,100           ;TO11 TRANSFER COMPLETE
         JRST [ CONO DTE,100    ;CLEAR TO11 TRANSFER COMPLETE
                SETZM DTEBBY    ;BUFFER NO LONGER BUSY
                JRST .+1 ]
        CONO DTE,%DBL10+40      ;CLEAR DTE20 INTERRUPTING STATE
        SKIPGE A,DTETYI         ;CHECK FOR TTY INPUT AVAILABLE
         JRST TTDTE2
        SETOM DTETYI            ;AVAILABLE.  INDICATE HAS BEEN GOTTEN.
```

**Comment by larsbrinkhoff** [comment]
Adding some more to my debug code.  These are the last lines.  TTDTE1+10 is input, a CR character.  TTDTE2+25 is output.  Characters are to be transferred from the TOOP to A; they are both byte pointers.  Now to check the number of characters, and the characters themselves.

```
TTDTE1+10  A/ 15
TTDTE2+25  A/ 441000112674  B/ 777777  I/ 0  TOOP/ 341000101217
TTDTE2+25  A/ 441000112674  B/ 777777  I/ 0  TOOP/ 241000101217
TTDTE2+25  A/ 441000112674  B/ 777777  I/ 0  TOOP/ 341000101222

**Comment by larsbrinkhoff** [comment]
Here's some more.  Here we see various labels and memory contents.  The `N/X` output are characters in ITS' output buffer.  These are codes according to SYSDOC; ITSTTY >, section "ITS OUTPUT BUFFER CODES."

1. At TTDTE1+10, we see a CR in A.
2. At TYP0F, right before output, TORM (typeout room) is 403.  The output buffer holds 404 characters, so there's one character in the buffer.
4. The character in the buffer is 207.  This is the %TDCRL code: "Move cursor to beginning of next line".
5. At the next TYP0F, we have ":KILL", some codes, and "*".  Code 200 is "move cursor" followed by four argument bytes.
6. More stuff follows.

The interesting thing is that we see a CR input, and a %TDCRL output.  Next I'll check how this %TDCRL is processed.

```
TTDTE1+10  A/ 15
TTDTE2+25  A/ 441000112674  TOOP/ 341000101217
TYP0F  TORM/ 403  TOOP/ 341000101217  TOBEP/ 41000101254
 207/\207
TTDTE2+25  A/ 441000112674  TOOP/ 241000101217
TYP0F  TORM/ 371  TOOP/ 241000101217  TOBEP/ 41000101254
 72/: 113/K 111/I 114/L 114/L 200/\200 4/^D 5/^E 5/^E 0/^@ 52/*
TYP0F  TORM/ 400  TOOP/ 341000101221  TOBEP/ 41000101254
 201/\201 5/^E 0/^@ 52/*
TYP0F  TORM/ 403  TOOP/ 41000101221  TOBEP/ 41000101254
 52/*
TYP1B+2  TORM/ 274040112666
TTDTE2+25  A/ 441000112674  TOOP/ 341000101222
TYP0F  TORM/ 404  TOOP/ 341000101222  TOBEP/ 41000101254

**Comment by larsbrinkhoff** [comment]
I haven't verified this yet, but it may be due to the ":tctyp la36\r" output string racing against the setting of the terminal type.  If so, we really do have to accept the "la36:KILL" output.

**Comment by larsbrinkhoff** [comment]
I think it goes like this:

1. The console is set to LA36 at the start, as per TTYTYP.  This is a printing terminal.
2. From what I see, the %TDCRL code is not used with a printing terminal.
3. To build INTO, we set terminal type to AAA.
4. Now %TDCRL is in use.
5. The string `:tctyp la36` is sent.
6. Then a CR.
7. CR inserts a %TDCRL in the output buffer.
8. There will be a short delay before the %TDCRL is processed.
9. **IF** TCTYP gets to run quickly and change the terminal type, %TDCRL will be processed with a printing terminal.
10. The effect is to print nothing.

**Comment by larsbrinkhoff** [comment]
I updated this pull request to the very latest commit on the kl10 branch.  Now the one-proceed test is broken again.  I'll try to find which commit did this.

**Comment by rcornwell** [comment]
Can we add this test early in the build to either abort the build or report an error at end of build?

**Comment by larsbrinkhoff** [comment]
I'm trying to have some kind of grouping of related programs, but sure
for now it can be run early.

**Comment by rcornwell** [comment]
:tctyp la36 is a timing issue. If there is another build running while building ITS, the build works fine. If it is run on an idle machine it drops the characters. Lars indicated that ITS is doing a switch to LA36, perhaps before it can fully flush it's CTY buffer. When it does the switch it flushes the buffer. When under load there is enough time to get the buffer empty before ITS flushes it. Perhaps ITS should drain the buffer before flushing it.

**Comment by larsbrinkhoff** [comment]
1. It seems one-proceed works now.
2. Tctyp la36 is probably a race condition in ITS as I described above.  I adjusted the build script.
3. I have currently added a lot of commits to track down problems.  I will rewrite the branch later.

**Comment by eswenson1** [comment]
I just built the lars/1proc branch with no issues (:tctype la36 worked and 1proc test worked).

**Comment by larsbrinkhoff** [comment]
Looks like builds went through.  (Except CirleCI which doesn't do well with submodule updates.)  So I'll look at getting this merged today.

**Comment by larsbrinkhoff** [comment]
I have cleaned up the branch now.  Hopefully this will still build fine like.

**Comment by larsbrinkhoff** [comment]
The KL10 build hung in the usual place (around EMACS) unusually many times.  That's troubling.

**Pull request merged**
