### PR TITLE
FCDEV - Talk to LispM file server

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYSEN2; FCDEV 74  
DEVICE; JOBDEV FC

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
It would be cool if a LispM hacker could test this.  @ams?

**Comment by larsbrinkhoff** [comment]
The Lispm file server address is hardcoded to 3060, CADR-27.  .SEE LMHADR

**Comment by larsbrinkhoff** [comment]
@ams, @bictorv This is FC: on ITS, and if I understand correctly uses the LMFILE Chaosnet contact name.  Do you have a server for this?

**Comment by ams** [comment]
LMFILE is a local file system used by the FC (and other LispMs).  LMFILE-Remote is a remote protcol to talk to said machines through contact name LMFILE.  FC from what I understand was the shared file system by the Lisp Machines at the AI lab.

**Pull request merged**
