### PR TITLE
Add choices program and routines library for LLogo

### PR DESCRIPTION
**Pull request by Alexey-Slyusar**
Minor fixes in doc/logo.md;
src/bh created;
added choices program and routines library for LLOGO #1538

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
It would be great to make this two commits.  The first for the markdown file, and the second with the BH files.

**Comment by Alexey-Slyusar** [comment]
Thank you, Lars!
I'll make the two commits tomorrow. Am I right that this one should be
deleted? Could you please suggest how to delete if so.

вс, 3 марта 2019 г. в 21:53, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
There are many ways to do it.  It wouldn't have to be deleted, just changed with parts split off into another commit.  

See e.g. https://github.com/larsbrinkhoff/fearless-git#split-commits, and if that's not helpful, let me know.

**Comment by Alexey-Slyusar** [comment]
I did:
`git rebase -i LW1/alexey~2`
and then,
```
pick b7f50fb Updated to build INQUIR;NETRTN FASL from source. Resolves #1553.   
edit deb5720 Minor fixes in doc/logo.md. Adding choices program and library for\
 llogo. 
```
and then, I changed commit's commentary to `Add choices program and library for llogo` and `git rm doc/logo.md`.
Git replies that I have two separated branch now: origin and another one. I have localised git, so it is meaningless to put exact message here.
But I have strong feeling that I did not make things right. So I did not type `git push -f`. 
I'll try to do things more carefully this evening.

**Comment by larsbrinkhoff** [comment]
That sounds reasonable.  After rewriting the local branch, it's no longer the same as the remote branch.

When done, `git log -3` should list your two new commits and b7f50fb.

**Comment by larsbrinkhoff** [comment]
You can also type `git diff HEAD origin/LW1/alexey` to check that there is no differences between your local branch and the remote one.

**Comment by Alexey-Slyusar** [comment]
Thank you Lars for finding time to look at this and comment. I'll try
things this evening.

пн, 4 марта 2019 г. в 13:43, Lars Brinkhoff <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
Sorry, not this evening / night.
Too busy at work currently.

пн, 4 марта 2019 г. в 14:29, Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by larsbrinkhoff** [comment]
Sure, take your time!

**Comment by Alexey-Slyusar** [comment]
Here is `git log -3` output:
```
alexey@its:~/git/ttt/its$ git log -3
commit db34f25c041d261d125076a49b426ca25bf13892 (HEAD -> LW1/alexey)
Author: Alexey-Slyusar <aleksey.slyusar@gmail.com>
Date:   Mon Mar 4 08:15:03 2019 +0300

    Add choices program and routines library for LLogo.

commit be20f391d8fec0993d0663a083c6c2c812e392c8
Author: Alexey-Slyusar <aleksey.slyusar@gmail.com>
Date:   Sun Mar 3 20:18:25 2019 +0300

    Add choices program and routines library for LLOGO.

commit b7f50fb3ed209169cd40f74fb518e0f7acafe7a0 (origin/master, origin/HEAD)
Author: Eric Swenson <eric@swenson.org>
Date:   Sun Feb 24 13:24:58 2019 -0800

    Updated to build INQUIR;NETRTN FASL from source.
    Resolves #1553.
```
So, yes it listed my two new commits and b7f50fb, as Lars wrote.

**Comment by Alexey-Slyusar** [comment]
Did `git push -f`

**Comment by Alexey-Slyusar** [comment]
It seems that I should correct the title to remove mention for logoguide from it.

**Comment by Alexey-Slyusar** [comment]
Lars, I reread https://github.com/larsbrinkhoff/fearless-git#why-rewrite-pull-requests.
And I think I consciously understand why you asked me to split commits. Thank you.

**Comment by Alexey-Slyusar** [comment]
But it is still unclear form me what should I do with second commit commit `be20f391d8fec0993d0663a083c6c2c812e392c8`. 
It contains `logo.md` file with minor corrections.

**Comment by Alexey-Slyusar** [comment]
Lars, thank you very much!

сб, 9 марта 2019 г. в 16:38, Lars Brinkhoff <notifications@github.com>:

**Pull request merged**
