### PR TITLE
URUG - GT40 Microrug

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYSEN2; URUG 27  

PDP-11 debugger for GT40, written in PALX assembly language.

Part of the rug/carpet family of debuggers.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm transcribing the manual.

Later, I'm going to test this with SIMH.

**Comment by larsbrinkhoff** [comment]
Please proofread the manual.  I'm sure I made typos.

**Comment by eswenson1** [comment]
All the typos I found are already corrected in @atsampson 's branch.

**Comment by larsbrinkhoff** [comment]
Thanks for checking! I typed furiously and tried to look for mistakes, but it's hard to see your own typos.

I added a commit with line breaks where the text seem to require them. I'm guessing they got lost in the typeset version. What do you think?

**Comment by larsbrinkhoff** [comment]
Another thing. There's precedent for putting the binary in GT40; URUG BIN, or RUG; URUG BIN see MAPS). Putting it in SYSBIN was my own idea. No big deal, I suppose, but let me know if you have any argument either way.

**Comment by larsbrinkhoff** [comment]
Running in SIMH.
urug

**Comment by larsbrinkhoff** [comment]
GT40 featuring in a film from the AI Lab.  
https://archive.org/details/AIfilms/103-consort.mp4
gt40

**Pull request merged**
