### PR TITLE
Make IP number configurable

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Make it easier to specify the target IP number when building.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I removed the binary host table from SYSBIN; it's now built from scratch.

@b4 Can you see if this solves #402?

**Comment by eswenson1** [comment]
Looks like this failed. Fix?

**Comment by larsbrinkhoff** [comment]
Yes, apparently some problem with the SIMH build.  I'll look into it and request a review when it's done.

**Comment by larsbrinkhoff** [comment]
Fixed.

**Comment by eswenson1** [comment]
I think the solution of building the binary host table the way you're doing it is fine. I suspect the way I was building it the right way of doing it once the system is up and running and the host table is in use.  But for bootstrapping the system from zero, I think the way you're doing it is better.

**Comment by b4** [comment]
With a but of delay - boot drive in my VM box is failing and will need replaced.

**Comment by larsbrinkhoff** [comment]
@b4 Whenever you are ready, of course.  You should just have to edit the top of the Makefile to change the networking configuration.

**Comment by b4** [comment]
*comsat$j!
*$l .mail.;comsat bin
*bughst/'NEW$:   .IOT U4,3131   1203001144
domgat/   0   1203001005
tcpgat/   0   1203001005
debug/   -1   0
xvers/   -1   0
purify$g
:PDUMP DSK:.MAIL.;COMSAT LAUNCH
*:kill
*:job comsat
!
*:load .mail.;comsat launch

it did not crash!

However...what format is the IP address?  That doesn't seem to be octal as that's most definitely not 10.12.2.100 ;)

**Comment by larsbrinkhoff** [comment]
Great!  Yes, 1203001144 is octal for 10.12.2.100.

Quick check in Emacs: (+ (ash 10 24) (ash 12 16) (ash 2 8) 100) gives the answer 168559204 (#o1203001144, #xa0c0265)

**Pull request merged**
