### PR TITLE
CHESS

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
RG; CHESS2 614  
CHPROG; CHESS2 ORDER  

.INSRTs missing file AGB; C DIS, but it probably moved to CHPROG; OCDIS 21.  
.INSRTs missing file AGB; CHCH, but it's optional.  
EDIT: No, those files won't work.  However, CHESS2 works without any .INSRT files as long as TV and CHEOPS are disabled.

CHPROG; OCM 470  
CHPROG; OCAUX 470  
CHPROG; OCDIS 212  
CHPROG; OCDAGB 21  
CHPROG; CHNET 29  
CHPROG; CCHEOP 484 (optional)

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
It's actually two separate chess programs.  RG; CHESS2 614, and CHPROG; OCM 470.

I have built CHESS2 for both timesharing and standalone.  I disabled the use of a Knight TV display.

I have built OCM for timesharing only.  It should run standalone too, but so far I haven't figured out how to use it.  CHESS2 has a friendly help screen, but OCM doesn't.  ^L does a redisplay of the board.

**Comment by larsbrinkhoff** [comment]
I did figure out more about OCM and added a short OCM ORDER.  Short version: enter ^E to have the program make a move.

**Comment by larsbrinkhoff** [comment]
Krakauer says he doesn't have any code.

**Comment by larsbrinkhoff** [comment]
Questions for Greenblatt:

- Which two versions of the chess program are these?  Are they both by you?
- Is anyone of them Machack?
- What does OCM mean?  Old Chess something?

**Comment by atsampson** [comment]
It does look like OCM is Mac Hack. Supporting evidence:

- The piece values are as described in AI Memo 174 (aside from KQ?).
- `ADRAW` implements the accept/decline draw mechanism described in AI Memo 174.
- [Krakauer writes](http://ljkrakauer.com/LJK/60s/chess1.htm) "Mac Hack VI had an "Undo" command, actually called "Unmove", which was invoked by typing the single character <Ctrl-u>". OCM's ^U calls `UNMOVE`.
- The `SAVE`/`ALG`/`PG` commands shown in [Krakauer's 1968 transcript](http://ljkrakauer.com/LJK/60s/game1list.htm) work in the same way in OCM.

There's a list of other long-form commands it understands at SYMPS; most need an argument, e.g. `PPV 1`.

Do we have the opening book data for it? At present it plays... poorly if you say `BOOK 1`. It looks like the file should be called `DSK:BOOK MOVES`.

**Comment by larsbrinkhoff** [comment]
Thanks for doing this research.

We don't have any file called BOOK MOVES, but I'll look for it.

**Comment by aap** [comment]
smj from the @livingcomputermuseum will visit Greenblatt next month. He told me he probably still has some earlier MACHACK VI code

**Comment by atsampson** [comment]
CHESS2 is Alan Baisley's Tech II. See:

- https://chessprogramming.wikispaces.com/Alan+Baisley
- https://www.saildart.org/TECH2.SGK[UP,DOC] (nearly the same as CHESS2's built-in help)

https://www.saildart.org/CHESS.AKC[UP,DOC] says that DCHESS.DMP on SAILDART is Greenblatt's chess program; the earliest version they have is from 1972.

**Comment by larsbrinkhoff** [comment]
@atsampson, is this any good?  
https://github.com/PDP-10/its-vault/blob/master/files/chess/book.moves

**Comment by atsampson** [comment]
Hmmm. I don't know if that's the right format, but it's probably not the actual book file - AIM-174 says "The book contains over 5000 moves", so 114 bytes is a bit short.

On the other hand, though, https://github.com/PDP-10/its-vault/blob/master/files/muddle/book.4 looks like an openings book and has 6000-odd words in it...

**Comment by atsampson** [comment]
The [LCM interview transcript with Greenblatt](http://archive.computerhistory.org/resources/text/Oral_History/Greenblatt_Richard/greenblatt.oral_history_transcript.2005.102657935.pdf) (p26) talks a bit about the book data: "This guy Larry Kaufman generated our opening book. And I had a thing that encoded the opening moves ... in a small amount of memory ... and it was compacted pretty efficiently". So maybe book.4 is the input data for that?

**Comment by larsbrinkhoff** [comment]
Still, 114 bytes would be extremely small for thousands of moves.  Maybe book.moves is an early version with fewer moves.  But it could be better than nothing.

Maybe some time in the future we can find Greenblatt's thing and see if we can process book.4 with it.

**Comment by larsbrinkhoff** [comment]
DECUSLIB10-01 has a CHESS.SAV that is claimed to be MacHack, and it's timestamped 1970.  I disassembled it, but there's no use of device 130 (the 340).

**Comment by larsbrinkhoff** [comment]
See #897 and #1024 for yet another chess program.  The command to display is yet another variation: `.BD`

**Comment by larsbrinkhoff** [comment]
OCM works with the Knight TV display.
ocm

**Comment by larsbrinkhoff** [comment]
@atsampson, maybe this?

https://github.com/PDP-10/its-vault/blob/master/files/rg/book.22

**Comment by larsbrinkhoff** [comment]
Alan Baisley by the PDP-6 and 340 display, playing MacHack VI.

baisley

Source: https://archive.org/details/AIfilms/04-cubechess.mp4

**Comment by larsbrinkhoff** [comment]
Greenblatt talks about Tech II five minutes in here:  
http://projects.csail.mit.edu/films/aifilms/Podcasts/45-robot.mp3

**Pull request merged**
