### PR TITLE
Build for FreeBSD on Cirrus CI

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I'm trying to use Cirrus CI to build for FreeBSD:

https://github.com/PDP-10/its/tree/lars/cirrus

### CODE REVIEW

**Comment by tvrusso** [comment]
To date I have seen no problem with the build mixing and matching gcc and clang.  Some Makefiles explicitly invoke gcc, some $(CC) (thereby getting clang instead).  As far as I can tell it all works fine once everything completes.

**Comment by larsbrinkhoff** [comment]
@tvrusso, do you know if libusb is available for FreeBSD?  And if so, what is it called?

**Comment by tvrusso** [comment]
I don't think you need a package for that.  According to the ports system:

Port:   devel/libusb
Moved:  
Date:   2013-04-30
Reason: Has expired: has been already included into base system

So it should just be there on any recent system since 2013.

**Comment by larsbrinkhoff** [comment]
Getting close to a working build for "simh" (KS10) and "pdp10-ka" (KA10).

KLH10 has a minor problem with libusb which I'm going to fix later.

"pdp10-kl" does not do well.  Ping @rcornwell.

**Comment by larsbrinkhoff** [comment]
KL10 failure looks like this:

```
spawn ./tools/sims/BIN/pdp10-kl build/pdp10-kl/boot
KL-10 simulator V4.0-0 Current        git commit id: 88b26df8
^[lits
 BINU   
The last command timed out.
gmake: *** [Makefile:101: out/pdp10-kl/rp04.1] Error 1
```

Expected is this:

```
spawn ./tools/sims/BIN/pdp10-kl build/pdp10-kl/boot
KL-10 simulator V4.0-0 Current        git commit id: 88b26df8
$L ITS BIN
$$L SALV BIN
```

This is an older version of the KL10 simulator.  I will need to retry with the newest version.

**Pull request merged**
