### PR TITLE
Added mail support (COMSAT, MAIL, RMAIL, DQ device).

### PR DESCRIPTION
**Pull request by eswenson1**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'll take a look at the SIMH issue, but probably not today.

**Comment by eswenson1** [comment]
I committed a change to this branch that will skip the COMSAT 
initialization on SIMH. This will allow the build to complete on SIMH 
and should allow us to merge this. I will then look into exactly why 
this fails on SIMH and see if a better fix is possible. COMSAT should be 
usable for local mail delivery without network support.

I'd like to get the COMSAT/MAIL support merged, however.  -- Eric

**Comment by eswenson1** [comment]
Can I merge this now. Travis is happy now.

**Comment by larsbrinkhoff** [comment]
Thanks, merged.

**Comment by bictorv** [comment]
I have some patches to DQDEV and RESOLV documented at the end of http://its.victor.se/wiki/dqdev (configuration, mainly).

**Comment by eswenson1** [comment]
Thanks. I'll take a look.

-- Eric

**Pull request merged**
