### PR TITLE
11LOGO

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
11LOGO; DC11 4  
11LOGO; DISPAT 25  
11LOGO; EVAL 336  
11LOGO; MASS CMD  
11LOGO; .PDP11 (INIT)  
11LOGO; READ 62  
11LOGO; SSA CMD  
11LOGO; SYSTEM 327  
11LOGO; .TECO. (INIT)  
11LOGO; TS 11HERE  
11LOGO; TURTLE 61  
11LOGO; TYI 152  
11LOGO; ZEND 67

LOGO running on the PDP-11/45.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
This pull request could be ready to do, but I'd like to investigate a little bit more:

- How to access the attached disk?  Is there a way in 11LOGO to list files, or save/restore the state?
- Whether the emulated TK display works.  Try some turtle graphics.

**Comment by larsbrinkhoff** [comment]
These are from 1974, whilst our version of 11LOGO is from 1972.

- [Logo Manual](https://dspace.mit.edu/bitstream/handle/1721.1/6226/AIM-313.pdf)
- [A Glossary of Logo Primitives](https://dspace.mit.edu/bitstream/handle/1721.1/6228/AIM-315.pdf)

**Comment by Alexey-Slyusar** [comment]
It is just fantastic news! Thank you!

The "10 Workolace" and "11 File System" sections of the AI Memo 313 describes how to list files and save / restore workplace (state is called workplase in Logo).

Section "13. Display Turtles" of the same document describes 11LOGO display routines. 

I will try the things out in the evening and get back with results.

**Comment by larsbrinkhoff** [comment]
I tested workspace disk commands, but they don't appear to work in this version.

To test turtle graphics, we'll have to attach one more device in the PDP-11 emulator: `;a ngdis`.  The emulator must be run on the KA10 simulator which supports the Type 340 display.

**Comment by larsbrinkhoff** [comment]
11LOGO turtle graphics works in 11SIM.  Enter `STARTDISPLAY` to start drawing in the upper left quadrant.

The lower left quadrant is a 11SIM status display.  It says something about a bus error, but everything seems to work anyway.

**Comment by Alexey-Slyusar** [comment]
I can't get it up:

:pdp45
 PDP451$J
1145.427 
CORE = 8.K
!56.:core
CORE = 56.K
!;a pk
!;a df
NON-EXISTENT DIRECTORY
 ?

**Comment by larsbrinkhoff** [comment]
Oh, maybe you need to say `:cwd 11logo` first!

**Comment by larsbrinkhoff** [comment]
Sorry, my mistake.  It should be just `;L L BIN`.

**Comment by larsbrinkhoff** [comment]
Screenshot.
turtle

**Comment by larsbrinkhoff** [comment]
@Alexey-Slyusar, I made some more mistakes in the start script.  It should be fixed now.  If you want to edit your file in ITS, add `;a ngdis^M` and `400` before `;g`.

Can you advice on some nice demo program for turtle graphics?  I'd like to do a screenshot with the typical Logo spiral-y shapes.  But this Logo won't accept code like `REPEAT 36 [ FORWARD 50 LEFT 170 ]`.

**Comment by Alexey-Slyusar** [comment]
Thank you, Lars! It will be fun to find the differences between 1972 11LOGO and AI memo 313 :) I'll do my best :)

But unfortunately, I still can't get the things working. Due to hardware problems I've changed my hardware and I trying to build the KA10 simulator on my current machine but unsuccessful:
KA-10 simulator V4.0-0 Current        git commit id: 82181d19
build/sims/init-7> at dpa0 out/sims/rp03.2
DPA: creating new file
build/sims/init-8> at dpa1 out/sims/rp03.3
DPA: creating new file
build/sims/init-9> at dpa2 out/sims/rp03.0
DPA: creating new file
build/sims/init-10> at dpa3 out/sims/rp03.1
DPA: creating new file
MAGDMP
$$t
The last command timed out.
Makefile:73: error «out/sims/rp03.2»
make: *** [out/sims/rp03.2] Error 1
So I am working on figure out what is wrong.

At the same time I've got the klh10 on my current hardware and get 11LOGO working. But even core build-in text procedures doesn't work:
11LOGO 1005
?
?2+2
016560 WHAT SHOULD I DO WITH 4
?"hello
016560 WHAT SHOULD I DO WITH "hello
?[hi, there!]
016560 WHAT SHOULD I DO WITH hi, there!
?pirnt 7
047372 ... HAS NO MEANING.
?

I mean that work only infix arithmetic operations like 2 + 2 and self-evaluated expressions like "hello and  [hi, there].
But even "print 7" doesn't work. So it seems that the things work only on the KA10. But until I get the KA10 working I cannot check it.

**Comment by larsbrinkhoff** [comment]
Right, just entering numbers don't work.  `PRINT 2+2` and `PRINT "hello` does.

**Comment by larsbrinkhoff** [comment]
Oh, and CAPITAL LETTERS! :-)

**Comment by larsbrinkhoff** [comment]
I also had a similar problem building KA ITS on one of my machines, a slow VPS.

**Comment by Alexey-Slyusar** [comment]
Command TO should put you into editing mode.
Type
TO POLYSPI :SIDE :ANGLE 
And press enter.
Question mark "?" sould change to ">" it means that you're in editing mode. END takes you out of editing mode.

**Comment by larsbrinkhoff** [comment]
Yes, I have defined procedures with TO and END.  I have to use line numbers to enter lines.

I can use `EDIT POLYSPI` to edit.  I don't see a way to list the lines.  There's no PRINTOUT command.

**Comment by larsbrinkhoff** [comment]
POLYSPI stops after drawing just one line.

```
11LOGO 1005
?TO POLYSPI :SIDE :ANGLE
>10 FORWARD :SIDE
>20 RIGHT :ANGLE
>30 POLYSPI :SIDE + 1 :ANGLE
>END
POLYSPI DEFINED
?POLYSPI 5 95
062476 TOO MANY LINES
LEVEL 2  LINE 10  IN POLYSPI
?STARTDISPLAY
?POLYSPI 5 95
LEVEL 1  LINE 10  IN POLYSPI
?

**Comment by larsbrinkhoff** [comment]
Hello @natgoodman,

In this GitHub issue at https://github.com/PDP-10/its/pull/889, there is more information about 11LOGO and a screenshot with 11SIM and turtle graphics.

**Comment by Alexey-Slyusar** [comment]
Maybe this will work:
TO SPIRAL
10 LOCAL "SIDE
20 LOCAL "ANGLE
30 MAKE "SIDE 5
40 MAKE "ANGLE 95
50 FORWARD :SIDE
60 RIGHT :ANGLE
70 MAKE "ANGLE :ANGLE + 1
80 GO 50
END

**Comment by Alexey-Slyusar** [comment]
Or:
70 MAKE "ANGLE :ANGLE+1

**Comment by Alexey-Slyusar** [comment]
ctrl+g for break

**Comment by Alexey-Slyusar** [comment]
Oh,  shame on me :)
:ANGLE should incease insted :SIDE. Here is right version:

TO SPIRAL
10 LOCAL "SIDE
20 LOCAL "ANGLE
30 MAKE "SIDE 5
40 MAKE "ANGLE 95
50 FORWARD :SIDE
60 RIGHT :ANGLE
70 MAKE "SIDE :SIDE+1
80 GO 50
END

**Comment by Alexey-Slyusar** [comment]
It may work without LOCAL, I think. By bumping these two lines, does it fit in 400 bytes?

**Comment by larsbrinkhoff** [comment]
Oops, I meant the number of vector lines, not the number of procedure lines.  Apparently there's an error some time before drawing 36 vectors on the display.

Other than that, I think the code works.  I made a REPEAT:

```
TO REPEAT :N :L
10 IF :N = 0 STOP
20 DO :L
30 MAKE "N :N - 1
40 GO 10
END
```

So now I can do things like `REPEAT 7 [FORWARD 50 RIGHT 95]`

**Comment by Alexey-Slyusar** [comment]
Great!
The First thing that comes in mind is write recusive version:

TO REPEAT :N :L
10 IF :N = 0 STOP
20 DO :L
30 REPEAT :N-1 :L
END

But it seems that 11LOGO can't handle such code. Some investigation needed. But firstly I must solve my problems with KA10.

**Comment by Alexey-Slyusar** [comment]
To list procedure type:
PO REPEAT
To list all defined procedures:
PO ALL

**Comment by Alexey-Slyusar** [comment]
I was not attentive. You wrote already, that PRINTOUT doesn't work, So obviously PO doesn't work either.

**Comment by Alexey-Slyusar** [comment]
I've got the things working!

TO POLYSPI :SIDE :ANGLE
10 FORWARD :SIDE RIGHT :ANGLE
20 POLYSPI (:SIDE + 5) :ANGLE
END

?POLYSPI 5 95
1procedure

?POLYSPI 5 90
2procedure

?POLYSPI 5 120
img_48642

**Comment by Alexey-Slyusar** [comment]
All recursive procedures interrupted by the system due to the problem that @larsbrinkhoff already mentioned (400 octal byte restriction) or due "OUT OF BOUNDS" error. 

It is interesting that AIM-313 has a solution (a kludge?) for "OUT OF BOUNDS" error:
Run a procedure "but first  ERSET the following procedure:
TO TURN
10 LEFT 180
20 ERRET 10
END
Now every time the "OUT OF BOUNDS" error occurs TURN will turn the turtle around and keep going." (p. 69)
 
But it seems that we have very early 11LOGO system with very limited vocabulary and it doesn't have error handling facilities ( as a workspace management or file system handling capabilities either). But  is not so important. The most important thing is that playing with a Turtle on the ITS system is just fantastic experience!!! 
Many thanks to the PDP-10/its community!!!

**Comment by larsbrinkhoff** [comment]
Thanks for the nice screen shots!  I posted one to Twitter.

@philbudne, would you be interested in adding another display simulation to SIMH?

**Comment by larsbrinkhoff** [comment]
Demoing 11LOGO running in 11SIM yesterday brought down around of applause.

https://youtu.be/Jgo53c7-SUQ

**Comment by philbudne** [comment]
Possibly.....

I seem to recall it was well documented AND 11SIM simulates it as well?

Phil

**Comment by Alexey-Slyusar** [comment]
Great demonstration. Thank you, Lars!

**Comment by Alexey-Slyusar** [comment]
Here is a brief description of the build-in procedures (primitives) in the 11LOGO version 1005 (year 1972):
[A GLOSSARY OF 11LOGO PRIMITIVES](https://drive.google.com/file/d/1gKXYHLcV7MyXINfvZeth4wSxq32_42Nc/view?usp=sharing)

I am steel working on it so it is a draft of the document.

**Comment by Alexey-Slyusar** [comment]
And here is some more turtle art :)))
doodle1

**Comment by larsbrinkhoff** [comment]
Thanks for that list, @Alexey-Slyusar!  I think it should go in the 11LOGO directory when it's finished.

Some notes:
- KILLDISPLAY is probably the opposite of STARTDISPLAY.  I do wonder how to use a display other than the upper left?
- The turtle should be a triangle, but isn't.  Also, I think LEFT doesn't always turn the right angle.  There may be bugs.
- RUG probably jumps to the PDP-11 debugger.  We have it (RUG; AR >), but how to get both that and 11LOGO running we don't know yet.
- VERSION is the sum of all source file versions.

**Comment by larsbrinkhoff** [comment]
- What is THING?
- DO can evaluate a list.
- Are there any line editing characters?  Backspace doesn't work, is there another way to delete?

**Comment by larsbrinkhoff** [comment]
@Alexey-Slyusar, I invited you to the PDP-10 organization.  You should see the invitation in email, and also here: https://github.com/PDP-10

**Comment by Alexey-Slyusar** [comment]
Thank you, Lars! I really appreciate it.
I'm happy to join the community!

пт, 31 авг. 2018 г. в 10:42, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
SIMH configuraition to run 11LOGO:

```
set cpu 11/45
set cpu 56k
set dz disabled
set pclk enabled
set ke enabled
set hk disabled
set rf enabled
at rf0 file

**Pull request merged**
