### PR TITLE
Added IDLE, which displays idle users.

### PR DESCRIPTION
**Pull request by eswenson1**

### CODE REVIEW

**Comment by eswenson1** [comment]
This PR resolves ticket #48

**Comment by larsbrinkhoff** [comment]
If you want to merge this yourself, do this:

    git fetch -p        # to update origin/master
    git checkout ejs/idle
    git rebase origin/master
    git status               # to see conflicted files
    # resolve conflicts
    git add -u
    git rebase --continue
    git push -f

Now it should be possible to "Rebase and merge" in GitHub.

**Comment by eswenson1** [comment]
Did the above steps.  Waiting for Travis checks.

**Comment by larsbrinkhoff** [comment]
There's a conflict marker left.

**Comment by eswenson1** [comment]
I'll check.

**Comment by eswenson1** [comment]
Fixed, committed, and pushed.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Pull request merged**
