### PR TITLE
CLOCK - Knight TV clock

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
KLH; CLOCK 84  
KLH; DUUOS 38  
KSC; MSTAT > *missing*

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Big analogue clock.
big

**Comment by larsbrinkhoff** [comment]
Small version in upper right corner.  Runs in the background.
tiny

**Comment by larsbrinkhoff** [comment]
Or digital.
digi

**Comment by larsbrinkhoff** [comment]
We don't have a policy, so it's open for discussion.

My thinking is that programs.md should list all programs.  It's not entirely clear exactly what a program is.  We don't have individual EMACS libraries listed, for example.

Another thought is that not all programs must be in SYS*n*.  They can still be called with the :*FOO*;*BAR* syntax.  We already have ALAN;GENSYM, C;CC, BKPH;ZAP, KSHACK;MICRO, GAMES;CHESS, BBN;LOGO, AAP;FORTH, etc.  Some of those are historically correct, others are recent inventions.

**Comment by eswenson1** [comment]
I wonder if it would be a good convention to specify how to invoke the program (e.g. :alan:gensym) if the program doesn't live in SYS:

**Comment by larsbrinkhoff** [comment]
Good idea.  I think that would be an improvement.

**Comment by larsbrinkhoff** [comment]
I'm weary of adding these half crappy names I came up with, but I don't want this to linger on.  I'll make a note that they can be reconsidered.

**Comment by eswenson1** [comment]
Or just include (in parens) the install directory? Maybe anyone using ITS will be smart enough to use FIND to find programs that don’t just work by virtue of being in SYS:.

**Comment by larsbrinkhoff** [comment]
The big watch should be SYS1; TS CLOCK.

**Comment by larsbrinkhoff** [comment]
The small clock should be TS WATCH.

**Pull request merged**
