### PR TITLE
MIGS - Muddle interactive graphics system

### PR DESCRIPTION
**Pull request by Rick-Shiffman**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Hello @Rick-Shiffman,

I think I understand how the ARDS/Imlac and Tektronix output modes work, because the graphics drawing commands are fixed.

However, would you mind explaining how GT42 works?  Is there some particular software that must be running on the GT42 for MIGS to use it as an output device?

**Comment by Rick-Shiffman** [comment]
Our (USC-ECL) gt42 was running the mybook software terminal emulator. This was pdp11 assemble code that was a slightly modified version of DEC'a picturebook software. My changes were to add support for a 3' by  3' tallos tablet as a graphical input device for the users to  interact with the gt42. If you have a copy of DEC's Picture Book program, MIGS should work fine except for the graphical input. I have no idea if my mybook code exists any more. When the gt42 wasn't playing space war or Lem. It was used by FORTRAN and muddle and assembly language  programs on the IBM360/44 or ECL's tenex. I did learn an import lesson about working  with Fortran. One of my early tablet drives would besides returning -1 as an error, it also set its first argument, the mode to -1, the mode was no normally set to 2, this didn't bother muddle since numbers are passed by value. FORTRAN uses call by reference for everything. So if the tablet got an error ever 2 in the FORTRAN program became -1. I learned very quickly that changing an argument to report an error was a very bad idea! I was the  TA for CS575, the interactive graphics coarse at USC and my class used the gt42 and the tablet. I wrote the first version of MIGS as my class project in CS575 and it got me the TAship of the class. I was the only person in CS575 who didn't write a game as a  class project. USC also had a Adage AGT-10 vector drawing computer and a large Craytos display scope. The adage was a 30bit word interupt driven computer that's assembly language was like parallel microcode. You made up the
Instructions as you went along. I was introduced to computer graphics on that machine. It had spacewar also!

**Comment by Rick-Shiffman** [comment]
I am working ENTERY function for RRS;XPACKG >, 
my muddle package system i an off by 1 indexing into a loop. Hope to fix it tomorrow 
    Rick
PS PACKAGE and ENDPACKAGE are working.

**Comment by larsbrinkhoff** [comment]
Thanks.  I'm inquiring about the Picture Book software, but it's not looking good.

**Review by eswenson1 — APPROVED** [review]

**Pull request merged**
