### PR TITLE
Name Dragon pictures.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
CHANNA; NAMPIC *

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I made a selection.  Feel free to object.

**Comment by atsampson** [comment]
Are SHIP/SHIP2 from SAIL's GEOMED (e.g. see [DAT,BGB]SHIP.B3D)?

**Comment by larsbrinkhoff** [comment]
I don't know.  Do we have a way to view GEOMED files?

I have only seen the GEOMED torus, and it didn't have hidden lines removed.

**Comment by larsbrinkhoff** [comment]
Yes, it does look much like the starship in Stanford AI memo 232.  
https://stacks.stanford.edu/file/druid:bc777my6054/SC1041_SAIL_AIM_232.pdf

**Comment by bonniedalzell** [comment]
Bonnie Dalzell (MA), me is the creator of three of these images above:
The dragon
The (prancing turtle)
The unicorn

I did them when I had my job as an experimental user at the Logo Group at the MIT AI lab in 1975.
I release them into the public domain but would appreciate recognition as the artist if they are used for anything.
Putting the three of them together on a tee-shirt might be neat. I lost my collection of weird tee-shirts in a house fire Dec 31,  2017 and have been looking for designs since then. 
 
I think we had some sort of graphic input device that was used to do free hand drawing and get them into the DEC PDP computer we had in the Logo group.
I will look around to see if I have any other images from that time period among my archived artwork.

Margaret Minsky or Richard Stallman may remember more about the graphic input methods available then.  So much time has passed and computers are so much more advanced now that some things become fuzzy.

**Comment by larsbrinkhoff** [comment]
I rushed to order this to wear at the [VCF](http://vcfed.org/vcf-pnw):
nampic

**Comment by larsbrinkhoff** [comment]
takeme

From https://youtu.be/-G6Lg6HYN8k?t=27

**Comment by larsbrinkhoff** [comment]
Pictures spotted in Stanford SAILON 74: https://www.saildart.org/allow/pdf/SAILON/74/find-a-font.pdf

sailon74

**Pull request merged**
