### PR TITLE
NFILE - New file server

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
BAWDEN; NFILE 185  
NETDOC; RFC037 NFILE

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@eswenson1, you think this is ok to merge?

**Comment by eswenson1** [comment]
I don’t see why not — considering it is a new program being added.

do we have any NFILE clients we can use to test that the server works? It might be good to prove that it works before committing.

**Comment by larsbrinkhoff** [comment]
If I understand correctly, NFILE was a Symbolics protocol.  I haven't found anything else, so I assume a Symbolics Lispm would be the only client.  And I don't have one of those.

**Comment by eswenson1** [comment]
I do have a Symbolics client, but I haven't put it on the chaosnet yet.  Maybe I'll try to do that.

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Merged.  If bug fixes or updates are needed, they can be done separately.

**Pull request merged**
