### PR TITLE
Utility for printing binary files

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Read binary files, and output each word in many different formats:

- Twelve octal digits
- Two halfwords, like AOBJN pointers
- SIXBIT
- ASCII
- Squoze

Suggested name: OD, if that isn't too Unixy.

This isn't anything that can't be done in DDT, it would just be slightly more convenient.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I wrote one in Maclisp.

Putting the FASL file in SYSBIN is probably wrong.  Where should it go?

**Comment by eswenson1** [comment]
Well, for standard system packages the FASL file goes in the LISP; directory.  However, take a look at LIBLSP and LIBDOC, and read the -READ- -ME- there.  Author-maintained LISP code seems to have gone in LIBDOC.

**Comment by larsbrinkhoff** [comment]
Hold on, I'll add half-word display too.

**Comment by larsbrinkhoff** [comment]
Depends on #436.

**Comment by eswenson1** [comment]
Still holding on, right?

**Comment by larsbrinkhoff** [comment]
It should be done now.  I wanted to use FORMAT ~< ~>, so I had to bring in LISP; FORMAT BRACK.

**Pull request merged**
