### PR TITLE
Enable PD clock

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Build KA ITS with PD clock enabled.  See PDCLKP.

Enable PD clock in SIMH scripts.

Fix bugs if any.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'd like to test this extra carefully, because the last time I used this there were some interrupt problems.  They could have been unrelated to the PD clock, but I'm not sure.

**Comment by eswenson1** [comment]
What does this error mean, when starting up ka10?

```
sim> set dpy enabled
Display initialization failed
sim>
```
It seems I *must* start up a gt40 or tv11 or tvcon?  Is that true?  The start script doesn't enforce this.

I've been unable, so far, to run the ka10 ITS from lars/pdclock branch as a result.

**Comment by larsbrinkhoff** [comment]
Thanks for checking.  It's good to have any kinks ironed out.

That error probably means the "ka10" binary was built without the display code.  It should be built like this:

    make ka10 TYPE340=1

But it's not required; ITS runs without it.  What happened after this message was printed?

No, you don't need gt40 or tv11 or tvcon.  I regularly run without those.

**Comment by eswenson1** [comment]
Didn't start:

```
eswenson@eswenson-ThinkPad-W520:~/ITS/simstest$ ./my_start

KA-10 simulator V4.0-0 Current        git commit id: 0b525336
Display initialization failed
./run-10> at tk 10000
Listening on port 10000
./run-11> set mty enabled
Non-existent device
./run-12> at mty 10003
Non-existent device
./run-13> set ten11 enabled
Non-existent parameter
./run-14> at ten11 10011
Non-existent device
./run-15> at ptr bin/ka10/boot/dskdmp.rim
File open error
./run-16> at dpa0 out/sims/rp03.2
File open error
./run-17> at dpa1 out/sims/rp03.3
File open error
./run-18> at dpa2 out/sims/rp03.0
File open error
./run-19> at dpa3 out/sims/rp03.1
File open error
./run-24> b ptr

Unit not attached, PC: 000000 (LUUO00 0,0)
sim>
```

my_start is the same as start, except the paths are changed to be relative to my working directory.

**Comment by eswenson1** [comment]
This is my session:

```
eswenson@eswenson-ThinkPad-W520:~/ITS/simstest$ ./my_start

KA-10 simulator V4.0-0 Current        git commit id: 0b525336
Display initialization failed
./run-10> at tk 10000
Listening on port 10000
./run-11> set mty enabled
Non-existent device
./run-12> at mty 10003
Non-existent device
./run-13> set ten11 enabled
Non-existent parameter
./run-14> at ten11 10011
Non-existent device

 DSKDMP
its
$G
SALVAGER.313


KA ITS 1648 IN OPERATION
KA ITS 1648 SYSTEM JOB USING THIS CONSOLE.PDTIME OFFSET, NOT ON DISK.
PLEASE SETLOC APPROPRIATELY.
TV 11 WENT DOWN --
 LOGIN  TARAKA 0
TOP LEVEL INTERRUPT 200 DETACHED JOB # 3, USR:TARAKA CNAVRL
TARAKA NETIME IOTLSR


                              Attention!

                              Attention!

The time could not be set because:
No host responded.
It will be necessary for someone to set the time
manually by logging in and running :PDSET.

TOP LEVEL INTERRUPT 400 DETACHED JOB # 11, USR:TARAKA TVFIX

KA ITS 1648 SYSTEM JOB USING THIS CONSOLE.
```

**Comment by eswenson1** [comment]
Here is my run script:

```
eswenson@eswenson-ThinkPad-W520:~/ITS/simstest$ cat run
set console wru=034
set cpu its
set cpu 1024k
set cpu idle
set cpu mpx
set pd enabled
set pd on
set dpy enabled
set tk enabled
at tk 10000
set mty enabled
at mty 10003
set ten11 enabled
at ten11 10011
at ptr ./dskdmp.rim
at dpa0 ./rp03.2
at dpa1 ./rp03.3
at dpa2 ./rp03.0
at dpa3 ./rp03.1
set mta mpx=7
set mta type=b
set dt mpx=6
set dpa noheaders
b ptr
```

**Comment by eswenson1** [comment]
Note that pd is enabled and on.

**Comment by eswenson1** [comment]
Hmm...I guess it is working. I typed ^Z, got a DDT, ran PDSET, logged out, and logged back in. Clock was still set. Shut down. Rebooted, clock was still set.  So I guess it is just all the TOP LEVEL INTERRUPTS and "TV 11 WENT DOWN" errors that made me think things weren't working properly.

**Comment by eswenson1** [comment]
I rebuilt ka10 as per your instructions. Copied it to my working directory and re-reran my_start.  Got this:

```
eswenson@eswenson-ThinkPad-W520:~/ITS/simstest$ ./my_start

KA-10 simulator V4.0-0 Current        git commit id: 40e11301
Display initialization failed
./run-10> at tk 10000
Listening on port 10000
./run-12> at mty 10003
Listening on port 10003
./run-14> at ten11 10011
Listening on port 10011

 DSKDMP
```

So as you see, I still got the Display initialization failed message.  Also, the ka10 that I had previously used was the one that was built by the build -- so if it was built incorrectly, it was the build that incorrectly built-it.

**Comment by larsbrinkhoff** [comment]
The SIMH makefile auto detects the presence of libraries, including SDL2 that needed for the Type 340 simulation.  So even when TYPE340=1 is on the make command line, it can still fail and maybe that's what happened here.

Try something like:

    sudo apt-get install -y libx11-dev libxt-dev libsdl2-dev

I don't remember which libraries are required exactly, but the build/dependencies.sh script installs these and some more.  This is what's used by the CI builds.

**Comment by eswenson1** [comment]
I checked the output from my ka10 build, and I didn’t get any errors. It did successfully build a ka10 executable when I built with the 340 flag you mentioned earlier.

**Comment by larsbrinkhoff** [comment]
> I checked the output from my ka10 build, and I didn’t get any errors.

Missing libraries don't generate an error.  They just aren't linked in, and then the display code is excluded.

**Comment by eswenson1** [comment]
So how are you supposed to know that the library is missing?  No error message?

**Comment by larsbrinkhoff** [comment]
If it works, you'll see libsdl2 on the command line that links SIMH.  Actually, it compiles and links everthing in one go, so its' just one huge `gcc` command.

Then, when SIMH is started `set dpy enabled` shouldn't say anything.

**Comment by larsbrinkhoff** [comment]
I suppose the approval means you tested this to your satisfaction?

**Comment by eswenson1** [comment]
Well, I ran for a few hours and used a bunch of programs with no issues. But I’m not running it continuously. Do you want me to run for a while and attempt to develop code on it?

-- Eric

**Comment by larsbrinkhoff** [comment]
> So it would appear I do have it installed. So now what? How 'come I don't have display support in my ka10?

First of all, note that this is only for the Type 340 display.  You don't need this for the GT40 or Knight TV.

It's hard for me to say what's wrong.  The SIMH makefile does some checks to see that the prerequisite libraries are installed, so we have to debug that.

Maybe try these too:

    sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev

Now that I check the CI build logs, I see they don't include the SDL2 libraries either.  But they do include type340.c and -lX11 etc.  So I'm not sure the display code is OK or not.

**Comment by larsbrinkhoff** [comment]
> Do you want me to run for a while and attempt to develop code on it?

That would be a good idea, I think.

Do try `./start tv11 tvcon` some time.  Use F1 instead of ^Z.

**Comment by larsbrinkhoff** [comment]
By the way, since it came up here, the GT40 isn't very usable yet.  The GT40 comes with a boot ROM which is a *very* crude terminal, and can load a binary.  We *should* be able to do something like `:GTLOAD GT40; VT07 BIN29`, but it gets stuck somewhere.  That's the "Datapoint emulator and graphics package".

It should also be possible to convert the binary to a file acceptable by the SIMH pdp11 and run it directly, bypassing the ROM.

**Comment by larsbrinkhoff** [comment]
When VT07 is up and running, we should be able to use it for SUDS, Lisp, and Logo.

**Comment by larsbrinkhoff** [comment]
The start of my build output from `make ka10 TYPE340=1` is

```
lib paths are: /lib/ /lib/i386-linux-gnu/ /lib/x86_64-linux-gnu/ /lib32/ /libx32/ /usr/lib/ /usr/lib/i386-linux-gnu/  /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/libfakeroot/ /usr/lib/x86_64-linux-gnu/mesa-egl/ /usr/lib/x86_64-linux-gnu/mesa/ /usr/lib32/ /usr/libx32/ /usr/local/lib/
include paths are: /usr/include
using libm: /usr/lib/i386-linux-gnu/libm.so
using librt: /usr/lib/i386-linux-gnu/librt.so
using libpthread: /usr/lib/i386-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using libdl: /usr/lib/i386-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
using mman: /usr/include/sys/mman.h
using libSDL2: /usr/include/SDL2/SDL.h
***
*** ka10 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 5.4.0.
*** - video capabilities provided by libSDL2 (Simple Directmedia Layer).
```

And from Travis CI:

```
lib paths are: /lib/ /lib/x86_64-linux-gnu/ /usr/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/mesa-egl/ /usr/lib/x86_64-linux-gnu/mesa/ /usr/lib/x86_64-linux-gnu/mir/clientplatform/mesa/
include paths are: /usr/include
using libm: /usr/lib/x86_64-linux-gnu/libm.so
using librt: /usr/lib/x86_64-linux-gnu/librt.so
using libpthread: /usr/lib/x86_64-linux-gnu/libpthread.so /usr/include/pthread.h
using libpcreposix: /usr/lib/x86_64-linux-gnu/libpcreposix.so /usr/lib/x86_64-linux-gnu/libpcre.so /usr/include/pcreposix.h /usr/include/pcre.h
using libdl: /usr/lib/x86_64-linux-gnu/libdl.so /usr/include/dlfcn.h
using libpng: /usr/lib/x86_64-linux-gnu/libpng.so /usr/include/png.h
***
*** ka10 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 4.8.4.
```

So clearly the makefile didn't find all the libraries.  I think it searches LIBPATH for a library file, and INCPATH for an include file.

**Comment by larsbrinkhoff** [comment]
Sorry, I had this wrong.  You won't be needing the SDL2 libraries.  If the command line says `-lX11 -lXt` you should be fine.

(I'm linking in SDL2 because I updated the 340 simulation to use it.)

**Comment by eswenson1** [comment]
> > Do you want me to run for a while and attempt to develop code on it?
> 
> That would be a good idea, I think.
> 
> Do try `./start tv11 tvcon` some time. Use F1 instead of ^Z.

That doesn't work for me.  Both tv11 and tvcon claim they need a hostname argument. And when I manually try to start tv11 and tvcon (from a telnet login to ka10 ITS), I get errors from either. So I'm not able to run tv11 nor tvcon.  I am running ka10 ITS now without.  Of course, on startup, I get 2 or three top-level interrupts.  Peek shows this:

```
DB ITS 1648  Peek 630   1/12/2018 12:14:08  Up time = 2:34
Memory: Free=359   Runnable Total=11 Out=4     Users: High=12 Runnable=1
Index Uname Jname Sname     Status   TTY    Core Out %Time    Time PIs
  0 SYS    SYS    SYS        HANG    ?        44   0   0%
  1 CORE   JOB    CORE       UUO     ?         0   0   0%
  2 EJS    HACTRN EJS        HANG    >        30   9   0%
  5  EJS    P      EJS       MULTIX  T1  C    11   3   0%
  3 TARAKA CNAVRL CNAVRL     10!0    ? DSN    26   0   0%          .VALUE
  4 EJS    FIDO   EJS        10!0    ? DSN     1   0   0%
  6 TARAKA NAMDRG NAMDRG     10!0    ? DSN    18   0   0%          .VALUE
  7 TARAKA PAPSAV PAPSAV     HANG    ?         1   0   0%
 10 PFTHMG DRAGON PFTHMG     HANG    ?         6   0   0%
 11 TARAKA TVFIX  TVFIX      10!0    ? DSN     2   0   0%          ERROR
Fair Share 99%     Totals:                   139       0%
Logout time =         Lost 0%  Idle 98%  Null time = 2:37
Q
:KILL
```

I'm assuming all those fail because there is no networking?  No wonder I use KLH10 -- I've never had much luck with ka10.

**Comment by larsbrinkhoff** [comment]
> Both tv11 and tvcon claim they need a hostname argument.

They do, but they should get it from the start script.  `tv11 -p 10011 localhost` and `tvcon $TVCON localhost`  I wonder why this doesn't work for you.

> I'm assuming all those fail because there is no networking?

I think CNAVRL does.  NAMDRG and TVFIX fail because there's no TV-11.

> I've never had much luck with ka10.

It's still a work in progress.

**Pull request merged**
