### PR TITLE
Clean up C documentation.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Forgot this:

- Rename CC.PAT[C,SYS] to CC PATCH.
- Remove E padding from CCDOC.

### CODE REVIEW

**Comment by ams** [comment]
Maybe use a .gitattributes file to explicitly mark them as text?

**Comment by larsbrinkhoff** [comment]
Not a bad idea, but I don't think GitHub honors that.

**Comment by larsbrinkhoff** [comment]
The `diff` attribute forces git to display a text diff even though it detects a binary file.

**Comment by larsbrinkhoff** [comment]
I checked.  Neither `linguist-language=Text`, nor `diff` affects GitHub.

**Pull request merged**
