### PR TITLE
BOLIO

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
BOLIO; TS BOLIO, link to next   
SYSBIN; BOLIO 174  
SYSBIN; BOLIO 177  
LSB; BOLIO 45  
LSB; BOLIO FASL

...is a dumped Lisp program.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Possible source code:

BOLIO; .BOLIO 146  
BOLIO; 1INDEX 24  
BOLIO; CONDIT 2  
BOLIO; DOC 37  
BOLIO; DUMPER 38  
BOLIO; EMACK 36  
BOLIO; FONTS 77 
BOLIO; .FORMA 33  
BOLIO; INLINE 9  
BOLIO; INSTAL 3  
BOLIO; IOS 107  
BOLIO; JCL 17  
BOLIO; JIN 101  
BOLIO; JINIT 147  
BOLIO; JOUT 130  
BOLIO; JUST 296  
BOLIO; JUSTDT 163  
BOLIO; LISTIN 93  
BOLIO; LMRQ 383  
BOLIO; MACROS 13  
BOLIO; NOTES 1  
BOLIO; OUSER 41 
BOLIO; PATCH 2  
BOLIO; PMAP 12  
BOLIO; PRESS 2  
BOLIO; REF 110  
BOLIO; RFONTW 66  
BOLIO; SECTIO 35  
BOLIO; STR 36  
BOLIO; USER 64  
BOLIO; XDUMP 6  
BOLIO; .XDUMP 130

**Comment by ams** [comment]
My copy is AMBER BOLIO 5 (https://github.com/LM-3/doc/blob/master/amber.bolio.%7E5%7E)

**Comment by larsbrinkhoff** [comment]
@ams, I believe these are the source files:

JINIT, is the "init" file for loading Bolio.  It mentions these files:  
JUST  
JIN  
JOUT  
STR  
FONTS  
RFONTW  
LMRQ  

Have you seen anything like these?

**Comment by ams** [comment]
@ams, I believe these are the source files:

   JINIT, is the "init" file for loading Bolio. It mentions these files:
   JUST
   JIN
   JOUT

Couldn't locate any of those in what I have currently on hand -- will
check off-line storage.

   STR
   FONTS

To vauge to find.

   RFONTW

SYS: IO1; RFONTW LISP ? Multiple copies of that,

   LMRQ

Exists in the PDP10/ITS repository.

**Comment by larsbrinkhoff** [comment]
http://emackandbolios.com/our-story/

> Two homeless gentlemen that the lawyers did pro bono work for asked that the ice cream shop be named after them.

Emack and Bolio.  Bob in the middle.
Story-EBandBob

**Pull request merged**
