### PR TITLE
EMACS Macsyma mode

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
EMACS1; MAXIMA 26  
EMACS1; MAXIMA INFO  
EMACS; MAXIMA :EJ

Now that we have Macsyma!

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Some obvervations:

- I don't see that MAXIMA INFO is linked from INFO or .INFO.
- I don't see any files with `-*- maxima -*-`.
- There is a "Macsyma Mode" in USRCOM.

**Comment by eswenson1** [comment]
Isn’t maxima the Common Lisp rewrite of Macsyma — the latter being the maclisp one? ITS macsyma sources would have -*- Macsyma -*- and would use Macsyma mode, not Maxima mode.

**Comment by eswenson1** [comment]
Given the above, why do we need this in ITS?

**Comment by larsbrinkhoff** [comment]
I think it's just **named** "maxsima".  The INFO file says it's from 1979 where Maxsima or even Common Lisp didn't exist.  The TECO file says " EMACS macros for editting Macsyma code".

I don't know if this adds much value, but I don't think we should discard it either.

**Pull request merged**
