### PR TITLE
Additional Docs

### PR DESCRIPTION
**Pull request by everyfan**
Added some documentation for H3TEXT and CROSS.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thanks.

Rather than adding a new h3text file, conf/README could refer to the file build/h3text and explain that the file that goes into ITS is a concatenation of build/h3text and conf/hosts.

**Comment by everyfan** [comment]
OK, I just removed h3text.txt and amended the readme.

**Comment by larsbrinkhoff** [comment]
Thanks.  I squashed the third commit into the first one.

**Comment by everyfan** [comment]
I changed it so that the README points you to a sample hosts file in build/h3text.>

**Comment by eswenson1** [comment]
> I changed it so that the README points you to a sample hosts file in build/h3text.>

Ok. If that's it, then I'll approve.

**Comment by everyfan** [comment]
Hmm... The build failed. Looks like it timed out. I've actually had issues with my ITS builds timing out randomly, but i assumed that was just because I'm running my linux on an external hard drive so it's not very fast

**Comment by everyfan** [comment]
Can I go ahead and merge? If you read the klh10 log, it looks like it just timed out at a random point because building the Emacs library took too long

**Comment by larsbrinkhoff** [comment]
I restarted the build, but you can merge any time you like.

We have been having some problems with KLH10 timing out in random places on some machines.

**Pull request merged**
