### PR TITLE
Updated to build compiler from source.

### LINKED ISSUE #383: Build LISP compiler
Currently, we're dumping out a new lisp compiler from the pre-built FASL files. We need to build these FASL files from source.

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #383.

### CODE REVIEW

**Comment by eswenson1** [comment]
Ok. Will do.

**Comment by eswenson1** [comment]
Also moved all the other FASL files from src/comlap to bin/comlap.

**Comment by larsbrinkhoff** [comment]
I think you also need to add comlap to BIN in the Makefile.

**Comment by eswenson1** [comment]
Indeed. Done.

**Pull request merged**
