### PR TITLE
Update deploy-ftp.sh

### PR DESCRIPTION
**Pull request by oilcan-productions**
Adding validation function to the deploy_ftp.sh script to ensure the upload was successful. If the upload was not successful,  the script will exit with status code 1 and fail the build

### CODE REVIEW

**Review by larsbrinkhoff — APPROVED** [review]
That's a thorough validation!

**Comment by larsbrinkhoff** [comment]
Do you think the FTP password will keep expiring in the future?

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
The next to last line of the "Deploy" section says "find: ‘../pdp10-ka’: No such file or directory".  Is that something to fix?

https://github.com/PDP-10/its/actions/runs/8441743024/job/23139306028

```
Testing download of pdp10-ka.tgz
[...]
Testing archive pdp10-ka.tgz
Unpacking successful!
Testing archive integrity
find: ‘../pdp10-ka’: No such file or directory
The contents of ../pdp10-ka and ./pdp10-ka are binary identical.
```

**Comment by oilcan-productions** [comment]
No, I do not expect it to expire again. I also set up a test loop here to ensure that FTP in general keeps working.

**Comment by oilcan-productions** [comment]
> The next to last line of the "Deploy" section says "find: ‘../pdp10-ka’: No such file or directory". Is that something to fix?
> 
> https://github.com/PDP-10/its/actions/runs/8441743024/job/23139306028
> 
> ```
> Testing download of pdp10-ka.tgz
> [...]
> Testing archive pdp10-ka.tgz
> Unpacking successful!
> Testing archive integrity
> find: ‘../pdp10-ka’: No such file or directory
> The contents of ../pdp10-ka and ./pdp10-ka are binary identical.
> ```

Let me look into that, have not seen that locally.

**Comment by oilcan-productions** [comment]
Looking into the job log I think that at the end of the build we did not drop back to the its directory, which is the assumption I am making right now in the script.

**Comment by larsbrinkhoff** [comment]
@oilcan-productions, I often get this now.  If I rerun the build 1-2 times it will usually work.  Any idea why?
Screenshot from 2024-04-12 07-02-06

**Comment by larsbrinkhoff** [comment]
All variant builds run in parallel, but they upload different file names.  Also, rerunning a single failed job by itself has resulted in a broken file so I don't think parallelism is the cause.  Next time I'll try to manually download the file to check the contents.

**Comment by larsbrinkhoff** [comment]
Three out of six jobs failed.
Screenshot from 2024-04-17 07-09-48

**Pull request merged**
