### PR TITLE
Full build takes too long now

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
A full build of ITS and all program takes too long.
- Build time exceeds CI services.
- It's hard to test changes to the build script.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I pushed some commits.  I couldn't leave well enough alone, so I made a few separate scripts: emacs (not optional), lisp, scheme, misc (optional).

I see CircleCI is putting a failed build status on everything.  It's not as bad as it looks.

**Comment by larsbrinkhoff** [comment]
I intend to squash these commit together later.  For now I'll leave them in place for easier reviewing.

Build times are down to 10/15/30 minutes (SIMH/KLH10/KA10).

**Comment by atsampson** [comment]
Looks good to me so far!

**Comment by larsbrinkhoff** [comment]
I agree @eswenson1, but I'll save that for later.  I want this in soon and not keep tweaking it.

I tested the full build (whithout BASICS=yes), and there was a problem with Rabbit.

**Comment by eswenson1** [comment]
Ok, so not ready to merge yet then?

**Comment by larsbrinkhoff** [comment]
No.  It works in Travis, but it'll not work for a user who just runs make.

I'm also checking this in your VPS to see if it now works with KLH10.

**Comment by larsbrinkhoff** [comment]
No, still doesn't work with KLH10.  Somewhere like 6-10 minutes in, there's a problem with console I/O.

**Pull request merged**
