### PR TITLE
Add some old .INFO. files.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
ITS INFO dated 1974.  Note the 1973 info on the 10-11 interface.

? INFO and ^DDT INFO from 1972.

### CODE REVIEW

**Comment by eswenson1** [comment]
I hadn’t approved this because I had a pending question/comment!

**Comment by larsbrinkhoff** [comment]
Sorry, I was impatient after two days.

Feel free to post your questions and comments anyway.

**Comment by larsbrinkhoff** [comment]
I have some questions of my own: What is `? INFO` about?!?  What system name?

**Comment by eswenson1** [comment]
I guess I'm asking why we are including this?  What does it do?  It certainly doesn't have any valuable content.

**Comment by larsbrinkhoff** [comment]
I can certainly agree ? INFO is arguable.  The ^DDT and ITS files I think are not useless.  Is the use of console lights to display running jobs documented elsewhere?

My reasoning is not to judge too much.  The files were there on an ITS machine at some point, and I don't know what future generations will think is valuable or not.  That said, I'm not adding every single version of everything; I try to stick to the latest versions.

**Comment by eswenson1** [comment]
Ok

**Pull request merged**
