### PR TITLE
Short introductions for beginners

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Adding short introductions for important programs:

- [Editing with EMACS](https://github.com/PDP-10/its/blob/lars/teco/doc/EMACS.md)
- [Editing with TECO](https://github.com/PDP-10/its/blob/lars/teco/doc/TECO.md)
- [Debugging with DDT](https://github.com/PDP-10/its/blob/lars/teco/doc/debugging.md)
- [Hello world in MIDAS](https://github.com/PDP-10/its/blob/lars/teco/doc/hello-midas.md)
- [DUMP and itstar](https://github.com/PDP-10/its/blob/lars/teco/doc/DUMP-itstar.md)

Comments, @aap @lokedhs and anyone else?

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Comments, @aap @lokedhs and anyone else?

**Comment by larsbrinkhoff** [comment]
I folded #618 into this.

**Comment by larsbrinkhoff** [comment]
People, I'd like some input here.  Thanks!

**Comment by larsbrinkhoff** [comment]
@philbudne, these short guides might be useful to you.  Or are they too basic?

**Comment by lokedhs** [comment]
I would argue that they are not basic enough, at least for new users. For example, the DDT commands are explained, but it is not explained how you actually use it if you want to debug your own software.

**Comment by larsbrinkhoff** [comment]
That's a fair point.

The intended audience is people who do know how to debug programs, just not the DDT commands.

**Comment by philbudne** [comment]
For me, too basic.  I used EMACS and MIDAS extensively on TOPS-20 (and
MIDAS on TOPS-10 as well).  I need to learn how to assemble and boot
an ITS with support for the 340 enabled.  I was an ITS turist, but
that didn't include doing sys admin stuff!

Looks like it's embedded (with LOTS and LOTS of stuff) in
https://github.com/PDP-10/its/blob/master/build/build.tcl

**Comment by larsbrinkhoff** [comment]
Right, build.tcl does spell out how to build everything.

For 340 support set 340P to 1 in SYSTEM; CONFIG > or the corresponding host file.

**Comment by larsbrinkhoff** [comment]
To assemble ITS, you just do

    :midas .;nits_system;its

After that, you need to merge DDT, SALV, and NITS as explained in KSHACK; BUILD DOC.  You can do it in DSKDMP or in timesharing DDT.

**Comment by larsbrinkhoff** [comment]
Future screencasts will provide more hands-on step-by-step guides.

**Pull request merged**
