### PR TITLE
BBN Logo

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This is https://github.com/PDP-10/bbn-logo, assembled with MACRO-10 in ITS, and dumped with the DECUUO bootstrap.

On reexamination, I found that symbols and code sections match CLOGO so I think we can confidently say BBN Logo is the direct ancestor of CLOGO.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm holding off merging this until @Alexey-Slyusar had a chance to examine it more closely.

**Comment by Alexey-Slyusar** [comment]
Lars, thank you very much!
I'm getting copy of the branch.
And after I get it on my machine, I'll do close exploration with my big pleasure, of course.

**Comment by larsbrinkhoff** [comment]
I wanted to use MACRO-10 assembled from source (#1235), but it turns out it's not happy with LOGO.MAC:

```
EXCTLP+1        LOGO   PAGE 22
U       400703' 001 00 0 00 000000*              ERROR  PRNER2
EXPARR+3
U       400720' 001 00 0 00 400703*             ERROR   PRNER2  ;MISSING )?
RPREN+0 LOGO   PAGE 99
Q                                       ),EXCTRP,0,1    ;PARENTHESES ARE NOT INFIX OPERATORS BUT
PRNER2  UNASSIGNED, DEFINED AS IF EXTERNAL

%1 WARNING GIVEN
?2 ERRORS DETECTED
```

I suppose we could leave the old MACRO SHR in place and use that instead.

**Comment by larsbrinkhoff** [comment]
Or fix the LOGO source?

**Comment by larsbrinkhoff** [comment]
Adding some < > around macro arguments makes the newer MACRO happy.

**Comment by Alexey-Slyusar** [comment]
Hi Lars!

I did some exploration and here are the results:

1. The BBN LOGO version that we have has minor syntax differences both from BBN LOGO as it described in BBN report no. 1889 and from CLOGO, e.g.:

* BBN LOGO (BBN Report No. 1889):
default

* BBN LOGO that we have on ITS (I'll name it as NRC version of BBN LOGO of BBN LOGO / NRC)
default

* CLOGO
default

2. The data types that BBN LOGO / NRC can handle are the same as CLOGO has. The core vocabulary is the same too (but I continuing to check the things). BBN LOGO / NRS has the same built-in editing facilities as they described in BBN Report no. 1889. The simple built-in editor allows to edit procedure definitions directly in the environment, and there is interface for debugging, so it is some kind of IDE :-) (CLOGO has the same with the minor differences). 

3. TURTLES
It seems that BBN LOGO / NRS has its own turtles related routines. There are no SETTURTLE, LAMPON, LAMPOFF, TOOT procedures. And FORWARD and RIGHT interpreted by BBN LOGO / NRS  in some direct manner without SETTURTE:
default

4. As for overall BBN LOGO / NRC behavior, it is weak in memory allocation management and recursive procedures calls. The interpreter is crashed regularly with a message 
`ILLEGAL MEMORY ALLOCATION TRAP- ALL IS LOST.`
but you can type in DDT `*:CONTINUE` and return to the interpreter in most cases.

For example, CLOGO can easily compute FACTORIAL 100 
default

At the same time, BBN LOGO / NRC can't handle even FACTORIAL 40:

default

5. Preliminary conclusion
 It seems that, with the exception of minor syntax differences and turtle/music related parts, the core language for BBN LOGO, CLOGO and BBN LOGO / NRC is the same (Bob Orchard said that he "suspect the changes we made were related to some of the graphics terminals we had (support for the ’turtle’) and possibly for music." and it is seems so). One more point is that CLOGO has more robust mechanism for memory allocation and can handle much more recursion steps.

**Comment by larsbrinkhoff** [comment]
Thank you @Alexey-Slyusar.

You mention some BBN reports.  Where are they?

**Comment by larsbrinkhoff** [comment]
Thank you.  I made copies to the bbn-logo GitHub repository so they are easy to find.

**Comment by Alexey-Slyusar** [comment]
Actually, I found several more logo related BBN reports on the net. But the
reports are some kind of math oriented logo curriculum for seventh grade
children and don't say anything about the Logo system itself.
Do you think whether these pedagogical reports may be interesting for the
PDP-10 / ITS community members? If so, I can post links on these reports in
a current issue, or I can create separate issue here for the such original
pedagogical stuff.

пн, 24 сент. 2018 г. в 7:51, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
No, I don't think they are so interesting for this PDP-10 group.  You can post links in a comment here in case someone happens to come here to read about Logo history.  If you want to copy the documents to GitHub, I suggest making a new organization named something like "Logo-history".

**Comment by Alexey-Slyusar** [comment]
The "Logo-history", of course, will be an interesting project. And maybe I
will start such organization some day.
Thank you Lars, for the suggestion! I very appreciate it.

But unfortunately I do not have enough time for this at the moment.
So, I want to concentrate on documenting and testing the logo versions that
we have running on ITS. And also, I'm working to become skilled enough to
revive the LISP LOGO.

пн, 24 сент. 2018 г. в 11:16, Lars Brinkhoff <notifications@github.com>:

**Pull request merged**
