### PR TITLE
CLOGO 49

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
RJL; LOGO 49, dated 1973-03-09  
RJL; LOGOPS >  
RJL; TUROPS >  
RJL; MUSOPS >  
RJL; FILES >

BBN Logo ported to ITS and MIDAS.

```
TITLE LOGO
;         TM
;(C) COPYRIGHT,1970,BOLT BERANEK AND NEWMAN INC., CAMBRIDGE, MASS.???????
;LARRY KRAKAUER:  MICRONETICS:  204 ARSENAL ST. WATERTOWN  926-2570
;WALLY WEINER:  BBN:  491-1850   EXT. 423

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Complete list of binary versions:

| File | Timestamp | Version
| --- | --- | ---
| BACKUP; TS CLOGO | 1971-12-08 | 28
| SYSBIN; CLOGO BIN | (backed up 1972-04-21)| 41
| SYSBIN; CLOGO BIN | (backed up 1973-03-09) | 44
| HQM; CLOGO BIN | 1975-11-27 | 44
| SYS; TS CLOGO | ? | 44
| RJL; LOGO BIN | 1973-03-06 | 49

**Comment by Alexey-Slyusar** [comment]
Thank you for summarising, Lars!
Are the binaries on its/vault resource?

Am I right that we have source code for the LOGO 49?

вт, 5 февр. 2019 г. в 14:46, Lars Brinkhoff <notifications@GitHub.com>:

**Comment by larsbrinkhoff** [comment]
Since the two SYSBIN; CLOGO BIN files have identical names and directories, there is only one in its-vault.

**Comment by larsbrinkhoff** [comment]
Hello @Alexey-Slyusar,

I have now pushed some files to this pull request.  Can you test them a little bit to verify that it's OK to replace our previous CLOGO with this LOGO 49?

**Comment by Alexey-Slyusar** [comment]
I'll test things out tonight. Thank you, Lars!

вт, 5 февр. 2019 г. в 17:21, Lars Brinkhoff <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
Oh, LOGIN command is something new in repertoire. :-) Thanks.

вт, 5 февр. 2019 г. в 17:44, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
The full list of commands is in LOGOPS, starting at label CMPT.

**Comment by eswenson1** [comment]
@Alexey-Slyusar Done. RJL directory loaded on ES. Have fun.

**Comment by Alexey-Slyusar** [comment]
Eric, thank you very much!

вт, 5 февр. 2019 г. в 18:58, Eric Swenson <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
Lars, It seems that LOGO 49 is source file rather a binary one. Which file
shold I run in order to get CLOGO prompt?


вт, 5 февр. 2019 г. в 19:04, Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by eswenson1** [comment]
See the changes in the TCL build file in this PR for steps to build the source.

**Comment by Alexey-Slyusar** [comment]
Eric, thanks for the hint!

вт, 5 февр. 2019 г. в 19:37, Eric Swenson <notifications@github.com>:

**Comment by Alexey-Slyusar** [comment]
It seems I've got it running on ES!


вт, 5 февр. 2019 г. в 19:39, Alexey Slyusar <aleksey.slyusar@gmail.com>:

**Comment by Alexey-Slyusar** [comment]
:-)
Pretty far from being ITS hacker yet. But there is a place for a logo
enthusiast on ITS too.

And many thanks to true ITS hackers like Eric and you for make ITS
accessible even for hobbyists.

Exploring LOGO 49 :-)

вт, 5 февр. 2019 г. в 20:19, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
The BIGTURTLE and SMALLTURTLE may be the yellow big turtle, and the smaller new turtle.

**Comment by Alexey-Slyusar** [comment]
Interesting. Thanks!

ср, 6 февр. 2019 г. в 19:52, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
Files do work.  I took an old file LOGO; NBAM FILES, logged in as NBAM, and I got this file list:

```
?LIST FILES
DEMO    PLAY    21:46:33        23 MAY 1971
FANCY   FILE    12:07:53        10 JUL 1971
TUNE    BUILD   16:12:55        13 JUL 1971
ROUNDS  ALL     11:56:27        02 JAN 1971
CHIP    BAM     14:13:41        03 MAY 1971
GUEST   SUITE   18:12:50        22 JUN 1971
QUEER   BLOCKS  20:52:57        27 FEB 1972
TUNE    BUILD1  16:50:21        16 JUL 1971
NEW     MUSIC1  12:28:35        09 JUL 1971
NEW     MUSIC   15:13:51        13 JUL 1971
ROWE    TWONE   15:29:40        28 APR 1971
DON     DON     13:59:12        25 MAY 1971
MASH    MUSIC   11:56:41        14 JUL 1972
RANDOM  TUNE    14:12:08        15 JUN 1971
TUNE    BUILDER 12:24:32        18 JUL 1972
STEVE   LORCH   14:27:43        23 MAR 1971
SWCH    J       12:10:50        20 APR 1971

**Comment by Alexey-Slyusar** [comment]
Hi Lars!
I have some free time on weekend so I wand to do some CLOGO work.
Could you please point me where I can get LOGO; NBAM file.
Thank you!

**Comment by eswenson1** [comment]
https://s3.amazonaws.com/eswenson-its/public/nbam.files

**Comment by Alexey-Slyusar** [comment]
Eric, thank you!

I am building KL version of ITS.
Hope, if everything goes well with the building process, I will be able to try CLOGO on KL.

**Comment by Alexey-Slyusar** [comment]
I did slightly differently than Lars:

1. Logged into ITS as `alexey` as usual;
2. Ran `?LOGIN NBAM` from CLOGO prompt.
And here the `LIST FILES` printing in my case:
```
DEMO	PLAY	15:08:49	23 FEB 1971
NEW	MUSIC	10:07:17	09 FEB 1971
TUNE	BUILD	12:18:19	05 MAR 1971
ROUNDS	ALL	11:56:27	02 JAN 1971
DIRECTORY	INFO	12:57:43	02 JAN 1971
MINI	MUSIC	13:28:12	26 OCT 1972
QUEER	BLOCKS	20:52:57	27 FEB 1972
TUNE	BUILD1	14:32:37	06 FEB 1971
CRITIC	VEH	15:12:13	08 MAY 1972
RANDOM	VEH	11:11:32	17 JUL 1972
CHIP	BAM	11:02:44	13 NOV 1972
DOUG	MAC	13:09:32	01 FEB 1971
ROWE	TWONE	15:20:48	19 FEB 1971
MASH	MUSIC	11:56:41	14 JUL 1972
HARM	PLAY	16:05:24	05 JAN 1971
TUNE	BUILDER 12:24:32	18 JUL 1972
VARI	STAR	19:03:15	14 FEB 1971
DOUG	TUNE	11:52:20	13 FEB 1971
STEVE	LORCH	23:15:28	09 JAN 1971
MARK	TUNE	14:35:19	08 MAR 1971
FILE	ALEXEY	11:33:14	26 OCT 1971
LOGO	DUMP	12:44:14	26 OCT 1971
```
I noticed that a few files are different from what Lars had, particularly interesting these three:
```
DIRECTORY	INFO	12:57:43	02 JAN 1971
LOGO	DUMP	12:44:14	26 OCT 1971
FILE	ALEXEY	11:33:14	26 OCT 1971
```
All of these seem to be kind of special entries, and latter two automatically generated by CLOGO.

**Comment by Alexey-Slyusar** [comment]
It is obvious also, that the single `NBAM FILES` was used by several children to save their procedures. But I still cannot figure out how to create such a master file like `NBAM FILES` one.

**Comment by Alexey-Slyusar** [comment]
`WRITE` saves all workspace procedures into user directory as a plain text file.
`READ` reads procedures from the plain text file.

But the plain text file created by `WRITE` is not master file like 'NBAM FILES`.
The plain text file doesn't have internal structure like `NBAM FILES` one.

**Comment by Alexey-Slyusar** [comment]
`GET` command loads procedures from an Entry entry into workspace.
e.g. `?GET MARK TUNE`
`SAVE` saves all workspace procedures as an Entry in `NBAM FILES` file.
e.g. `?SAVE MARK TUNE`

**Comment by larsbrinkhoff** [comment]
Thanks for testing this!

**Comment by Alexey-Slyusar** [comment]
`DELETE` deletes an Enty from a Logo directory file. 
E.g. `?DELETE MARK TUNE`

By Logo directory file I mean the master file like `NBAM FILES`. 
An Entry is a "internal file" inside a Logo directory one, like `MARK TUNE` stored inside 'NBAM FILES`.

**Comment by Alexey-Slyusar** [comment]
It seems that a new LOGO directory file (or master file) like `NBAM FILES` cannot be created using LOGO binary. 

A possible reason for this is that LOGO was intended to use by children and so there has to be a protection mechanism to prevent deleting files by accident.

It is very likely that there was separate binary to create the LOGO directory file. 
Something like `ts fhack` Lars mentioned at #1018.

**Comment by Alexey-Slyusar** [comment]
I `itstar`ed fhack and loading it into my local KL.
I am going to test it with 'NBAM FILES'

**Comment by Alexey-Slyusar** [comment]
`FHACK` works with `NBAM FILES`!

Here is `FHACK` output:
```
:FHACK

*U
LOGO USER=NBAM

*L
LOGO    DUMP    22:47:25        31 OCT 1971
ALEXEY  FILES   21:14:13        26 OCT 1971
TUNE    BUILD   12:18:19        05 MAR 1971
DIRECTORY       INFO    12:57:43        02 JAN 1971
MINI    MUSIC   13:28:12        26 OCT 1972
QUEER   BLOCKS  20:52:57        27 FEB 1972
TUNE    BUILD1  14:32:37        06 FEB 1971
CRITIC  VEH     15:12:13        08 MAY 1972
RANDOM  VEH     11:11:32        17 JUL 1972
CHIP    BAM     11:02:44        13 NOV 1972
DOUG    MAC     13:09:32        01 FEB 1971
ROWE    TWONE   15:20:48        19 FEB 1971
MASH    MUSIC   11:56:41        14 JUL 1972
HARM    PLAY    16:05:24        05 JAN 1971
TUNE    BUILDER 12:24:32        18 JUL 1972
VARI    STAR    19:03:15        14 FEB 1971
DOUG    TUNE    11:52:20        13 FEB 1971
STEVE   LORCH   23:15:28        09 JAN 1971
MARK    TUNE    14:35:19        08 MAR 1971

*
```

**Comment by Alexey-Slyusar** [comment]
But I still cannot create a new Logo directory file though.

It is not clear for me, how `FHACK` option `I-INITIALIZE USER` works:
```
:FHACK

*I?
*
```
I doesn't see any effect after executing `FHACK` with `I` parameter.

**Comment by larsbrinkhoff** [comment]
Thank you, this is very interesting.  I would logically seem like I (initialize) *should* be able to create a new empty LOGO file.  Maybe it just needs the right conditions to work.

**Comment by larsbrinkhoff** [comment]
I see INIT doesn't work unless MUNGE is in effect.  Try typing "M" and then the secret key "%".  Now maybe "I" works.

**Comment by Alexey-Slyusar** [comment]
Yeah!!!

**Comment by Alexey-Slyusar** [comment]
Lars, this spell works! Thank you!!!

**Comment by Alexey-Slyusar** [comment]
Here is `FHACK` session:
```
*:FHACK 

*M%
*I
LOGO USER=SEYMOUR

*Q   
:LISTF

KL   LOGO
FREE BLOCKS #0=10250 #1=16589 #2=2918
  1   NBAM   FILES  24 ! 10/31/2019 22:47:24
  1   SEYMOU FILES  1 ! 11/2/2019 21:46:06
*
```

**Comment by larsbrinkhoff** [comment]
Wow, that's great!  I didn't expect it to work right away.  Thanks for testing this!

**Comment by Alexey-Slyusar** [comment]
A pleasure :)

**Pull request merged**
