### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jordanhubbard**
install_macosx function has been renamed to install_osx

### CODE REVIEW

**Comment by eswenson1** [comment]
Why the rename to install_osx? OS/X is an old/obsolete name for the Mac operating system. The correct name for the OS is now macOS (spelled that way). 

I’d recommend “install_macOS”.

**Comment by jordanhubbard** [comment]
Because that is the name of the function in the shell script - I assumed someone changed the name in the script without changing the documentation.  As long as both are in sync, it’s fine.

**Comment by ams** [comment]
> I’d recommend “install_macOS”.

Lower case please... since this is something a user is going to type.

**Comment by jordanhubbard** [comment]
I didn’t mean to start a naming war, particularly since I’m a little too close to macOS to be opinionated about it, I am merely trying to align README.md and build/dependencies.sh since they are currently out of sync.

FWIW, the official Apple brand is “macOS” - capital O, capital S.  As one of the creators of macOS, however, I don’t want to dictate how others choose to spell it.

- Jordan

**Comment by jordanhubbard** [comment]
FWIW, if we're "voting" on this, I would suggest a single change to name it macOS in both places.  If everyone can align on that, I'll submit two updated PRs that commits *just* the renaming change.

**Comment by ams** [comment]
Typing capital letters for one system is annoying though.  Should it now be Linux? What about

**Comment by larsbrinkhoff** [comment]
This wasn't really meant to be a user facing name.  `dependencies.sh` was just a helper for the continuous integration scripts.  But now the cat's out of the bag, and maybe that's just as well.

The name is part of an identifier, which ends up being called inside a shell script.  Stylistically, I think lower case works better.  Maybe this design is questionable, and the script could just as well take a name as an argument, and act accordingly.  In that case it could even be case insensitive.  If someone wants to do a minor rewrite of the script, give it a go.

**Review by larsbrinkhoff — APPROVED** [review]

**Pull request merged**
