### PR TITLE
Added PRUFD.

### LINKED ISSUE #101: PRUFD - list files on disk volume
SYS1; TS PRUFD
SYSEN2; PRUFD 10

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #101.  Includes patch to replace LPT device with TTY device (version in PI must have been patched).

### CODE REVIEW

**Comment by eswenson1** [comment]
Ok. I'll redo. However, you realize it won't run without the patch, right?

**Comment by larsbrinkhoff** [comment]
You can have two commits in this pull request.  The first with unchanged files, the second with the fix.  That way, it will work when the pull request is merged.

**Comment by eswenson1** [comment]
Ok. Will do.

-- Eric

**Comment by eswenson1** [comment]
There are now two commits. The first just builds PRUFD from sources. The second patches it to use TTY: rather than LPT:  I entered #195 for the second commit.  #101 is for the first commit.

**Comment by larsbrinkhoff** [comment]
The PRUFD source file seems to be broken.  See the end:  
https://github.com/PDP-10/its/blob/master/src/sysen2/prufd.10#L404

**Pull request merged**
