### PR TITLE
Fix doc link to midas.26

### PR DESCRIPTION
**Pull request by codesmythe**
Previously pointing to midas.25, which doesn't exist in the repo.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you.  Too bad we can't link to "midas.>".

**Comment by larsbrinkhoff** [comment]
@codesmythe, the CI build was held up a bit because you submitted a pull request from a fork.  If you have more coming, you are welcome to make a branch in the main repo.

**Comment by codesmythe** [comment]
Thanks for the merge.

I'm working on a re-implementation of Conroy's PDP-10X FPGA board. For debug purposes I needed to reassemble his ROM, and was checking out the MIDAS docs here.  I don't expect to have any more changes any time soon.

**Comment by larsbrinkhoff** [comment]
Maybe you should talk to @gerryk as he is also working on Conroy's FPGA stuff.

**Pull request merged**
