### PR TITLE
Lisp display slave

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYS; ATSIGN 10SLAV  
SYS; ATSIGN 6SLAVE  
SYSEN2; LD10 61  
SYSENG; FDITS 43  
L; SLAVE 8 (in AR1)

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Some outstanding questions:

- Where to put the GT40 binary for LD10?
- What is FDITS?
- How does it differ fromthe GT40 LD10?
- Who uses it?
- Where should the binary be?

**Comment by larsbrinkhoff** [comment]
"GT40 Utility Programs and the LISP Display Slave"  
https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/AI_WP_059.pdf

**Comment by larsbrinkhoff** [comment]
Ah, the working paper answers some questions: SYENG; FDITS > is .INSRTed when assembling the GT40 slave.

**Comment by eswenson1** [comment]
@larsbrinkhoff  how would I identify lisp code that uses this stuff?  What would that code be doing that would identify itself?

**Comment by larsbrinkhoff** [comment]
Basically anything that makes calls to `(DIS...`  I made the obvious checks already.  I just asked in case you'd know already.

**Comment by larsbrinkhoff** [comment]
We don't have anything installed at the moment, but

- SHRDLU makes a call to DISINI
- LLOGO makes calls to DISINI, DISCOURSE, DISFLUSH, DISCREATE, etc...

**Pull request merged**
