### PR TITLE
Deploy images to kostersitz.com FTP site.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Since the new hactrn.org machine is not yet fully operational, @oilcan-productions offered to host images on kostersitz.com.

A new `FTP_SECRET` secret was created to hold the FTP password.  To do this, or update it, click *Settings*, then *Environments* in the left bar, then *Deploy*, then scroll down to *Environment secrets*.

I haven't been able to test this manually yet since my login credentials wasn't accepted.

### CODE REVIEW

**Comment by oilcan-productions** [comment]
I have reset the FTP Password, and also reset the FTP_SECRET. I tested the login with MacOS FTP client and from Windows as well and it seems to work manually. 
@larsbrinkhoff  can you try the deploy again? the FTP user is hactrn@kostersitz.com
FTP hactrn.kostersitz.com
User: hactrn@kostersitz.com
Password: <secret>

**Comment by oilcan-productions** [comment]
also updated deploy.sh to deploy to the mirror
#2166

**Comment by larsbrinkhoff** [comment]
@oilcan-productions I have updated this pull request with your new information.

**Review by oilcan-productions — APPROVED** [review]

**Comment by oilcan-productions** [comment]
LGTM

**Comment by larsbrinkhoff** [comment]
Ok, let's hope this works!  Deploy only happens when it goes to the master branch, so we'll have to test and see.

**Pull request merged**
