### PR TITLE
Add Macsyma

### PR DESCRIPTION
**Pull request by eswenson1**
This PR adds the sources and build instructions to build Macsyma.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Looks like you need to rebase this on origin/master, and fix conflicts.

**Comment by larsbrinkhoff** [comment]
There are some things that can trip you up:

- rebasing on master, when master isn't up to date with origin/master.
- rebasing on origin/master, but forgetting to first fetch from origin.

To get it right, you may have to

    git fetch
    git checkout master
    git merge --ff-only origin/master
    git checkout feature/branch
    git rebase master

After this, master is up to date with origin/master, and feature/branch is rebased on top of master.

**Comment by larsbrinkhoff** [comment]
And don't forget, no matter how bad the pull request is messed up, you can always go back to fix it and force push.

**Comment by eswenson1** [comment]
Thanks. I definitely didn’t use —ff-only. And I didn’t merge Master into my branch. I rebased my branch with origin/Master. I’m pretty sure I did the fetch first because I did get all the recent changes into my branch before pushing.

**Comment by larsbrinkhoff** [comment]
Maybe add a comment why build_macsyma_portion is called so many times in a row?

**Comment by eswenson1** [comment]
I intended to write a descriptive comment before those to explain it.  Thanks for the reminder.  I'll add something when I debug/fix/commit/push a fix for the arithmetic overflow.

**Comment by eswenson1** [comment]
Well, it passed on SIMH and failed on KLH10. I have no idea why it failed on KLH10 (it works fine on my machine). It got a timeout, but I don't see how it could have -- unless complr just hung.  It is supposed to begin compiling items on the TODO list until either a) it gets a breakpoint or b) it is done.  Nothing happened -- no output at all until expect timed out.  

Is there any way, without making a change to have Travis "try again"?

**Comment by larsbrinkhoff** [comment]
Yes.  You can cancel and restart builds.  Well, I can; I don't know about others.

Click on the status symbol (cross, dot, check mark), or "Details".  You will see a page from Travis.  Near the upper right is "Restart build" (or "Cancel build" if it's running).

**Comment by larsbrinkhoff** [comment]
The default timeout is 100 seconds.  Maybe it actually took longer than that?

**Comment by eswenson1** [comment]
But I think it responds with some output almost immediately.  I compared the output of the KLH10 build with the output of the SIMH build, and I saw the expected output in the SIMH build.  Also, this works perfectly fine on my machine with the KLH10 build.  With the Travis build, it acts like KLH10 hung (or the compiler did).

**Comment by eswenson1** [comment]
Ah, i noticed that while I was logged in on GitHub, I wasn't on Travis -- that's why I couldn't see those controls.

**Comment by eswenson1** [comment]
Oh for goodness sakes!  Now the build failed because it went longer than 50 minutes on SIMS.  It passed on the other two platforms.  How do you increase the time limit for a Travis build?

**Comment by larsbrinkhoff** [comment]
I suppose we'll have to disable building for the KA10 simulator for now.  @rcornwell, any ideas?

**Comment by larsbrinkhoff** [comment]
Pushed a commit to this branch to disable building with "sims".

**Comment by ams** [comment]
Would it make sense to split up the build, and reuse a previous build artifact?

**Comment by eswenson1** [comment]
No. I’m pretty sure I did a “fit commit —amend” though.

**Comment by eswenson1** [comment]
I like the idea of splitting the build. When I test out new changes, I do that myself — with a second expect script with all the Macsyma changes, for example, that boots an emulator build with our original Makefile and expect script and then applies the new changes. I’m not sure, however, how we’d organize the Travis config though such that the right build would get executed. Any ideas, Lars?

**Comment by eswenson1** [comment]
Lars, do you mind doing the Git magic to combine my two commits? I’m not at a computer for a while, and don’t think I can do that from my phone.

**Comment by larsbrinkhoff** [comment]
Sure, I quite like git magic. :-)  Pushed updated commits.

**Comment by eswenson1** [comment]
I assume you just did a "git rebase --interactive" and picked the two commits?  (I know I've done this once before, but where I work, we've never cared about having single commits to represent fixes before, so we don't do this merging of commits ever).

**Comment by larsbrinkhoff** [comment]
`git rebase -i master`, yes.  Then changed the second commit to "fixup" the first.

**Comment by eswenson1** [comment]
@larsbrinkhoff Thanks for fixing that.

**Comment by larsbrinkhoff** [comment]
No problem!

**Comment by larsbrinkhoff** [comment]
I was thinking that some bit applications could be split off: Emacs (maybe add TECO to this), Maclisp, Macsyma.

In Travis it's not quite natural to use build artifacts from one repo in another repo.  But I suppose they could be wgetted.. wgotten... downloaded from somewhere.

**Comment by larsbrinkhoff** [comment]
Approved and build passed.  @eswenson1, I'll let you do the honours.

**Pull request merged**
