### PR TITLE
Information about the XGP.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
XGP WRITES taken from SRI-NIC \<src.canon.mit>.

### CODE REVIEW

**Comment by atsampson-abertay** [comment]
I've seen several versions of this writeup with minor variations:

- MC/AI: SYSDOC; XGP WRITUP (1974-07-22)
- SRI-NIC: <src.canon.mit>mit.xgp-writup (??) - same as XGP WRITUP with commands 51/52 added
- SRI-NIC: <src.canon.mit>mit.xgp-writes (1977-09-11) - reworded version of XGP WRITUP
- SAIL: [XGPSER[S,SYS]](https://github.com/PDP-10/waits/blob/master/sys/J17-1974/xgpser.MAC#L1295) (appeared in version 63, 1977-12-17)
- MC/AI: INFO; XGP 24 (1980-04-18) - same as SRI-NIC: <src.canon.mit>xgp.info - Info-ised and reworded lightly from XGP WRITUP, with commands 51/52/53 added

I suspect this is an extract from the XGP manual or something like that.

Maybe we should just check that the copy in INFO; XGP > is up to date and keep that?

**Comment by atsampson** [comment]
I've seen several versions of this writeup with minor variations:

- MC/AI: SYSDOC; XGP WRITUP (1974-07-22)
- SRI-NIC: <src.canon.mit>mit.xgp-writup (??) - same as XGP WRITUP with commands 51/52 added
- SRI-NIC: <src.canon.mit>mit.xgp-writes (1977-09-11) - reworded version of XGP WRITUP
- SAIL: [XGPSER[S,SYS]](https://github.com/PDP-10/waits/blob/master/sys/J17-1974/xgpser.MAC#L1295) (appeared in version 63, 1977-12-17)
- MC/AI: INFO; XGP 24 (1980-04-18) - same as SRI-NIC: <src.canon.mit>xgp.info - Info-ised and reworded lightly from XGP WRITUP, with commands 51/52/53 added

I suspect this is an extract from the XGP manual or something like that.

Maybe we should just check that the copy in INFO; XGP > is up to date and keep that?

**Comment by larsbrinkhoff** [comment]
I'm a little weary of removing things from SYSDOC, but I suppose in this case it makes sense.

We have a similar merging pending for MIDAS: #1005.

**Comment by larsbrinkhoff** [comment]
I suggest to add SYSDOC; XGP WRITUP as is, then follow up with a commit that rewrites the file to say the information is now in INFO; XGP >.

**Comment by larsbrinkhoff** [comment]
@eswenson1, your thoughts?

**Comment by eswenson1** [comment]
My thoughts:  Do what you said.  Commit original XGP WRITUP, then have another commit that adds a line to the top of that file saying where the newer info lives, and commit that file too.

**Comment by larsbrinkhoff** [comment]
CC @sebras, this may have useful into.

**Pull request merged**
