### PR TITLE
Add fix to ITS to ensure it doesn't hang waiting forever for TUTs to be written to disk.

### PR DESCRIPTION
**Pull request by eswenson1**
Fix guarantees that TUTs will get written out if doing so was skipped due to QACTIM being non-positive more than 10 times.

Addresses #2220.

### CODE REVIEW

**Comment by eswenson1** [comment]
@larsbrinkhoff I'm not suggesting we actually merge this yet.  I'd like @desaster to try it out to see if it resolves their shutdown issue.  We can also discuss the fix here to see if we want to change it.

**Comment by desaster** [comment]
I think I managed to install this for testing. So far after a few tries my system has successfully shut down every time:

```
SHUTDOWN COMPLETE
PI LEVEL 7 BUGDDT.  TYPE <ALTMODE>P TO CONTINUE.
YOU ARE NOW IN DDT.
BUGPC/   CAI COFFI4+1   $Q-2/   JRST COFFI7
```

But I'll keep testing more as I keep exploring ITS. I'll also keep testing the old build to see that the issue is still there.

The way I installed it, hopefully actually applying it correctly:

* Copied the file to `FIX; DISK 1228` using the [itstar instructions](https://github.com/PDP-10/its/blob/master/doc/DUMP-itstar.md)
* Copied it to `SYSTEM` with `:copy fix; disk,system; disk`
* Assembled ITS using the [assembling instructions](https://github.com/PDP-10/its/blob/master/doc/NITS.md), skipping disk re-configuration and skipping updating (N)SALV
* Booted the new ITS from DSKDMP as instructed, and later copied it to `DSK0:.; @ ITS`

**Comment by eswenson1** [comment]
@desaster Seems to me like you did it correctly.  Glad it is working for you.  Keep using that ITS (I'm doing the same) so we get some experience with it.  Please let me know if you see the shutdown hang again (when using the fix).  Thanks very much for trying it out.

**Comment by larsbrinkhoff** [comment]
I have a vague feeling this has become more prominent with later KA10 emulator updates.  I will try to look into *why* QACTIM isn't behaving as expected.

**Review by larsbrinkhoff — CHANGES_REQUESTED** [review]
I'm reviewing this as "request changes" to be explicit about waiting to merge something.

**Comment by eswenson1** [comment]
Updated this branch to use the "option 2" fix -- we simply force writing of TUTs and disk buffers on slow clock if we are shutting down.

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
All ready to merge now.  Thanks so much for working on this, Eric!

**Pull request merged**
