### PR TITLE
Builds all LISP; * FASL files that are on autoload properties 

### LINKED ISSUE #1271: LISP; STRING FASL
This, and possibly other FASL files in LISP; are not built from source. These should be all built from source.  source for LISP; STRING FASL is NILCOM; STRING 186.

### PR DESCRIPTION
**Pull request by eswenson1**
Builds all LISP; * FASL files that are on autoload properties when the lisp interpreter is first booted.

Redumps lisp compiler with updated FASL files built from source.

Resolves #1271, #1272, #1275, #1276, and #1277.

### CODE REVIEW

**Comment by eswenson1** [comment]
@larsbrinkhoff I have one commit here and multiple tickets are being resolved. It is too difficult to extricate all these into separate commits. There are a lot of interdependencies.  For example, some sources can't be compiled until issues are fixed.  So I had to fix all the issues in order to finish the task of compiling all the fasl files used by initial autoload properties.  

And while I could have separated out the compiler redump from this in a separate commit, I didn't because I didn't want to leave a possible build (of the first commit) with a compiler that had inconsistencies with respect to what other programs would see if they used LISP; fasl files.  So now we have a consistent library and compiler.  Well almost.

I'm going to do more reorganization in another commit/PR and will likely want to recompile the compiler before redumping it out.  (First compile uses the runtime from the binaries on the sources tape, second compile uses the recompiled runtime).  To do this *really* write, there should be a third compile that uses the previously-compiled compiler, but I don't really think that is necessary.

**Comment by eswenson1** [comment]
@larsbrinkhoff  what do we do about this? the klh10 build failed to produce any output within 10m during the dump.   This builds fine and runs fine for me.

**Comment by larsbrinkhoff** [comment]
I restarted the KLH10 build.  I think it's an intermittent failure.

**Comment by larsbrinkhoff** [comment]
Good to go now.

**Pull request merged**
