### PR TITLE
Recreated sources no longer needed

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
@eswenson1 We recreated a few source files, but this is the only replacement as of now, right?

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
STINK 201 in #45 is identical to our recreated version.  It was just a one-character change from version 200.

**Comment by larsbrinkhoff** [comment]
SYSENG; DRAGON 63 isn't a replacement for our SYSENG; DRAGON 206.

**Comment by larsbrinkhoff** [comment]
MRC; TEN50 22 is mostly cosmetic changes compared to our TEN50 1.  Not sure which to prefer.

**Comment by eswenson1** [comment]
Yeah, the dragon source I recreated assembles to an identical binary as we got from PI ITS distribution. The most recent DRAGON source we recovered is very different and produces an entirely different binary.

**Comment by larsbrinkhoff** [comment]
I added MRC; TEN50 22 too.  I think it's an improvement over TEN50 1.

**Pull request merged**
