### PR TITLE
GT - generate tables for C compiler

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This program reads a machine description and writes tables to a C file.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Admittedly, this isn't very useful without the rest of the compiler.

**Comment by larsbrinkhoff** [comment]
PCC20 is this: http//github.com/PDP-10/PCC20

There is something called PCC20 from Utah, which has been described as a port of Steve Johnson's Unix PCC from Bell labs.  I haven't found this.

The code in the PCC20 repository clearly descended from Snyder's compiler, also called C10 or C20.  Files mention Alan Snyder AS@DM and Eliot Moss EBM@XX.  Comments say "TOPS-20 Portable C Compiler".  I don't see Utah mentioned anywyere.

I asked Alan Snyder about this, but he doesn't remember.  I asked Steve Johnson, and he explained he was working on the Unix PCC, but left the Lab on sabbatical for a year.  During this time, Snyder worked at the lab and rewrote parts of PCC.

I'm not sure if there is one PCC20, or two: one that grew from Snyder's compiler, and another from Johnson's.  And if so, to which degree they met and cross pollinated.

@philbudne, do you have anything to add to this?

**Comment by larsbrinkhoff** [comment]
I pushed some more code to the PCC20 repository (which may be increasinly misnamed).  There are now three directories: its, sail, and tops20.  Clearly they are all closely related; I'm using the sail and tops20 files to patch up the ITS compiler.

**Comment by philbudne** [comment]
Not sure I was aware that Snyder had worked on Johnson's PCC.

Alas Jay Lepreau is no longer with us to ask about PCC-20 source...

Found this https://minnie.tuhs.org//pipermail/tuhs/2017-September/010666.html

 Nelson H. F. Beebe beebe at math.utah.edu 

 I worked on, and co-managed, TOPS-20 on DECsystem 20/40 and 20/60
 systems with the PDP-10 KL-10 CPU from September 1978 to 31 October
 1990, when our 20/60 was retired.  (A second 20/60 on our campus in
 the Department of Computer Science had been retired a year or two
 earlier).

 There were two C compilers on the system, Ken Harrenstien's kcc, and
 Steve Johnson's pcc, the latter ported to TOPS-20 by my late friend
 Jay Lepreau (1952--2008).

 pcc was a straightforward port intended to make C programming, and
 porting of C software, fairly easy on the PDP-10, but without
 addressing many of the architectural features of that CPU.

**Comment by larsbrinkhoff** [comment]
I'll upload PCC-20 shortly.

**Comment by larsbrinkhoff** [comment]
The major evidence other than files named PCC20, is the file pcc20.hlp which says:

```
pcc info (2/82 -- cjt@mit-xx)

This implementation of C for TOPS-20 is based on the Portable C Compiler
written by Steve Johnson of Bell Labs.
```

And cc.doc:

```
  The C compiler described here is based on the Portable C Compiler written  by
S. C.  Johnson  of  Bell  Labs.  The PDP-10 code generator was written by Eliot
Moss and Chris Terman of the MIT Lab for Computer Science, and John  Wroclawski
of the MIT Research Lab of Electronics.
```

But looking at the files, they all are close related to the ITS compiler by Snyder.  Among other things, I don't think GT and STINKR were ever used with Johnson's PCC.

**Comment by larsbrinkhoff** [comment]
@philbudne, Utah's PCC20 is now here: http://github.com/PDP-10/utah-pcc20.  It's a close match to pcc as found in V7.

Johnson wrote in "C and the AT&T Unix Port—A Personal History":

> In early 1973, I went on a 9-month sabbatical to the University of Waterloo.  When I returned, B was dead—long live C.  An MIT coop student named Al Snyder had rewritten Yacc from B to C, and used it as the basis for a C compiler that would run on both the Honeywell and the PDP-11.  It had a Yacc grammar for the language.  Neither implementation was especially compelling—it took four passes to run on the PDP-11, so it was horribly slow, and the code generator on the Honeywell had numerous bugs.  But it was a very impressive few months work.
> 
> When I returned from Canada, it was strongly suggested that I take this over—Al was returning to school.  Over the course of the next six months, I replaced nearly everything but portions of the grammar, and it became the first Portable C compiler.

**Comment by larsbrinkhoff** [comment]
I asked, and CJT says indeed MIT wrote a PDP-10 code generator for Johnson's PCC.  So it looks like the TOPS-20 PCC20 have some files from that project, but the compiler implementation is from Snyder's compiler.

**Comment by larsbrinkhoff** [comment]
\<C.NEW.LIB>C20MEM.C says

> This code was written by Alan Snyder and Eliot B. Moss. Modified for the Standard I/O Library by John Wroclawski

So that's a clear connection between Snyder's work and the C library used with C20.

**Comment by larsbrinkhoff** [comment]
Three files in \<C.PCC20LIB> check for the preprocessor symbol `snyder_compiler`.  If defined, they will get varargs from increasing addresses.  Otherwise, decreasing addresses.

So this looks like evidence the library was used with two different compilers.

**Comment by philbudne** [comment]
> So this looks like evidence the library was used with two different compilers.

At least on two different architectures!  PDP-10 stacks grow "up"
towards higher addresses (where many/most later arhitectures have them
grown "down") and I'd be SHOCKED (or at least VERY VERY surprised(*))
to see a PDP-10 C compiler that eschewed {PUSH.POP}[J] to "correct"
this!


(*) It would be a RISCy thing to do!  BTW, I worked on Alan Kotok's
"SAFE" RISC project, which Cuttler stole and renamed PRISM (along with
breaking all the datatype names from 2,4,8 to W,L,Q), which is
referenced in the (possibly apocryphal and likely backcronym) "AXP"
(Almost eXactly PRISM).

**Comment by larsbrinkhoff** [comment]
Good point.  I was thinking `#ifndef snyder_compiler` would mean another PDP-10 compiler, e.g. an MIT PCC port.  But it could be another architecture.

When I worked on the GCC port, for a while we discussed an option to use JSP for subroutine calls, much like modern RISCs do.

**Pull request merged**
