### PR TITLE
6502 cross assembler in Maclisp

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Written by @leighklotz.

KLOTZ; ALL 4  
KLOTZ; TOKENZ 59  
KLOTZ; ARMACS 20  
KLOTZ; PASS1 65  
KLOTZ; EVAL 66  
KLOTZ; MATCH 20  
KLOTZ; DECPOP 45  
KLOTZ; 6502 54  
KLOTZ; DEFDEF 9  
KLOTZ; COMMAC 29  
KLOTZ; ASSEM FILES  
KLOTZ; ASSEM IDEAS  
KLOTZ; DEC PSEUDO

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I haven't been able to test this fully, but I propose to merge this now rather than hang around forever.

**Comment by BobKerns** [comment]
So...a cross-assembler running on a PDP-10 emulator to assemble code that will presumably run on a 6502 emulator?  How very retro!

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
@BobKerns, presumably there are still plenty of working 6502 machines.  But yes, the testing I have done has always been emulators so far.

This kind of scenario often makes me think of a future where everything we have now run on at least one layer of emulation.  I strive to make the emulators simple to make it easier for future generations.  Hi guys, I hope you're having fun!

**Comment by BobKerns** [comment]
> This kind of scenario often makes me think of a future where everything we have now run on at least one layer of emulation.

Kind of a return to the microcode era!

**Pull request merged**
