### PR TITLE
Fixed typo in limerick

### PR DESCRIPTION
**Pull request by mettacrawler**
"form" vs. "from"

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you.  You can merge this in GitHub when the CI builds have finished.

**Comment by larsbrinkhoff** [comment]
It seems @mettacrawler doesn't want to merge this himself, so I'll do it now.

**Comment by mettacrawler** [comment]
Sorry I didn't know it was my turn.

**Comment by larsbrinkhoff** [comment]
No problem!

**Pull request merged**
