### PR TITLE
ITS Muddle 54 order.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
```
MUDDLE F/SUBRS:         (for MUDDLE 55)         PDL/SWG 3/8/79

        The following is a very brief description of all the
primitives currently available in MDL.
```

I'm inviting everyone to provide evidence, opinions, and rumours about the original location of this file.  In particular @atsampson, @36bit.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Actually, a complete list of Muddle directories and their intended use.

For example, from the MAPS3 files:

- MUDDLE - locks, FBIN, NBIN files.
- MUDRST - Binary save and patch files.
- MUDSAV - Executable TS files, and... ?
- MUDBUG
- MUDMAN - documentation.
- MUDTMP
- MUDSYS - Interpreter & runtime sources.
- COMBAT - Batch compiler plan files.

**Comment by larsbrinkhoff** [comment]
From MUDSYS files:

- MUDSAV - Main data base rfiles.
- MUDTMP - Directory of update files.
- MUDSUB - For demons and the like.

**Comment by larsbrinkhoff** [comment]
Already added in #883.

**Comment by 36bit** [comment]
I'm going to guess that muddle.order.1 probably lived in MUDMAN, only because it seems to be documentation and Dave Lebling's book "The Muddle Programming Environment" has that:

> Most of the documentation in this manual is from published and
> unpublished memos of the Programming Technology Division of the M.I.T.
> Laboratory for Computer Science. As a general rule, updates and
> revisions to this and other PTD documents concerning Muddle are
> available online in the directory "`MUDMAN`" at MIT-DMS

The exact location of the MUDMAN directory on DM is never mentioned though.

**Comment by larsbrinkhoff** [comment]
Thanks, I agree.  In ITS there's only one level of directories so the location is quite certain.

**Comment by 36bit** [comment]
MUDTMP was used for updating the library. See section 4.2.1 about the demon in https://github.com/PDP-10/its/files/2581151/LCSTR294Lebling.pdf

Also, the FIXUP and SAV files were also (section 6.3 of the same book)

I'll have to look into more of these later.

**Comment by larsbrinkhoff** [comment]
From the same document:

> The standard library is named `LIBMUD` and lives on a directory named `LIBMUD` (on ITS) or `MDLLIB` (on Tenex/Tops-20)

**Comment by larsbrinkhoff** [comment]
From DUMP:

- %SYS - DMCG memos.
- .BATCH
- COMDAT
- COMMUD
- COMPIL
- NCOMPI
- COMSAV

**Pull request closed without merging**
