### PR TITLE
Update deploy-ftp.sh

### PR DESCRIPTION
**Pull request by oilcan-productions**
changing hostname hactrn.kostersitz.com

### CODE REVIEW

**Comment by oilcan-productions** [comment]
Updated FTP_SECRET with the new password. Once this is merged we should be able to re-publish

**Comment by oilcan-productions** [comment]
Note that DNS replication for the change is still in progress and might take 48 hours to complete before it all starts working again

**Comment by larsbrinkhoff** [comment]
Thanks!  I squashed your three commits together.  The real test will be when we push to master, that's when the deploy script kicks in.

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Ok, let's give this a try.

**Pull request merged**
