### PR TITLE
Added sources and build instructions for Lisp library packages required by Macsyma

### LINKED ISSUE #706: Need various LISP packages to support Macsyma
The following LIBLSP LISP packages need to be built/installed in order to support the build and running of Macsyma:

LISPLIB;IOTA FASL (LIBDOC; IOTA KMP)
LIBLSP;TIME FASL (LIBDOC; TIME KMP8)
LIBLSP; LETFEX FASL (LIBDOC; LETFEX GJC2)
LIBLSP; LUSETS FASL (LIBDOC; LUSETS ALAN)
LIBLSP; BREAK FASL (LIBDOC; BREAK GJC1)
LIBLSP; SMURF FASL (LIBDOC; SMURF RWK1)
LIBLSP; FASDMP FASL (RLB%; FASDMP 124)

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #706.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I rebased this branch to the fixed master.  Force pushed.

**Comment by larsbrinkhoff** [comment]
Unusual to have a % in the directory name.

**Comment by eswenson1** [comment]
Regarding the % in the directory name, there is a source file (I think it was RLB; FASLRO that has an explicit reference to RLB%; FALSRE in it.  I decided to keep the original names -- although I'm inclined to want to move all of these random lisp source files to LIBDOC or something more "reasonable".  I think we decided on keeping things faithful first, and then would discuss cleaning things up and making things more regular.

**Comment by larsbrinkhoff** [comment]
Right, thanks!

**Pull request merged**
