### PR TITLE
Added TEACH;TS XLISP -- TEACH subsystem for teaching LISP.

### LINKED ISSUE #377: TEACH; LISP
There's TEACH; TS LISP that says it's assembled from SYS: SYS; PURQIO 2149.  So Lisp, I guess?

TEACH; TEACH 159 looks promising.

@BobKerns, do you want to look into this?

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #377.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
It's my impression TEACH; TS XLISP is a temporary name for an experimental version that should eventually be blessed and renamed TEACH; TS LISP.  Then the tutor can be started with `:TEACH;LISP`.  I don't see any XLISP in backups.

I think these should go in doc rather than src: -READ- -THIS-, TEACH BUGS, TO-DO 7.

We usually don't commit TAGS files, do we?  Does TAGS 3 have some special purpose here?

**Comment by eswenson1** [comment]
Well, the TAGS files are useful. I suppose it might be good to generate them, but why not include them until such time as we generate them?

Ok, I can move -read- -this-, teach bugs, and to-do 7 to doc/teach.

I'll add a step to rename TEACH; TS XLISP to TEACH; TS LISP.

**Comment by larsbrinkhoff** [comment]
It's not important so keep the TAGS file if you like.

I'd rather not add them to my commits because they can be out of date, and I think they can be generated when they are needed.

**Comment by larsbrinkhoff** [comment]
Need to add `teach` to Makefile variables SRC and DOC.

**Comment by eswenson1** [comment]
Yeah, src/teach was there, but not doc/teach.  Updated.

**Comment by larsbrinkhoff** [comment]
The CircleCI builds fail sometimes, and I don't know why.  The KA10 build sometimes hang when running MAGDMP.  KLH10 broke when I started loading more files in the boostrapping phase, and it now hangs occasionally usually when making EMACS.

**Comment by larsbrinkhoff** [comment]
KA10 did it again, so I can paste in the log:

```
spawn ./tools/sims/BIN/ka10 build/sims/init

KA-10 simulator V4.0-0 Current        git commit id: f934d88e
build/sims/init-7> at dpa0 out/sims/rp03.2
DPA: creating new file
build/sims/init-8> at dpa1 out/sims/rp03.3
DPA: creating new file
build/sims/init-9> at dpa2 out/sims/rp03.0
DPA: creating new file
build/sims/init-10> at dpa3 out/sims/rp03.1
DPA: creating new file
MAGDMP
$
The last command timed out.

**Pull request merged**
