### PR TITLE
JOBDAT REL - locate or reconstruct source

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
There are binary JOBDAT REL files in SAIL and DECSYS.  (Different sizes and time stamps.)

Reconstruct source code from disassembly (e.g. FAIL BIN), or find source somewhere else.  There is a JOBDAT.MAC in the SRI-NIC dump.  It was updated 1988, almost ten years after the ones in the ITS dumps.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
There are plenty versions of JOBDAT.MAC: DEC tapes, SRI-NIC backup, SailDart.  But they all look somewhat complex.

I used STINK to make a binary from SAIL; JOBDAT REL.  Then I disassembled it and wrote this much simpler version.

**Comment by larsbrinkhoff** [comment]
My JOBDAT didn't work well when used to build FAIL.

**Comment by eswenson1** [comment]
So what does this mean? Are you saying that your reconstructed version of JOBDAT REL was bad -- or something else? Why close this ticket? Are we giving up?

**Comment by eswenson1** [comment]
Oh, sorry. This is the PR and not the ticket. (I get confused sometimes with the UI being so similar).  So I assume you're going to try again (at some point) with a new PR, but keep the ticket open?

**Comment by larsbrinkhoff** [comment]
Right, the JOBDAT REL built from my new source did work.  I closed this, because I wanted to get back to it later, and I thought it looked bad to have a dangling pull request.

**Comment by eswenson1** [comment]
Thanks.  However, now I'm confused. One comment said "My JOBDAT didn't work well..." and your latest comment said it did work.  Which is it?

**Comment by larsbrinkhoff** [comment]
Argh, typo!  Should have been "didn't work".

**Comment by larsbrinkhoff** [comment]
Source was in:  
SAIL; JOBDAT 16

**Comment by larsbrinkhoff** [comment]
Fixed in #660

**Pull request closed without merging**
