### PR TITLE
NUDIR - create a user directory

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This is my own invention.  Makes it easier to create directories without having to remember the phrase ..NEW. (UDIR).

It also leaves a -READ- -THIS- file in the directory, to ensure it won't get deleted by the salvager.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm changing the name to NUDIR.  It's supposed to be a double entandre.

**Comment by larsbrinkhoff** [comment]
Before the ..NEW. (UDIR) feature existed, I believe directories had to be created by patching ITS at location NUFDTB.  It's a table of directory names that are created automatically when references.  The first item is 0, which is why I think it was for patching.

So now I'm considering renaming NUDIR to NUFD in homage to ancient ITS usage.

**Comment by eswenson1** [comment]
I assume NUFDTB existed in old ITS, but not in current ITS, right?  I don't see it in any of the files in the SYSTEM; directory.

There is an AUTOCR table in the SYSTEM; DISK >, but there are no zero-entries.

**Comment by larsbrinkhoff** [comment]
Right.  NUFDTB was replaced by AUTOCR.  I'm guessing ..NEW. (UDIR) was introduced at the same time.

**Comment by larsbrinkhoff** [comment]
The latest version we have with NUFBTB is SYSBIN; ITS CPY from May 1974, which is ML ITS 864.  The earliest sighting of AUTOCR is in SYSTEM; DISK 1012 from November 1976.

**Pull request merged**
