### PR TITLE
Build hangs on FreeBSD

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
build log: https://thunix.org/~neo_chen/TEMP/its.makelog

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@NeoChen1024, if you could test [this](https://github.com/PDP-10/its/pull/957/commits/cef794b4714d737a8ab765b2ef065e682e6a2bc9), that would be great!

**Comment by NeoChen1024** [comment]
But, it hangs at "(ASUM...", not "(todoi)"

**Comment by larsbrinkhoff** [comment]
@NeoChen1024, yes the last output in the log is "(ASUM...", but the reason the build script fails (I'm hypothesising) is that it doesn't see "(todoi)" in the output.  It's there, but it's broken up into "(", "tod", "io", and ")".

My change in this pull request should fix that.  It works on my machine, and on Travis CI.  But they also worked without this change.  I don't know if it works on your machine, so if you can test it that would be great.

**Comment by larsbrinkhoff** [comment]
@NeoChen1024, according to #963 I see you have built ITS.  Does that mean this issue is resolved?

**Comment by NeoChen1024** [comment]
Yes, it's resolved.

**Comment by larsbrinkhoff** [comment]
Thanks.

**Pull request merged**
