### PR TITLE
Updated to add EX ITS machine to host table. 

### PR DESCRIPTION
**Pull request by eswenson1**
Also updated chaosnet address for ES ITS machine and fixed typo.

### CODE REVIEW

**Comment by eswenson1** [comment]
Also, should we fix the duplicate address for DB-ITS.EXAMPLE.COM?  We currently have this:
```
;;; DistriBution ITS and generic KA
HOST : %CHAOS%%IP% : %HOSTNAME%, DB : PDP-10 : ITS : :
HOST : %CHAOS%%IP% : %HOSTNAME%, KA : PDP-10 : ITS : :
```
Which results in:
```
;;; DistriBution ITS and generic KA
HOST : CHAOS 3161, 192.168.1.100 : DB-ITS.EXAMPLE.COM, DB : PDP-10 : ITS : :
HOST : 192.168.1.100 : DB-ITS.EXAMPLE.COM, KA : PDP-10 : ITS : :
```
This causes a duplicate IP address for DB-ITS.EXAMPLE.COM.  Did you intend the second to be something like KA-ITS.EXAMPLE.COM?  Even that won't work, because you'll get a different error.  How 'bout turning these two lines into:
```
HOST : %CHAOS%%IP% : %HOSTNAME%, DB, KA : PDP-10 : ITS : :
```
Or perhaps:
```
HOST : %CHAOS%%IP% : %HOSTNAME%, DB, KA, KA-ITS.EXAMPLE.COM : PDP-10 : ITS : :
```
Or perhaps defining another variable, %KAHOSTNAME% and then using:
```
HOST : %CHAOS%%IP% : %HOSTNAME%, DB, KA, %KAHOSTNAME%: PDP-10 : ITS : :
```
Or maybe something else, entirely?

**Comment by eswenson1** [comment]
> Here are some more to add:
> 
> ```
> 4400 AMS.aosnet.CH
> 4401 LISPM-1.AMS.aosnet.CH
> 4402 LISPM-2.AMS.aosnet.CH
> 4403 BRIDGE.AMS.aosnet.CH
> 4404 FILECOMPUTER.AMS.aosnet.CH
> 3037 PUMA.NoCrew.ORG PDP-11 MINITS
> 3116 PREP.NoCrew.ORG VAX UNIX
> ```

You didn't provide the machine/os info for some of these.  How does this look:

```
HOST : CHAOS 4400 : AMS.aosnet.CH : : : :
HOST : CHAOS 4401 : LISPM-1.AMS.aosnet.CH : : :	:
HOST : CHAOS 4402 : LISPM-2.AMS.aosnet.CH : : :	:
HOST : CHAOS 4403 : BRIDGE.AMS.aosnet.CH : : : :
HOST : CHAOS 4404 : FILECOMPUTER.AMS.aosnet.CH :	: : :
HOST : CHAOS 3037 : PUMA.NoCrew.ORG : PDP-11 : MINITS :	:
HOST : CHAOS 3116 : PREP.NoCrew.ORG, PREP : VAX : UNIX : :
```

**Comment by ams** [comment]
> PUMA should have a short name.
> 
> I suppose @ams should have a say in what types his machines are. The Lispm operating system is usually LISPM. Are those CADRs? FILECOMPUTER ought to be LU ITS?

LISPM-1 and LISPM-2 are CADRs, so those should be LISPMs.  FC is a Unix host of sorts, similar to BRIDGE.

**Comment by ams** [comment]
> So that would make the list look like this:
> 
> ```
> HOST : CHAOS 4400 : AMS.aosnet.CH : : : :
> HOST : CHAOS 4401 : LISPM-1.AMS.aosnet.CH : CADR : LISPM : :
> HOST : CHAOS 4402 : LISPM-2.AMS.aosnet.CH : CADR : LISPM : :
> HOST : CHAOS 4403 : BRIDGE.AMS.aosnet.CH : : UNIX : :
> HOST : CHAOS 4404 : FILECOMPUTER.AMS.aosnet.CH : : UNIX : :
> HOST : CHAOS 3037 : PUMA.NoCrew.ORG, PUMA : PDP-11 : MINITS : :
> HOST : CHAOS 3116 : PREP.NoCrew.ORG, PREP : VAX : UNIX : :
> ```
> 
> So what hardware/os for AMS? What hardware for BRIDGE and FILECOMPUTER?

Thank you! In my `SYS: SITE; HOSTS TEXT`I just specify the hardware type as "UNIX" for stuff running on x86 hardware.  For AMS I am not sure, @bictorv what do you think we should do?  I guess it should be the same for Swenson.ORG, GEWT.NET, Victor.SE, etc.

**Comment by bictorv** [comment]
But... why not use the script I wrote? https://github.com/Chaosnet/config-files-from-dns

**Comment by bictorv** [comment]
AMS.aosnet.CH, Victor.SE, GEWT.NET, Swenson.ORG are NETWORKS, not hosts? Of course they don't have OSes.

**Comment by eswenson1** [comment]
Do you have a requirements.txt for the dependencies. I get:

```
$ ./host-files-from-dns.py
Traceback (most recent call last):
  File "./host-files-from-dns.py", line 30, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
```

And when I do:

```pip install dns```

I get:

```Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns```

**Comment by bictorv** [comment]
dnspython is at https://github.com/rthalley/dnspython.

**Comment by eswenson1** [comment]
dnspython only builds for python3.  Your scripts seems not to run with python3.  Catch-22.

**Comment by eswenson1** [comment]
@larsbrinkhoff I think this is ready to go. Please review. I did use the python script, but it had a few issues (emitting b'xxx' for strings, for example. So I hand updated the few relevant (new) entries to use the hardware/os from the output of the script.

**Pull request merged**
