### PR TITLE
Added support for NAME, FINGER, and its aliases. Also added support

### PR DESCRIPTION
**Pull request by eswenson1**
for the remote FINGER service. Note that this commit includes the INQUIR
database INQUIR;LSR1 >. This is needed for various programs that use the
LSRTNS library.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by larsbrinkhoff** [comment]
I looked at the LSR1 EMPTY file, and it has references to Alan.  Is it really empty?

**Comment by eswenson1** [comment]
Well, it was the one that came with PI as LSR1 EMPTY.  I guess it wasn't completely empty!

**Comment by larsbrinkhoff** [comment]
Fun fact: Setting an IP number to 0.0.0.0 in the host table makes the NAME build fail.  Maybe only if that host is in ITSIRP?

**Comment by larsbrinkhoff** [comment]
```
From colbath@cs.rochester.edu Tue Feb 20 00:47:47 1990
From: colbath@cs.rochester.edu (Sean Colbath)
Newsgroups: alt.folklore.computers
Subject: Origins of the finger command
Date: 20 Feb 90 02:39:31 GMT
Reply-To: colbath@cs.rochester.edu (Sean Colbath)
Distribution: alt
Organization: U of Rochester, CS Dept, Rochester, NY

In response to a number of users who read my article re:  the etymology of
the "finger" command, I send mail to Les Earnest, who, according to ARPA
RFC742, wrote the original finger command.  Here is the reply I got,
reproduced with his permission.  I think you may find it quite amusing and
enlightening.


From LES@SAIL.Stanford.EDU Mon Feb 19 21:32:35 1990
Date: 19 Feb 90  1831 PST
From: Les Earnest 
Subject: re: Greetings...    
To: colbath@CS.ROCHESTER.EDU

[In reply to message sent Mon, 19 Feb 90 16:02:17 EST.]

I'm glad that you are enjoying the C3 articles.  I need to write another
one soon.

Here is a response to your conjectures, mostly regurgitated from an
article that I posted on Human-nets in 1985.  Feel free to forward it to
alt.forklore.computers, or I can post it there if you prefer.  I haven't
been reading that newsgroup, but a quick look indicates that maybe I
should.

Finger was named for the act of pointing.  I recall that sometime after it
became popular I received a message from a system administrator who
thought that it should be renamed so that users would not have to use a
"dirty" word.  I gave his request all the consideration that it deserved.

I created Finger around 1971 to meet a local need at the Stanford
Artifical Intelligence Lab.  People generally worked long hours there,
often with unpredictable schedules.  When you wanted to meet with some
group, it was important to know who was there and when the others would
likely reappear.  It also was important to be able to locate potential
volleyball players when you wanted to play, Chinese food freaks when you
wanted to eat, and antisocial computer users when it appeared that
something strange was happening on the system.

The only tool then available for seeing who was running on our DEC-10
computer was a WHO program that showed IDs and terminal line numbers for
people who were logged in.  There was no information available on people
who were not logged in.  I frequently saw people running their fingers
down the WHO display saying things like "There's Don and that's Pattie but
I don't know when Tom was last seen." or "Who in hell is VVK and where
does line 63 go?"

I wrote Finger and developed the supporting database to provide this
information in traditional human terms -- real names and places.  Because
I preferred to talk face to face rather than through the computer or
telephone, I put in the feature that tells how long the terminal had been
idle, so that I could assess the likelihood that I would find them there
if I walked down the hall.

The program was an instant hit.  Some people asked for the Plan file
feature so that they could explain their absence or how they could be
reached at odd times, so I added it.  I found it interesting that this
feature evolved into a forum for social commentary and amusing
observations.

Finger was picked up by a number of other groups with DEC-10 computers
that were connected to Arpanet -- software flowed in all directions around
the net in those days.  It later migrated to Un*x, probably via U.C.
Berkeley.  Somewhere along the line the idea arose to provide a network
Finger service.  I don't remember who suggested that but it seemed like a
good idea at the time so I stuck it in.  Some other anxious people wanted
to be able to verify that their mail was delivered to specific addressees,
so the Mail feature was also added.

While I was somewhat surprised by the popularity of Finger, it has not
been as successful as an earlier program that I invented -- the spelling
checker.  It too was created to fill a personal need that many others
apparently share.  We didn't think about commercial development and
software protection in those days, but if we had we probably could have
made something out of it.  On the other hand, I enjoyed the comradery
of those gentler times and have no regrets.

	-Les Earnest (Les@Sail.Stanford.edu)

-- 
Sean Colbath
colbath@cs.rochester.edu			...uunet!rochester!colbath
"And now for something completely different..."

**Comment by larsbrinkhoff** [comment]
```
From mrc@Tomobiki-Cho.CAC.Washington.EDU Thu Feb 22 13:21:20 1990
From: mrc@Tomobiki-Cho.CAC.Washington.EDU (Mark Crispin)
Newsgroups: alt.folklore.computers
Subject: Re: Etymology time again...
Date: 20 Feb 90 23:55:37 GMT
Distribution: alt
Organization: Mendou Zaibatsu, Tomobiki-Cho, Butsumetsu-Shi

In article  bzs@world.std.com (Barry Shein) writes:
>Someone probably has the truth but finger certainly goes back at least
>as far as the mid-late 70's on ITS systems.

FINGER originated on the DECsystem-10 at the Stanford Artificial
Intelligence Laboratory (SU-AI, now SAIL.Stanford.EDU).  It was
written by Les Earnest in the SAIL (a cousin of ALGOL) programming
language.  This was in the late 1960's or early 1970's.

Ken Harrenstein implemented FINGER at the MIT Artificial Intelligence
Laboratory (MIT-AI) as NAME.  A FINGER protocol was implemented soon
afterwards.  This was in the mid 1970's.

The next version of FINGER was for Tenex and TOPS-20, writen by Mike
McMahon and Stuart Cracraft.  A later TOPS-20 FINGER was written (in
order of who worked on it) in the early 1980's by myself, Mike Peeler,
and David Eppstein.

By 1979, the number of FINGER servers had proliferated to the point
that everyone had given up on having "FINGER @*" (!!!) work.

I think the first Unix finger programs appeared by 1979 or so; I have
a bit set that UCLA-SECURITY had a finger program written by Lauren
Weinstein.
 _____     ____ ---+---   /-\   Mark Crispin           Atheist & Proud
 _|_|_  _|_ ||  ___|__   /  /   6158 Lariat Loop NE    R90/6 pilot
|_|_|_| /|\-++- |=====| /  /    Bainbridge Island, WA  "Gaijin! Gaijin!"
 --|--   | |||| |_____|   / \   USA  98110-2098        "Gaijin ha doko ka?"
  /|\    | |/\| _______  /   \  +1 (206) 842-2385      "Niichan ha gaijin."
 / | \   | |__| /     \ /     \ mrc@CAC.Washington.EDU "Chigau. Gaijin ja nai.
kisha no kisha ga kisha de kisha-shita                  Omae ha gaijin darou."
sumomo mo momo, momo mo momo, momo ni mo iroiro aru    "Iie, boku ha nihonjin."
uraniwa ni wa niwa, niwa ni wa niwa niwatori ga iru    "Souka. Yappari gaijin!"

**Comment by atsampson** [comment]
> FINGER originated on the DECsystem-10 at the Stanford Artificial Intelligence Laboratory (SU-AI, now SAIL.Stanford.EDU).  It was written by Les Earnest in the SAIL (a cousin of ALGOL) programming language.  This was in the late 1960's or early 1970's.

14th July 1973, according to [FINGER.SAI[1,LES]1](https://www.saildart.org/FINGER.SAI[1,LES]1).

**Pull request merged**
