### PR TITLE
Updated Zork to address issue with bad message when opening non-functional windows

### PR DESCRIPTION
**Pull request by eswenson1**
When you attempt to "open window" in the North and South of House, you get a response that isn't appropriate. With this fix, you get "This window cannot be opened.".

Addresses this issue:  https://github.com/heasm66/mdlzork/issues/58
And this fix: https://github.com/heasm66/mdlzork/pull/59

https://github.com/AlexProudfoot

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
The builds all fail like this.  Maybe insert a `<QUIT>` after act1 and start a fresh compiler for act2?

```
<FILE-COMPILE "act2 >">$
Input from DSK:LCF;ACT2 92
Output to DSK:LCF;ACT2 NBIN
Bounds checking on.
Default declaration is UNSPECIAL.
Output in fast mode.
Temporary output going to:  _ACT1 >
Running disowned, with record on DSK:LCF;ACT2 RECORD
Toodle-oo.
:PROCED
*
$p
:$ FATAL ERROR ILLEGAL UUO $
*
```

**Comment by eswenson1** [comment]
> The builds all fail like this. Maybe insert a `<QUIT>` after ACT1 and start a fresh compiler for ACT2?
> 
> ```

Yes. Sure nice to see in the build log why it failed! And yes, that will probably fix it. I don’t have this issue on ES. I wonder why?

**Comment by eswenson1** [comment]
@larsbrinkhoff Can you approve? Looks like builds are happy with my new approach. @heasm66 I think I added you as a reviewer as well.

**Comment by larsbrinkhoff** [comment]
Great, finally!  It's strange that XXFILE (or something else) worked ok but not any more.

I'll just split the commit in twain: one for Zork updates, and one for Tcl changes.

**Comment by larsbrinkhoff** [comment]
Three actually; the single commit has been split, but the end result is identical.  Approved.

A question: should the XXFILEs still be there as a convenience for building Zork manually?

**Review by larsbrinkhoff — APPROVED** [review]

**Review by heasm66 — APPROVED** [review]

**Comment by eswenson1** [comment]
> A question: should the XXFILEs still be there as a convenience for building Zork manually?

I think so. I use them to build on ITS. Too cumbersome to be done manually.

**Comment by eswenson1** [comment]
> Great, finally! It's strange that XXFILE (or something else) worked ok but not any more.

Yeah. The XXFILE approach works fine for me on ES and EX, as long as I’m not running them from expect. No clue why that is the case. Actually sometimes it runs under expect too — but not always.

**Pull request merged**
