### PR TITLE
Make BUGHST, TCPGAT, DOMGAT, HDRGAT and GATHST be settable in NAMES.

### LINKED ISSUE #2332: COMSAT should get GATHST, TCPGAT, DOMGAT from NAMES.
When changing addresses of e.g. your host system, patching in any updates of the addresses of TCPGAT and DOMGAT in COMSAT is easy to forget. It would be good if COMSAT would parse special host names (not every time they are used) and use their addresses instead.

I would imagine a good place for such host names would be .MAIL.;NAMES, where most of the COMSAT configuration is done anyway. Special entries such as

`(*COMSAT-TCP-GATEWAY (R-NAME my-tcp-gateway.com))`
`(*COMSAT-DOMAIN-GATEWAY (R-NAME my.domain.gateway.org))`

could perhaps be used (with or without the `*` - just to minimize the risk of collisions), and the OWNHST routine in COMSAT could check for them (using RCPEQV) and save them in TCPGAT/DOMGAT etc (if they are defined).

The advantage would be that if `my-tcp-gateway.com` changes address (in HOSTS3), COMSAT automatically picks it up (at its next restart).

Thoughts?

### PR DESCRIPTION
**Pull request by bictorv**
When changing addresses of e.g. your host system, patching in any updates of the addresses of `TCPGAT` and `DOMGAT` in COMSAT is easy to forget. This PR makes them settable through `.MAIL.;NAMES >` (along with `BUGHST`, `HDRGAT` and `GATHST`).

The attached `NAMES` file documents the settings and has defaults for `*COMSAT-TCP-GATEWAY` (TCPGAT) and `*COMSAT-DOMAIN-GATEWAY` (DOMGAT). The Makefile and build/misc.tcl are updated to use this way of making the settings, instead of the old.

Resolves #2332.

### CODE REVIEW

**Comment by bictorv** [comment]
Please test this, in particular the build stuff which I haven't actually tested.

Are there more/better places to document this?

**Review by larsbrinkhoff — APPROVED** [review]
I bumped versions.  Looks ok, but I have a limited understanding of COMSAT.

**Comment by bictorv** [comment]
> Please test this, in particular the build stuff which I haven't actually tested.

Now I've tested the build stuff, and while `make EMULATOR=klh10` fails on my Mac (probably related to #2270), the `out/klh10/_mail_/names.2011` file has the desired contents.

**Comment by eswenson1** [comment]
Sorry. Forgot to report that all worked well for me.

**Comment by larsbrinkhoff** [comment]
Merged.

**Comment by bictorv** [comment]
What about better/more places for documentation?

**Comment by larsbrinkhoff** [comment]
Either an INFO file, or here: https://github.com/larsbrinkhoff/its-manual/wiki

**Pull request merged**
