### PR TITLE
Apple II Logo

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
APLOGO;

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thanks, I didn't know about any Apple II enthusiast venues.  If this runs ok on an emulator, we could notify the Open Apple people.

**Comment by Alexey-Slyusar** [comment]
Unfortunately, I haven't tried out the things on a emulator yet. I hope
that I can do it tonight.

вт, 18 сент. 2018 г. в 13:33, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
Of course @Alexey-Slyusar, no problem.  We're not in a great hurry.  These programs have waited decades to be run, they can wait a few days or weeks more.

**Comment by Alexey-Slyusar** [comment]
Thank you, Lars! At the same time, the core members of the PDP-10 / ITS
community are very energetic! So I just try to follow, but not always fit
the rhythm. :-)

вт, 18 сент. 2018 г. в 14:51, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
It should look something like this:

**Comment by larsbrinkhoff** [comment]
The Terrapin version looks like this:


But the MIT welcome message should look like this:
```
Welcome to Apple Logo!
Preliminary Version
Assembled 8/06/80

**Comment by Alexey-Slyusar** [comment]
Thank you for the hint, Lars!

I could not mount a tape image in the SIMS emulator.
`sim> attach tu0 aplogo.tape
Non-existent device
sim> 
`
My KLH10 has crached due the Magic Switch issue. 

So I am building SIMH to make a dump for transferring the files to AppleWin emulator.

**Comment by Alexey-Slyusar** [comment]
I've packed logo.bin into a 5.25" Apple II floppy image and tried to run it under Apple DOS 3.3 but unsuccessfully: 

default

I'll continue to explore.

P.S. I've tried the command `sim> attach tu0 aplogo.tape Non-existent device sim>` on SIMS not on KLH10. 
I assumed that `attach mta0` is KLH10 relevant command, so I didn't try it on SIMS.
My KLH10 crashed before that, and I didn't have a chance to check the command on it.

**Comment by larsbrinkhoff** [comment]
There's the matter of what exactly the binary file contains.  As far as I can see, it's a 36-bit file with two 16-bit words packed into each PDP-10 word.  Obviously, this isn't directly suitable for loading onto an Apple II.  Also, there's some kind of container format.  The first 16-bit word is 1, and the next is the numer of bytes in that block, including the first four header bytes.

There also seems to be an option to generate the output in Intel HEX format.

**Comment by larsbrinkhoff** [comment]
Here's the situation with the attach commands:

- "SIMS" (KA10) uses `attach mta0`
- SIMH (KS10) uses `attach tu0`
- KLH10 (KS10) uses `devmount mta0`

I can see this is confusing.  I sometimes use the wrong command myself.

**Comment by larsbrinkhoff** [comment]
Maybe @brouhaha can drop us a hint on how to run some random binary on an Apple II.

**Comment by Alexey-Slyusar** [comment]
Lars, thank you!
Maybe it would be worth to add the SIMS command description to the DUMP
itstar file? How do you think?

ср, 19 сент. 2018 г. в 8:55, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
Yes, good point.  I haven't updated the DUMP-itstar.md document on how
to use "SIMS".  (It's really SIMH too, just an additional simulator for
KA10.)

**Comment by larsbrinkhoff** [comment]
It's running!

@pneubauer sent this:  
aplogo

**Comment by larsbrinkhoff** [comment]
Yes, it's the same binary.  I have asked Peter to explain how he got it running.

**Comment by pneubauer** [comment]
> Yes, it's the same binary. I have asked Peter to explain how he got it running.

I wrote a small utility to convert the PTP into a binary, and then I copied the binary to an Apple II DOS 3.3 disk image.  I'll post a working disk image with details on how to reproduce this process tomorrow.

**Comment by Alexey-Slyusar** [comment]
Thank you Lars!


вт, 2 окт. 2018 г. в 8:27, Lars Brinkhoff <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
I'm guessing something like this is handy:  
https://github.com/paleotronic/dskalyzer

**Comment by pneubauer** [comment]
See https://github.com/pneubauer/ptp2bin.  You'll find:
- A bootable disk image (LOGO.dsk) suitable for use with your favorite emulator or transfer to real hardware
- A "ptp2bin" utility for converting PTP files to binary
- A shell script that builds LOGO.dsk from the "logo.ptp" file

I use AppleCommander (https://applecommander.github.io) to modify the disk image, but "dskalyzer" would likely work, too.

**Comment by larsbrinkhoff** [comment]
Thank you, @pneubauer.  I was able to boot your disk image with the Linapple emulator.

**Comment by larsbrinkhoff** [comment]
Question for @Alexey-Slyusar: How do I exit the screen editor?  TO or EDIT enters it, but how to exit?  CHANGE enters the traditional type editor.

**Comment by pneubauer** [comment]
@larsbrinkhoff: In the screen editor, the following keys should work (per the source code).  But, I'm having trouble defining new procedures.  I'm not sure if I'm encountering a bug or operator error.

Ctrl-C = finished (complete) (exits screen editor and saves)
Ctrl-B = previous screen
Ctrl-D = delete char under cursor
Ctrl-F = forward screen
Ctrl-H = back char
Ctrl-L = center point on screen
Ctrl-O = open line
Ctrl-P = up line
Ctrl-U = forward char
ESC = rubout

**Comment by larsbrinkhoff** [comment]
Thanks!

Control-D, L, O, and P looks like Emacs, but then there's Control-B, F, U which don't.

Outside the editor, I see Control-G is "stop" and Control-Z is "pause", similar to ITS.

**Comment by Alexey-Slyusar** [comment]
I've defined a procedure. But I'm having trouble executing the procedure:
default

**Comment by Alexey-Slyusar** [comment]
`PO` shows something wrong in my case.

**Comment by larsbrinkhoff** [comment]
Mr Klotz said this early version might be broken.  I'm hoping to find a slightly newer version from 1981.

**Comment by larsbrinkhoff** [comment]
I haven't been able to enter code into a procedure.  It's defined, but there's no code inside.  `PO` shows an empty procedure.

**Comment by larsbrinkhoff** [comment]
Background info posted by @leighklotz to comp.lang.logo:

> In 1979, a high school freshmen named Stephen Hain came (who had previously come to the Logo Lab on an NSF-sponsored summer program) started working at the Logo Lab as a part-time job during school.  Hal Abelson assigned him the task of producing an Apple II version of Logo.  The Apple II wasn't yet a big success.  In fact, I believe Bill Gates had sold Apple the BASIC for it for a small flat rate -- he didn't think it was worth collecting royalties on.  Hain read a book ont the 6502 instruction set, and wrote about 300 pages of 6502 code, based on Gary Drescher's PLOGO model.  There was not a single comment in the entire file.
> 
> One day he cross-compiled it on a PDP-10, and downloaded it to an Apple II with a 16Kb memory extension ("language") card.  It didn't work.
> 
> The Logo Lab hired Patrick Sobalvarro to fix things.  After one month, he got it to initialize and then crash.  
> 
> Patrick moved on to write the screen editor, based on Craig Finseth's bachelor's thesis ``A Cookbook for EMACS,'' which described how to implement a redisplay for an EMACS-like editor.  Back then, editors still had ``insert mode'' and ``overwrite mode,'' and it was a big deal to be in ``insert mode,'' because you had to move characters over and do memory intensive operations, and it was slow.  Nowadays, nobody would use an overwrite-mode editor, but back then it was a radical move to have such an editor in a machine.  It wasn't until the Macintosh came out in 1984 that the idea of always being in insert mode and having an explicit delete key won out in the popular mindset!
> 
> Anyway, after a year or so in 1980, I dropped out of MIT and joined the Logo lab as a Sponsored Research Staff member.  I helped finish the Logo, and turned it into something ready for release to the world.

**Comment by larsbrinkhoff** [comment]
More backgrund from [Byte Magazine](https://ia902700.us.archive.org/8/items/byte-magazine-1981-08/1981_08_BYTE_06-08_Smalltalk.pdf)

> Unpublished Apple Logo 
> 
> With some hesitation, I'm writing this  letter to inform BYTE readers of an unfortunate situation concerning the distribution of the MIT Apple Logo programming language. I've been writing Apple Logo at the Logo laboratory for the last two years as an undergraduate project. I've labored under the understanding that Apple Logo was to be placed in the public domain or licensed to software-development companies or dealers for distribution. However, for the past eight months, MIT has withheld the language from the public. 
> 
> I would like to explain why. The original intent of my project was to implement a small subset of the Logo interpreter on the Apple computer. The final product actually evolved into a full-scale implementation, with features surpassing the Texas Instruments (TI) version, which also was developed at the Logo laboratory. When TI heard about this and the Apple Logo project, it reacted angrily; it fears that a Logo for the Apple would adversely affect sales of its Logo system. In fact, TI may be quite justified in its fears, for there are many people who think that Apple Logo is superior to TI Logo as an educational tool. It's rumored that Texas Instruments is depending on TI Logo to redeem the TI-99/4 home computer, which is not selling as well as expected. 
> 
> Texas Instruments is a very generous friend of MIT, and some people here are embarrassed about a situation that might threaten one of its sales programs. So, in an effort to appease its corporate friend, 
MIT has been stalling the distribution of Apple Logo. There was a version ready for distribution at the end of last year with many improvements over the version reviewed in the June BYTE (see "Logo for Personal Computers," page 36), and since then it has been expanded and improved. But I'm extremely frustrated that MIT chooses to avoid angering Texas Instruments by compromising the efforts of one of its undergraduate students. This frustration is compounded by the fact that I feel, as do many here at the lab, that the TI-99/4 has many serious deficiencies and that the public will be cheated if forced to buy it because it is the only machine on which Logo is available. 
> 
> Apple Logo is one of the finest programs that can be used on the Apple, and I would like to see it widely distributed as early as possible. Two years of my efforts went into it, as well as those of several others, and it's sad that MIT does not recognize the injustice that it is doing to myself, the Logo laboratory, and the many Apple users who would benefit from Apple Logo. If TI is afraid that its sales will be hurt, then it should fix the deficiencies in its machine and stop trying to suppress this program. I urge BYTE readers to write the Office of the Provost at MIT and request that Apple Logo be made public or licensed for distribution without delay. Thank you. 
> 
> Stephen Hain 
> MIT Logo Laboratory 
> 545 Technology Sq 
> Cambridge MA 02139

**Pull request merged**
