### PR TITLE
Added WHO%.

### LINKED ISSUE #294: WHO% - list index/uname/jname/%time in sorted list
SYS1; TS WHO%
SYS1; TS % => SYS1; TS WHO%
AR3: GREN; WHO% 5

Note: this program MPVs when I build it.  Needs to get debugged/fixed.

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #294.
Note: this program MPVs when run. Needs to get debugged. See #369.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Can you add to the commit message, which archive the source comes from?

**Comment by eswenson1** [comment]
How can I do that now, since I've already merged.

**Comment by larsbrinkhoff** [comment]
It's nice if there is a record of the original location, and as a commit comment it's part of the git repository forever.

I can temporarily unlock master, and rewrite the comments.  Can you send me the information?

**Comment by eswenson1** [comment]
Actually, the tickets associated with these PRs have the archive paths...

**Comment by larsbrinkhoff** [comment]
Thanks, I'll look there.

**Comment by larsbrinkhoff** [comment]
I have now force-pushed to master.  No files have been touched, just the commit comments.

**Pull request merged**
