### PR TITLE
CHATAB - print Chaosnet hosts

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYS3; TS CHATAB  
SYSEN1; CHATAB 7

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Sorry if you got an email about this, @krewat.  You're welcome to review if you like, of course. :-)

**Comment by bictorv** [comment]
Meh, var har du fått "Genera" för Lambda-D, Lambda-X och Amnesia från? De ska vara "Lambda" ju.

**Comment by larsbrinkhoff** [comment]
@bictorv, I briefly considered something other than "LISPM" for all kinds of Lisp machines.  This is from my NO machine with lots of experimental changes on there.

**Comment by larsbrinkhoff** [comment]
The majority of ITS users understands Swedish these days, don't they?  I think five out of... seven?

**Comment by eswenson1** [comment]
And those of us who don’t can attempt to rely on google translate!

**Comment by larsbrinkhoff** [comment]
Of course, good catch.

**Pull request merged**
