### PR TITLE
CUBE

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYS3; TS CUBE  
.INFO.; CUBE INFO  
BSG; CUBE 8  
BSG; CXFRM 7  
BSG; CINPUT 16  
BSG: CSOLVE 8  
BSG; CUTILS 5  
BSG; CDRIV 53  
BSG; CUBE TEMPLT
BSG; CUBE DCLS
BSG; CSOLVE DCLS
BSG; OONL 3  
BSG; QQC 46
BSG; QCOLOR 82
BSG; CUBPKG 31
BSG; CUBRDF 4

Valrets on ES-ITS and UP.  Couldn't connect to SV now.  But on ka10.de it works!  And it's a Rubrik's Cube game.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Here's a demo:
https://www.youtube.com/watch?v=m6D3RhZPa7Y

**Comment by eswenson1** [comment]
Love the video, @larsbrinkhoff

**Comment by BernardGreenberg** [comment]
Quite amazing.  Thank you so much!
________________________________

**Comment by larsbrinkhoff** [comment]
Thanks!

**Pull request merged**
