### PR TITLE
Have "KL" ITS boot directly into NTS DDT.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This avoids using DSKDMP for pdp10-kl, aka KL ITS (but really still KA10).  This brings it closer to how MC was booted, e.g. load NTSDDT from KLDCP.

CC @eswenson1

### CODE REVIEW

**Comment by eswenson1** [comment]
You assigned this to me. Did you intend to add me as a reviewer?

**Comment by larsbrinkhoff** [comment]
Sorry, yes.

**Comment by larsbrinkhoff** [comment]
The pdp10-ka and pdp10-kl variants now hang unexpectedly in the middle of the build.  Since I updated the simulators from @rcornwell's upstream, I'll have to check to see if that is the cause.

**Comment by larsbrinkhoff** [comment]
I rolled back to an earlier version.

**Pull request merged**
