### PR TITLE
CHAOSNET ARPA/NCP/TCP - Chaosnet to Arpanet/Internet gateway

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYSNET; ARPA 66  
DEVICE; CHAOS ARPA  
DEVICE; CHAOS NCP  
DEVICE; CHAOS TCP

### CODE REVIEW

**Comment by eswenson1** [comment]
Why are these PRs saying they were opened about a year ago?

**Comment by larsbrinkhoff** [comment]
Because I'm reusing the old issues rather than opening new pull requests.

**Comment by eswenson1** [comment]
How do you do that?  I thought you had to create PRs for any new merges to master from changed non-master branches.

**Comment by larsbrinkhoff** [comment]
There is an API to convert an issue into a pull request.  I have a shell script to do that in my git-scripts repository:  
https://github.com/larsbrinkhoff/git-scripts/blob/master/git-hub#L54-L81

**Comment by eswenson1** [comment]
Why would you want to do this?  Seems to me that while the issue might be old, the PR (the request to merge) is new.  Why would you want the date on the PR to be that of the date the issue was created?  Is it so that we don't use up integer values too quickly (or issues and PRs)?  :-)

**Comment by larsbrinkhoff** [comment]
I do that t keep the discussion about the issue and the pull request in one place.  So that information about the same thing is less spread out.

**Comment by eswenson1** [comment]
Is that an approach you'd like the rest of us to use too?

**Comment by larsbrinkhoff** [comment]
I'm not overly concerned.  I think people can do what they're comfortable with.

**Pull request merged**
