### PR TITLE
Add VERSA

### LINKED ISSUE #856: Versatec Spooler
DCP; VERSA 210

Can read many file formats:
- ARDS
- Tektronix
- XGP scan
- Harvard scan
- Dover press

Can display bitmaps using SUPDUP graphics.

### PR DESCRIPTION
**Pull request by atsampson**
This is a rather flexible rasterising printer spooler, which works as a route for getting images out of applications like SUDS that print in PLOT or XGP format.

I've added a JCL parser so you can convert files (or show them with SUPDUP graphics, untested!) without needing to run the spooler demon. In spooler mode, it does seem to run OK, but I don't think we have the program for putting files into the spool directory; perhaps this was a modified version of XQUEUE, which uses the right spool directory but the wrong filename convention.

Fixes #856. Related to #862.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
I'm thinking the spooler would have been put in (or linked from) the DRAGON directory and doesn't need to be in SYS: or have a TS name.

**Comment by larsbrinkhoff** [comment]
There was a CHANNA; V80SPL during the 1982-1985 period.  Also GLPT; TS SPOOLR in 1976-1978.

VERSA 210 has timestamp 1983-09-19, and version 4 which is the first I can see is dated 1981-06-22.

So I'm guessing the Gould printer was installed in the late 70s, and then maybe VERSA used some code from the Gould spooler.

**Comment by larsbrinkhoff** [comment]
Also CHSGTV; TS SPOOLR and SPGLPT 19 both from 1978.

**Comment by larsbrinkhoff** [comment]
With this information in mind, I think there could be an optional link from CHANNA; V80SPL to SYS3; TS VERSA.  Currently, we don't have a way to specify which system services should be enabled or not.  For now the link could be commented out.

**Comment by larsbrinkhoff** [comment]
This from INFO; GLP 22 makes it sound very much like VERSA.

> The Gould spooler can currently print graphics files using ARDS, Tektronix, DPLT, and IMAGE formats.  ARDS files are most commonly produced by the MACSYMA PLOT2 package or Muddle graphics.  Tektronix files usually originate on some other machine and are copied to MC for printing.  DPLT files are produced by the Stanford Drawing System (SUDS) or GEOMED.  Image files are raw bit data.  In the future more types will be added (FR80, ITS, SCAN, etc).

**Comment by atsampson** [comment]
Sounds good. I've removed TS SPOOLR and add a commented-out link to CHANNA; RAKASH V80SPL.

**Comment by larsbrinkhoff** [comment]
Conflict in Makefile DOC, sorry!

**Pull request merged**
