### PR TITLE
Added FDIR (fast directory listing).

### LINKED ISSUE #313: FDIR - fast directory listing
SYS2; TS FDIR
AI: SYSENG; FDIR 84
AI: .INFO.; FDIR INFO

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #313.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
So how fast is it?

**Comment by eswenson1** [comment]
Faster than a speeding bullet.  :-)

I just used the same text as was used in the source code.  It is just a compressed display of a directory with only the names and arranged in rows.

**Comment by larsbrinkhoff** [comment]
Ah, should be much faster on a 1200 baud line.

**Comment by eswenson1** [comment]
Indeed.  I remember using ITS on a 1200 baud line.  We had an LA36 (printing) terminal in our fraternity house with an acoustic coupler modem. I had to dial up a TIP/TAC and enter "@o 54" (or something like that) to connect to MIT-MC.  And boy, did you regret typing some command that spewed a lot of output. You had to abort output all the time for fear of using up all the paper, or waiting interminably for the output to finish....

**Pull request merged**
