### PR TITLE
Update networking docs for KLH10

### PR DESCRIPTION
**Pull request by bictorv**
But I think it can be improved wrt the new build/mchn setup - @larsbrinkhoff ?

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
The use of MCNH is an advanced topic perhaps better explained in another document.  I think the parameter will only affect which section of CONFIG is used.  People with their own ITS name probably understands this.

**Comment by bictorv** [comment]
I agree it's for another document. But I think the parameter could be used in more ways - again a separate discussion. :-)

**Comment by larsbrinkhoff** [comment]
Ok to remove that part of the commit message?

**Comment by bictorv** [comment]
Yes, of course.

**Review by eswenson1 — APPROVED** [review]

**Pull request merged**
