### PR TITLE
Build TECO-6 from reconstructed source code

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
The @ TECO binary is replaced with a program built from source reconstructed from old ITS TECO sources.

### CODE REVIEW

**Review by eswenson1 — COMMENTED** [review]
Is the right thing here really to move the entirety of the Muddle build (muddle.tcl) forward, or wouldn’t it be better to simply move the STINK build out of muddle.tcl and before you need it for pdp-6 TECO?

**Comment by larsbrinkhoff** [comment]
I thought about something like that, but then we'd have to decide on a new location or name for STINK so I punted on that.  Suggestions?

**Comment by eswenson1** [comment]
Or you could keep the name and location the same as where muddle.tcl puts it. Just move the required lines from muddle.tcl to the TCL that builds 6 TECO.

**Comment by eswenson1** [comment]
Or make it STKnnn (whatever version it is) and put in SYS3 (and update muddle.tcl) to reference it.

**Comment by larsbrinkhoff** [comment]
Ok, I did the first thing.

**Review by eswenson1 — APPROVED** [review]
I assume the MUDSYS directory pre-exists from the tape load so you didn't have to create it?

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
The directory isn't created by the build scripts.  I think there's some MUDSYS files on the big "sources" tape.

**Pull request merged**
