### PR TITLE
Add INQUIR entries for system users and directories.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
These entries were added, based on information from backed up LSR1 files: APPLE2, DRAGON, DRAW, GFR, GT40, MINI, PDP11, PEEK, TARAKA, and TEACH.

### CODE REVIEW

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Only a draft so far.  I tried putting all users in a single .UPD1. file, but that doesn't seem to work.  Maybe they have to be separate files.

**Comment by eswenson1** [comment]
Really? I’m pretty sure you can have multiple entries. Separated by the correct separator.

if not, we can clearly have multiple .UPD1. files with different FN2s.

**Comment by larsbrinkhoff** [comment]
I tried using a ^_ separator, and I tried having just a blank line.  Neither worked.  Having separate files work.

**Comment by larsbrinkhoff** [comment]
Another aspect is that FILDI may have @ to indicate a directory on a particular machine.  There can be multiple directories, separated by comma.  I'm guessing the first directory is the home directory for the user.  If the @ indicates a machine other than the current one, apparently strange things can happen.  What happened in the build script is that the TEACH directory was TEACH@MC, and when the commands `TEACH$^S` and `EMACS^K` were run, the right EMACS init file was not picked up.  So I think it's best to drop all @\<machine>.

**Pull request merged**
