### PR TITLE
Some doc updates

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I have some doc updates batched up.  Please suggest more.

- Added a games.md to list the games and how to start them.  @eswenson1 and @atsampson, I'd like your input on the games you added.
- Small updates to the version history.
- Fix Gould printer in peripherals list.
- Add miscellaneous ITS documentation files.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@eswenson1, can you add or sent me a short description of TREK?

@atsampson, likewise for WUMPUS and JOTTO?

**Comment by eswenson1** [comment]
Geez. I'm no expert on Trek.  It's a Star Trek simulation game, where you are in charge of the Enterprise, are fighting Klingons, have photon torpedoes and phasers at your disposal. You choose the size of the galaxy (in number of quadrants) and can leverage a battle computer to compute directions and warp factors. You can replenish your energy, torpedoes, etc. by docking at one of your star bases. Your goal is to defeat all the klingons. Does that work?

**Comment by larsbrinkhoff** [comment]
Sure Eric, I'll use that.  Just need one or two sentences for each game, and how to start it.  Maybe point to some instructions.

**Comment by larsbrinkhoff** [comment]
This will do for now, I think.

Added another commit with various ITS doc files.

**Comment by larsbrinkhoff** [comment]
I did some changes since Eric approved this, but since no one raised any objections, I'll merge this.

**Pull request merged**
