### PR TITLE
.gitattribtues (doc/c/cc.pat, doc/c/ccdoc.text): Mark as text files.

### PR DESCRIPTION
**Pull request by ams**
See https://github.com/PDP-10/its/pull/1375

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thanks.  Everything in /doc and /src should be text.  Can you extend the scope of this pull request?

**Comment by larsbrinkhoff** [comment]
Oops, /src is already "Assembly".  That's not correct, but better than Text.

So just make /doc Text.

**Comment by larsbrinkhoff** [comment]
Please also add the `diff` attribute to /doc/*/* and /src/*/*.  It doesn't affect GitHub, but it does git.

**Comment by ams** [comment]
What do you want the diff attribute to be set too?

**Comment by larsbrinkhoff** [comment]
Checks passed.  @ams, would you do the honors?

**Pull request merged**
