### PR TITLE
KI10 "breathing lights"

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I found this in the telehack.com game:

```
Date: Fri, 6 May 94 17:19:56 PDT
From: Pat Tressel <tressel@decwet.enet.dec.com>
Subject: nostalgia

I was cleaning out stuff I still had at Locke this past Saturday, when I
came across something I thought I'd lost long ago:

0/  1,,0
1/  400000
2/  0
3/  0

6/  movei 4,40000
7/  xor   3,1
10/ xor   3,0
11/ movem 3,2
12/ imuli 3,1
13/ dmove 2,2
14/ sojg  4,12
15/ rot   0,1
16/ rot   1,-1
17/ jrst  6

(start at 6)

This is (one version of) the "breathing" KI lights code.  (The other
version doesn't have the movem or dmove.)

### CODE REVIEW

**Comment by eswenson1** [comment]
No build of these two programs?  Just the source?

**Comment by larsbrinkhoff** [comment]
I was thinking they are primarily for preservation, and easy to assemble if you want to.

**Comment by larsbrinkhoff** [comment]
@j-hoppe, the top comment in this issue has an actual program for running KI10 lights.

**Comment by ptressel** [comment]
I should mention that I don't have KI hardware documentation -- whatever we had vanished when our KI was replaced with a KL.  I sulked for days when the KI was turned off.  I should also note that which instructions got things displayed in the various light rows was determined somewhat experimentally, except that there were labels on the KI processor lights.

I don't know if that was the final version of the program.  Had I guessed that Evil People were going to complain, and demand that the KI be turned off *because of* the lights, I'd have been more careful to record the final version.  Ok, now I'm back to sulking again.

**Comment by larsbrinkhoff** [comment]
@SMJ is now testing this code on a KA10.  I'm begging him for a video.

**Comment by larsbrinkhoff** [comment]
It will certainly do *something*.  I added in a DATAO PI,3 too, so it should display on the console MI lights.

I'm not at all sure about the BR, MB, MQ lights but there's a good chance some of them will follow suit.

**Pull request merged**
