### PR TITLE
LIVE - PALX Game of Life

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
BUDD; LIVE PALX, with permission from author @philbudne.

Nice application for testing PALX and 11SIM.

I also used the assembled binary to test my converter from PALX binary to PDP-11 absolute loader paper tape image, and then verified that LIVE runs in SIMH too.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
As I wrote in the commit, either run this in a VT52 capable terminal emulator such as xterm (just send it the magic escape sequence), or in CRTSTY with the SIMULATE VT52 option.  Or hey @sethm, use a VT52!

**Comment by philbudne** [comment]
Note: I wrote it as a tourist in the 80's, so not a piece of MIT/ITS history!

p

**Comment by larsbrinkhoff** [comment]
It kinda is now!

**Comment by larsbrinkhoff** [comment]
I have now also subjected this poor program to PDP-11 stuffing.  All good things come to those who wait?

**Pull request merged**
