### PR TITLE
Correct file timestamps

### PR DESCRIPTION
**Pull request by lashtear**
Several files in `EMACS1;` have a timestamp in the gap caused by
EST->EDT timezone shift of 1989, likely as a result of
daylight-savings handling limitations in ITS at that time.

See https://github.com/PDP-10/its/issues/2044#issuecomment-870858093
and the later comments in #2051 .

The solution is to advance the three files in question one hour, which
is what they would have had if the timezone flipped at 2AM.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you.  I have been suspecting the timestamps have been mangled worse than just by one hour.  I'm not sure exactly what happens to the timestamp on the tape as it passes through itstar, then goes to disk, and finally is printed by ls.

Take the VT52 4 file for example.  The bits on the tape say "1989-04-01 19:11:39", but what I wrote in timestamps.txt was "198904020211.39".  So that's off by seven hours.

If I set TZ=EST, I do get the right timestamps from the extracted files on my disk.

**Comment by larsbrinkhoff** [comment]
I made a very slow shell script which should generate updated timestamps.  I will update this pull request when it has finished, in a few hours or days.

**Comment by larsbrinkhoff** [comment]
I have now carefully checked the timestamp bits on tape, and compared against those extracted to disk.  They seem to be the same except the first are (implicitly) local Massachusetts time - maybe with or without daylight saving, and the disk timestamps are in GMT.  My confusion came from running `ls` or `stat` and relying on the result, but that's converted to *my* local timezone which is off by around six hours.

I have now regenerated timestamps with TZ=EST.  Maybe this will be off by one hour during summers, but I'm willing to live with that for now.

**Review by eswenson1 — APPROVED** [review]

**Comment by lashtear** [comment]
I'd been thinking about shifting everything to UTC for clarity, but using EST (or EST5EDT maybe) does make sense for keeping things matching original data.

There are a couple places where current time is set (e.g. for the running machine) from localtime, which probably should get the same TZ treatment.

Thanks for looking!

**Comment by lashtear** [comment]
|Error|Line|
|:---|---:|
`touch: invalid date format ‘19780201141707’`| scheme/docume.89 19780201141707
`touch: invalid date format ‘(198604220323.02’`| inquir/inquir.(dump) (198604220323.02
`touch: invalid date format ‘(198106271729.00’`| maxtul/mcldmp.(init) (198106271729.00
`touch: invalid date format ‘(198001192010.37’`| scheme/nschsy.(init) (198001192010.37

Not sure what is causing the `SCHEME;` one to not have a dot; the `.00` case shows up on other lines at least.  The other three are an extra paren-- which tool is generating the list?  (May be reasonable to add it if it can do this from old tape images in an arbitrary way)

**Comment by larsbrinkhoff** [comment]
Thanks for checking.  I'm fixing those errors.

There is no nice tool for generating the timestamps.  It's a mess of scripts I make up on the fly pulling data from various places, plus lots of manual editing.

(I think that would be an appropriate collective noun.  You know gaggle of geese, parliament  of owls, mess of scripts.)

**Pull request merged**
