### PR TITLE
Added build of LIBLSP; VSAID FASL and LIBLSP; TTYVAR FASL.

### LINKED ISSUE #756: LIBLSP; TTYVAR FASL needs to be built from source
Source for this appears corrupted (LIBDOC; TTYVAR GSB1).  Need to find a better copy.

### PR DESCRIPTION
**Pull request by eswenson1**
Resolves #756 and #758.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Why make a copy of NILCOM; VSAID >, is it like that in PI?

**Comment by eswenson1** [comment]
You mean as opposed to just putting a link LISP: VSAID LISP to NILCOM; VSAID >?.   I guess I could/should have done that.  I can update for that.

**Comment by larsbrinkhoff** [comment]
Yes, I think we have made links in all other instances.

**Comment by eswenson1** [comment]
Yeah, I thought I saw this as a non-link somewhere, but I can't find it now.

**Comment by eswenson1** [comment]
Ok, fixed.

**Comment by eswenson1** [comment]
And I checked PI and there is no LISP; VSAID LISP (or LISP; VSAID >) -- just the FASL.  However, compiling the source (NILCOM; VSAID >) requires there to be a LISP; VSAID LISP in place.

**Pull request merged**
