### PR TITLE
Missing ';' to comment out mode-line.

### PR DESCRIPTION
**Pull request by BobKerns**
Obvious damage.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you.  The ; is also missing from the previous version ERRHER 37.

**Comment by BobKerns** [comment]
In case you were wondering why I noticed and what I'm doing: I'm loading the code into my web browser straight from Github.

I've sort of implemented Maclisp in an ObservableHQ Browser notebook. Check it out!

https://observablehq.com/@bobkerns/maclisp

**Comment by larsbrinkhoff** [comment]
@BobKerns, that is amazing!  Please keep us posted on your progress.

Will Macsyma run on this... ?

**Comment by BobKerns** [comment]
I think Macsyma might be easier than sorting out this mess of circular dependencies. The stuff I'm fighting with is the stuff that is massively self-referential yet inconsistent, while conditionalized for 5 different Lisp implementations: Maclisp, Multics, NIL, Lispm, and Franz.

I'm trying to keep the complexity down by not implementing hunks nor the SFAs (Software  File Arrays) used in various extended datatype addons added later. Neither TEACH;LISP nor Macsyma used these originally, so I figure eliminating code that depends on those will help narrow the scope of compatibility layer issues.

And half the stuff is not in the location that the code expects it to be, so my virtual filesystem notebook aliases a lot of files. Also, I don't handle PDP-10 FASL files, so I redirect those to source files.

By comparison, implementing a Lisp interpreter is easy.

**Comment by BobKerns** [comment]
But you know, it WOuLD be really cool to run Macsyma in an Observable notebook!.

So far, my impression is that it's faster than the original with compiled code.  I suppose I could compile it to Javascript. I compile function entry as it is, and I could optimize that further, if I ever notice it being slow. Most of my edits trigger a complete rebuild/reload, which so far happens faster than I can get back to observe the result. The V8 Javascript execution engine has pretty amazing performance.

**Comment by larsbrinkhoff** [comment]
Kent (@netsettler) says he wants to be in the loop on this.

**Comment by BobKerns** [comment]
I'm sure he does! I didn't realize he had a presence here, but I was going to grab him via other channels once I had a couple issues resolved (which I didn't quite yesterday). In a real sense (as I noted on the page) this is really his code at this point; I don't think there's much he didn't redo, and much of the lesson content was his work from the outset.

I'm to the point where I'm pretty sure I can do interesting stuff, but not far enough along to know just how much work it is.

I'll go ahead and ping him now. Probably not much he can help with the current process, but he can fork and fix up my exposition, something he excels at. And I hope to be to a point of discussing the TEACH;LISP code itself in a day or two.

Presently, I'm debugging my support for multiple values and providing some queuing so it doesn't try to run multiple cells' code at the same time in the same engine. The results can be...interesting.

I'll probably have that all sorted out tonight, enough to be a viable playground.

Observable notebook can be forked, and the changes can be submitted as "suggestions" (essentially, primitive pull requests).

**Comment by BobKerns** [comment]
(I dropped him a DM ping on Twitter. I'll follow up on  FB and/or Email later).

**Pull request merged**
