### PR TITLE
SEND programs

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
SYSNET; SENVER 45 - Chaosnet SEND server → SYSBIN (linked from DEVICE; CHAOS SEND)  
SYSNET; SENDS 24 - Chaosnet SEND server → SYSBIN (*not* linked from DEVICE; CHAOS SEND)  
GREN; SENSOR 87 - Sends censor → SYS3

SENVER and SENSOR appear to both do the same thing.  I chose to install SENVER as the Chaosnet SEND server, because it's newer and bigger.

### CODE REVIEW

**Comment by eswenson1** [comment]
Have you tested this? Have you set up a chaos net between two DB ITS machines?

**Comment by larsbrinkhoff** [comment]
No, it's not tested.

**Comment by larsbrinkhoff** [comment]
I tested it now.  `:SEND EJS@ES`

**Comment by larsbrinkhoff** [comment]
OS says it worked.

```
TTY message from chaosnet site NO.NOCREW.ORG:
LARS@DB  12:12pm
Testing Chaosnet SEND.

**Comment by eswenson1** [comment]
Weird.  I just tried it from NO (to ES) and I get a hang:  Can't get out of it. Have to kill supdup.

Update: It just takes a VERY long time (minutes).  I killed my HACTRN and tried a few times.  Finally, I just let it sit there and minutes later, I received a message on ES (from NO).  And :QSEND from ES to NO appears to work too.  It doesn't hang on the sending side -- but appears to take just as long to get the message received on the receiving side.

**Comment by eswenson1** [comment]
yes, messages from ES to NO appear to work fine (and don't hang the client).  Messages from NO to ES, using :send appear to hang until the message is successfully sent. Can't ^Z out of the hang.

**Pull request merged**
