### PR TITLE
C library for TV raster graphics.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**

### CODE REVIEW

**Comment by eswenson1** [comment]
I don't see this library being built. Is it supposed to be?

**Comment by larsbrinkhoff** [comment]
No, it's not built.  I was thinking it doesn't need to be until there's an application that uses it.  What do you think?

**Comment by eswenson1** [comment]
Hmm....I think if it is buildable, and could be used for linking with if there were an app that needed it, we should build it.

**Comment by larsbrinkhoff** [comment]
Fair enough.  I updated the commit.

**Pull request merged**
