### PR TITLE
Update APLOGO

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
APLOGO; LOGO 299, dated 1981-07-09

```
        .ASCII "         Logo for the Apple II"
        .ASCII "written by S. Hain, P. Sobalvarro"
        .ASCII "and L. Klotz under the supervision"
        .ASCII "of H. Abelson."

        .ASCII "This version assembled 7/9/81."
```

CC @leighklotz

### CODE REVIEW

**Comment by markisch** [comment]
@larsbrinkhoff [MIT_LOGO_for_the_Apple_II_1981](https://archive.org/details/MIT_LOGO_for_the_Apple_II_1981) mentions that it is 

> Released under the MIT License (http://opensource.org/licenses/MIT), per e-mail correspondence with H. Abelson on 5 November 2012.

Does this apply to the logo.299 source?

I have translated the source to the format used by the Merlin32 cross-assembler. After some minor tweaking, the assembled binary is now identical. I'd be more than happy to share.

**Comment by larsbrinkhoff** [comment]
@markisch, I'm surprised by the date November 2012.  I wonder if that should be 2018 instead?  Maybe @pneubauer knows more about this.

I believe the archive.org copy is identical to the 299 version here, so the license should apply.  It would not apply to the earlier 958 version.

I think it's a good idea to put your converted source out there.  This repository is not the right place though, so maybe make another?

**Comment by pneubauer** [comment]
I exchanged several emails with Dr. Abelson in 2012 (not 2018). At that time, Terrapin was considering releasing their Apple II Logo derivative, but that did not happen and I could not find an unmodified copy of MIT Logo.

Here's the original exchange:

> The MIT Logo software is released under the MIT License
> 
> http://opensource.org/licenses/MIT
> 
> Feel free to use it under the terms of that license.   If you redistribute it, please incoude a note that it is copyright MIT and released under the MIT license.
> 
> ==Hal 
> 
> On Sun, Nov 4, 2012 at 9:48 PM, Peter Neubauer wrote:
> Dr. Abelson,
> 
> I'm referring to the Logo language software developed at MIT under National Science Foundation Grant No. SED-7919033, copyright 1981.  The software distribution consists of two floppy disks, one labelled "Language Disk" and the other "Utilities Disk."  MIT licensed the software for commercial distribution to Terrapin Software and Krell (and possibly others).  My copy bears the following notice:
> 
> "The Technical Manual and the Logo software are copyrighted by the Massachusetts Institute of Technology.  The Tutorial and changes to the Technical Manual and Logo software are copyrighted by Terrapin, Inc."
> 
> and 
> 
> "Copyright, (c) Massachusetts Institute of Technology, 1981.  Except for the rights and materials reserved to others, the Publisher and Copyright owner hereby grant permission without charge to domestic persons of the United States and Canada for use of this work and related materials in the United States and Canada after 1995.  For conditions of use and permission to use materials contained herein or any part thereof for foreign publications or publication in other than the English language, apply to the Copyright owner or publisher.  Publication pursuant to any permission shall contain an acknowledgement and disclaimer statement as follows: [NSF credit omitted for brevity.]"
> 
> Bill, the current owner of Terrapin software, offers the following:
> 
> "I was at Terrapin at the very beginning and then gone for a number of years before coming back (and buying the company).  I am not sure what the entanglements with MIT were, but remember from old financial records payment of royalty to MIT.  As I understand it, the original MIT version of Logo for the Apple II was developed with a National Science Foundation grant whose stipulations required non-exclusive licensing of any resulting products. (Terrapin held one of those licenses.)  LCSI, founded by Papert, developed a version that was exclusive and royalty free with some differences from the original version developed at MIT.  There were lots of arguments back in the day as to which was better or even if they were different, but to my knowledge it was never challenged by MIT or in court and the two companies have ended up going their separate ways.  Terrapin did write the documentation and published the software, but I don't know who exactly held the copyright to that original version."
> 
> Given the "after 1995" clause, it seems that permission from Terrapin may be sufficient for legal redistribution.  But, I would appreciate your recommendation.
> 
> Thank you,
>     -Peter
> 
> On 11/4/2012 12:14 PM, Hal Abelson wrote:
> What software  (code files) are you talking about specifically?   What exactly does the copyright notice say?
> 
> ==Hal

**Comment by larsbrinkhoff** [comment]
Thank you, that's very good to hear!

**Pull request merged**
