### PR TITLE
Add contribution guidelines.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
@eswenson1 I'd like you comments on this.  Anything to change, or to add?

### CODE REVIEW

**Comment by eswenson1** [comment]
Seems ok to me. I'd probably include something to the effect that initially we are trying to mirror the PI distribution in terms of organization. Later, we may wish to start deviating/reorganizing to make for a saner system. But for now, it makes things easier if we can compare the DB and PI builds (file-by-file, directory-by-directory) to measure progress and determine when we have succeeded.

**Comment by larsbrinkhoff** [comment]
I added a short bullet point about that.

You are free to change, add to, or merge this PR if you like.

**Comment by eswenson1** [comment]
Are you ready to have me merge, once travis is happy?  I'm ok with this.

**Comment by larsbrinkhoff** [comment]
Yes, merge away!

**Comment by larsbrinkhoff** [comment]
> we are trying to mirror the PI distribution in terms of organization. Later, we may wish to start deviating/reorganizing to make for a saner system. But for now, it makes things easier if we can compare the DB and PI builds (file-by-file, directory-by-directory) to measure progress and determine when we have succeeded

I feel it's better to do the updates as we go, because the amount of work to get to a perfectly finished state replicating PI is so large.  We may end up never getting there.  And then the reorganizations will never be done.

I'd suggest we try to eat the cake and have it too.  Add a commit that records the files in a state that replicates the original system, and then another commit with updates.  It can be an individual choice whether this update is done right away, or much later.

**Comment by eswenson1** [comment]
I actually think we should mirror the PI distribution with respect to all the executables and basic functionality/doc. I don't think it is necessary to match all other files. There is a ton of useless stuff in the PI distribution, as well as lots of old versions of sources and binaries. I don't think we should duplicate that. Also, i think we'll know when we are at the point of reorganizing. Once we've produced all the executables and binaries that we can, and we've included all relevant doc, we can declare ourselves ready to clean up. We should enter tickets for all cleanup to document our intent and expectations. 

Anyway, that's just my opinion. I'm ok with not doing it that way if you feel strongly about it.

-- Eric

**Comment by larsbrinkhoff** [comment]
I do have some strong feelings, but I'm fine with you working that way.  I'd like to do some cleanups on the way, but it's not urgent so I can wait for a while.

**Pull request merged**
