### PR TITLE
"AR" RUG for Logo 11/45

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
RUG; AR BIN  
RUG; AR 632

### CODE REVIEW

**Comment by aap** [comment]
> "RUG FOR THE TV 11/20"

Wait, what? 11/20 now? That's also what RG said but STUFF mentions a 11/10. Maybe it's a 20 after all?

**Comment by larsbrinkhoff** [comment]
Someone's paying attention!  Very good.

I don't know if this refers to the TV-11.  The amount of core is right, but note that the configuration says there's no TEN11.  AR is assembled to begin at 36000, but TV-11 wants RUG at 57100.

**Comment by aap** [comment]
RG said they only had one 11/20 and that would have been the XGP one. So what is this??

**Comment by larsbrinkhoff** [comment]
Yes, what is the TV 11/20 indeed?  I also wonder what Guy's Logo 11/45 is, and the Fredkin 11/40?

**Comment by atsampson** [comment]
Do we know anything about the hardware of the Plasma Physics TV system? Maybe it's talking about that rather than the AI TV PDP/11?

**Comment by larsbrinkhoff** [comment]
I believe the Plasma Fusion Center TV system ran on top of MINITS.  According to the MINITS configuration file the computers numbered 01, 02, 03, and 36 were TV systems:

- System 01, "NW16 Plasma Fusion Center TV system", PDP-11/23, 56K core
- System 02, "Building 38 TV system", PDP-11/23
- System 03, "Building 38 old TV system (Grinnell)", PDP-11/10
- System 36, "New AI TV system", PDP-11/3, 56K core

According to this information, none of these seem to fit the bill.

Note the "New AI TV system"!  Was there an attempt to replace the old 10-11 based PDP-11/10?

**Comment by larsbrinkhoff** [comment]
AR BIN was the last of the files known to STUFF, so we now have a complete set.

**Comment by larsbrinkhoff** [comment]
I took a look as the -READ- -THIS- files in KTV, KTVDOC, CHSKTV, and CHSGTV directories.  It seems like "KTV" is the Plasma Fusion Centerl TV system, and "GTV" is the Plasma Physics Grinnell TV system.  "CTV" is Chuck Linton's "new AI TV system".

**Comment by larsbrinkhoff** [comment]
The Grinnell TV system was online in March 1977.  Screen resolution 512x512.

**Comment by larsbrinkhoff** [comment]
Sent emails to James Kulp and Chuck Linton.

**Comment by larsbrinkhoff** [comment]
I had the wrong J Kulp.  John answered:

> Yes, all those systems (except the last) were built by me back in 1979 or so.  I believe they all used the Knight keyboard. They were tied into the ChaosNet (a precursor to Ethernet, that was similar) which was propagating around MIT, which was connected to the early ArpaNet. We accessed the various PDP-10's at MIT, particularly to run Macsyma for symbolic math which included a graphics package written by Charles Karney (cffk) in Common Lisp that displayed on the KTV. We also used Macsyma to automatically generate Fortran programs which ran on Cray computers at the Lawrence Livermore Labs to which we were connected. Pretty cool for the time.

Notes: "the last" refers to Linton's CTV.

**Comment by larsbrinkhoff** [comment]
@atsampson,

> a computer terminal facility is being developed to provide a more effective computational support for the Alcator and technology programs.  This facility will include the following features: (a) a small processor capable of supporting displays for approximately eight users, (b) a network connection for this processor to the local CHAOS network which runs at an 8 Mbit rate, (c) a graphics/document quality hardcopy device, (d) a bit-map TV display system with 16 display memories, (e) distributed console access (TV monitors and keyboards located in offices, movable on carts), and (f) display, hardcopy, and network software.

https://dspace.mit.edu/bitstream/handle/1721.1/93397/80rr018_full.pdf, page 37.

**Comment by larsbrinkhoff** [comment]
> Users in Building 38 on the main campus, as well as some users in NW16, now use the TV monitor system via the CHAOS net for connection to the VAX.  During FY83 a PFC terminal area was set up and furnished with video terminals.

https://dspace.mit.edu/bitstream/handle/1721.1/93511/84rr003_full.pdf

**Comment by larsbrinkhoff** [comment]
They also include a Versatec printer in the list of SPECIAL EQUIPMENT AND FACILITIES.

**Comment by larsbrinkhoff** [comment]
> The system consists of a CAMAC crate, with its interface and digitizers, connected to the Plasma
Physics TV display system and the Macsyma Consortium Computer.

https://dspace.mit.edu/bitstream/handle/1721.1/93466/82rr029_full.pdf

**Comment by larsbrinkhoff** [comment]
Ed Schwalenberg wrote to ITS-LOVERS:

> Years after the Knight TVs, the Plasma Physics group (John Kulp) created a similar setup.  They had a new batch of keyboards made to the Knight design, and bought much more modern display-buffer technology from Grinnell.

**Pull request merged**
