### PR TITLE
Update networking.md

### PR DESCRIPTION
**Pull request by oilcan-productions**
Updating with more detailed steps for KA10/KL10

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you!  Wow, it looks like an ordeal and a half.  No wonder I didn't get it to work.

@eswenson1 and @rcornwell, I'd like you to take a peek at the update, please.

**Review by eswenson1 — COMMENTED** [review]
Have you actually done this and verified that it worked? I can’t (I need different approach).

**Comment by oilcan-productions** [comment]
> Have you actually done this and verified that it worked? I can’t (I need different approach).

Yes, this is how I configured KA10 on my raspberry pi 400. I am re-building as KL10 now to make sure it works the same way

Mike

**Comment by rcornwell** [comment]
So far looks good. You might want to add in about manually setting IP address and how to set up NAT interface like Eric uses.

**Comment by rcornwell** [comment]
Note these configurations will also work for pdp10-ks, which supports the same IMP interface. SIMP needs to be defined in the configuration file of ITS to enable it.

**Comment by eswenson1** [comment]
I *think* I saw in networking.md something to the effect that pdp10-ks didn't support networking.  If so, we should update that.

**Review by eswenson1 — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
Approved, so let's merge this now.

**Pull request merged**
